### ISSUE TITLE
Ability to use arbirary OAuth 2.0 authorization servers

### ISSUE THREAD

**Issue by ChristianWeyer** [nraboy/ng-cordova-oauth#1]
First, nice project!

Did you ever think about providing something like a 'generic' function which takes a bunch of parameters to support OAuth 2.0 flows with authorization servers like https://github.com/thinktecture/Thinktecture.IdentityServer.v3 ?

**Comment by kromkens** [comment]
First off, nice work with this library!

Regarding the OAuth 2.0 functions: will these then also work with ADFS?

**Comment by nraboy** [comment]
Active directory is a completely different beast.  With that said, no this library will not work with ADFS.

Sorry,

**Comment by kromkens** [comment]
That's too bad then. Any idea, example or library on how to authenticate against ADFS that you know of?

**Comment by nraboy** [comment]
I don't know a single thing when it comes to ADFS.  You may try posting this question in the Ionic Framework forums.

Sorry,

**Comment by kromkens** [comment]
I finally got the OAuth 2.0 working with ADFS. It is in fact not very different from the other providers. Any interest in adding this to the library?

**Comment by nraboy** [comment]
Can you fork this repository so I can see your code?

**Comment by UnbekanntesPferd** [comment]
Are there any updates on this issue?

**Comment by nraboy** [comment]
Since this ticket has become more than one issue I'm going to close it.  If you have specific issues, please open a ticket and lets try not to get multiple topics into a single ticket.

Thanks,
