### ISSUE TITLE
How to get User Email id?

### ISSUE THREAD

**Issue by prasad8mhatre** [nraboy/ng-cordova-oauth#101]
How to get Email id of user who is currently logged in.When i say  $cordovaOauth.google(<my key>,['https://www.googleapis.com/auth/plus.me','https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/gmail.readonly']):-
    Result{"access_token":<my current access token>,"token_type":"Bearer","expires_in":"3600"}

i tried sending http GET request to www.googleapis.com/plus/v1/people/me 
but with no result.Could you help me for this.

**Comment by nraboy** [comment]
Hey @prasad8mhatre 

I don't support any of the APIs.  Once you have an access token, that is where my help stops.  I suggest you reach out in the forums or read the Google API documentation to find what you need.

Regards,
