### ISSUE TITLE
Is it necessary to enter User email id and Password to login?

### ISSUE THREAD

**Issue by prasad8mhatre** [nraboy/ng-cordova-oauth#104]
When i install my app,my app loads,then it ask the user to login via Google.When user clicks on Login button,It opens a window using inappbrowser plugin displaying user to enter User google credential and then google permission page and all.
So, I want to implement that user will directly shown google permission page as it happens in all other apps.
how can be this done?

**Comment by nraboy** [comment]
This plugin uses web oauth, not native login.  If you want to automatically log in based on the users available accounts, you'll have to find a different plugin.  Otherwise, the user will have to sign in using the web flow with this plugin.

Regards,
