### ISSUE TITLE
Authentication stucks at permission page on ios platform

### ISSUE THREAD

**Issue by prasad8mhatre** [nraboy/ng-cordova-oauth#105]
Problem statement:Authentication stucks at permission page on ios platform for google authentication
Problem reproduce:
1.When we click on login with google.
2.It ask for User id and password.
3.After entering credentials, the permission page appears.
4.in this page we have to click on "Accept" button to proceed.
5.but when we click on this, no further action is shown.
what to do?

**Comment by nraboy** [comment]
What do your logs say?  Are you testing directly on your device or simulator or are you trying to use Ionic View, Ionic Serve, Ionic Live-Reload, or PhoneGap Build?  None of the four that I just mentioned are compatible with this library.

Regards,

**Comment by prasad8mhatre** [comment]
![screen](https://cloud.githubusercontent.com/assets/2304515/8951425/3f3c10c6-35eb-11e5-9945-f74e4f2fbc7f.png)
Why offline access permission is shown every time when i login?
Because in web,mobile it doesn't ask this permission it just proceed futher

**Comment by nraboy** [comment]
I don't know what scope you are using.  Also for your other platforms it may already have a session for you.  Too many unknowns with what you're doing:

https://github.com/nraboy/ng-cordova-oauth/blob/master/src/oauth.js#L169

You can see the code for yourself.  It is following what the Google APIs ask for.

Regards,
