### ISSUE TITLE
issue when checking InAppBrowser installed or not

### ISSUE THREAD

**Issue by Mirodil** [nraboy/ng-cordova-oauth#106]
here is issue when you checking InAppBrowser installed or not:

```javascript
if(cordovaMetadata.hasOwnProperty('org.apache.cordova.inappbrowser') === true) {
...
}
```
needs to replace with this one

```javascript
if(cordovaMetadata.hasOwnProperty('org.apache.cordova.inappbrowser') === true || cordovaMetadata.hasOwnProperty('cordova-plugin-inappbrowser') === true) {
...
}
```

**Comment by nraboy** [comment]
What plugin version are you using?  What you've suggested is already in place:

https://github.com/nraboy/ng-cordova-oauth/blob/master/src/utility.js#L13-L19

Regards,

**Comment by Mirodil** [comment]
plugin from here http://ngcordova.com/docs/plugins/oauth/

**Comment by nraboy** [comment]
Again, what version are you using?  The Ionic guys don't update their repository versions as frequently as I do.  It very likely that you are using a much older version.
