### ISSUE TITLE
Unable to use with facebook login

### ISSUE THREAD

**Issue by Shivaraman-iyer** [nraboy/ng-cordova-oauth#108]
I know this is a very basic question but I have tried to get ng-cordova-auth to work on my application. and following are the codes:

mainCtrl.js:
```javascript
angular.module('seekbiggerApp')
  .controller('MainCtrl', ['$scope' ,'$cordovaOauth', function($scope,$cordovaOauth){
    $scope.login=function(){
    	// console.log('Hey');
    	alert('facebook');
	$cordovaOauth.facebook("API_KEY", ['email']).then(function(result) {
		alert('success login:'+JSON.stringify(result));
	}, function(error) {
		// error
	});
    }
  }
]);
```

I am getting the alert, but there isn't any error log coming or anything else. Can you please tell me what I might be doing wrong with this. I also want to use linkedin on the same app, and even that doesn't seem to be working.

**Comment by Shivaraman-iyer** [comment]
It was the same mistake as in the https://github.com/nraboy/ng-cordova-oauth/issues/57 Was able to fix it with the answer there. But now I just wanted to understand how to do it for linkedin as it gives me the redirect_uri is different error and I dont understand the individual options like what should I put in "state" param for the function and where should I precisely set the redirect uri on the developer website

**Comment by nraboy** [comment]
This is going to sound cruel, but you're going to have to read the LinkedIn documentation.  You're not getting errors that would lead me to believe the library is broken.  Just API misunderstandings.

https://developer.linkedin.com/docs/oauth2

Regards,
