### ISSUE TITLE
IOS webView:didFailLoadWithError - -1004: Could not connect to the server.

### ISSUE THREAD

**Issue by phanthinh** [nraboy/ng-cordova-oauth#109]
I'm using connection Linkedin with Ionicframework, but seem it's not working with error.

error - upon submitting email and pass through the login dialog I instantly get  - "IOS webView:didFailLoadWithError - -1004: Could not connect to the server."

--------------------------------------- CODE EXAMPLE --------------------------------------
Index.html using code:

App.js using code:
document.addEventListener("deviceready", function () {
$cordovaPlugin.someFunction().then(success, error);
}, false);
....
angular.module(ModuleID, ['ionic', 'ngCordova'])
....

Linkedin.js using code:
Linked.CLIENTID = "75eqw61w9zeubd";
Linked.CLIENTSECRET = "WDWHs6D4B9GUpOkW";
$cordovaOauth.linkedin(Linked.CLIENTID,Linked.CLIENTSECRET, ["r_basicprofile","r_emailaddress"]).then(function(r) {
// results
console.log("OK");
console.log(r);
}, function(error) {
console.log("FAIL LIB");
console.log(error);
});

Can you help me this issue? Also, I have test on the ion-lab and serve then it's working fine. Just only not working when build app with Xcode.

Thanks

**Comment by nraboy** [comment]
For one, don't use ionic lab or ionic serve.  It isn't entirely compatible with the library.  As for that error, did you install and configure the whitelist plugin correctly?

If I remember correctly, that error doesn't actually cause any problems.

**Comment by nraboy** [comment]
Closing due to duplicate issue: https://github.com/nraboy/ng-cordova-oauth/issues/61#issuecomment-125433849

**Comment by phanthinh** [comment]
@nraboy i make sure plugin installed, because i open linkedin  browse then enter email and password to saw this error

**Comment by nraboy** [comment]
Does it prevent you from getting access tokens?

**Comment by phanthinh** [comment]
@nraboy I don't sure error of cordova plugin. But seem application try access this url "http://localhost/callback"   when enter email and password from linkedin

**Comment by nraboy** [comment]
Again, does it prevent you from getting access tokens?

**Comment by phanthinh** [comment]
@nraboy I'm saw access_token return.

**Comment by phanthinh** [comment]
@nraboy 

Currently, my app working fine. Thank you a lot :)

Best regards.

**Comment by nraboy** [comment]
Great :-)

**Comment by montaserfzy** [comment]
The same issue happen with me after login by facebook or google plus
