### ISSUE TITLE
LinkedIn and Twitter Login result in a 404 error page before to finish que authentication

### ISSUE THREAD

**Issue by silvamarcel** [nraboy/ng-cordova-oauth#116]
Hi,

Every time I do Login with LinkedIn or Twitter, I got this error page below (It is in portuguese, but it is the same error that 404), before the flow go to the "then" function.

![screenshot_2015-08-10-14-42-24](https://cloud.githubusercontent.com/assets/1327954/9180340/4e3f41a6-3f78-11e5-9a21-b502ddfaa58a.png)

My code to login in the app is:

var ID = <myLinkedInID>;
var SECRET = <myLinkedInSECRET>;
var SCOPE = ['r_basicprofile', 'r_emailaddress'];
var STATE = 'ngCordovaOauth';
$cordovaOauth.linkedin(ID, SECRET, SCOPE, STATE).then(function(result) {
	console.log(result.access_token);
}).catch(function(error) {
	console.log(error);
});

**Comment by nraboy** [comment]
Can you translate the message for me as well as tell me what your ADB logs say?

Also confirm that you ARE NOT using ionic serve, ionic view, ionic live-reload, or phonegap build?

Thanks,

**Comment by silvamarcel** [comment]
I put here the view in English and can confirm to you that I'm not using "ionic serve", "ionic view", "ionic live-reload", or "phonegap build". I'm using "ionic run android" and this error page is directly from my device.

![screenshot_2015-08-10-20-40-22](https://cloud.githubusercontent.com/assets/1327954/9186846/303ae98a-3fa0-11e5-929a-c9f488b7c205.png)

My ADB Log is this:

D/SSRMv2:Monitor( 2369): SIOP:: AP = 330, Prev AP = 330, Duration = 10001
I/InputReader( 2369): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.2449 ] when=250509029320000
I/InputDispatcher( 2369): Delivering touch to: action: 0x0
I/InputReader( 2369): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=250509093718000
I/InputDispatcher( 2369): Delivering touch to: action: 0x1
V/WebViewInputDispatcher(10740): blockWebkitDraw
V/WebViewInputDispatcher(10740): blockWebkitDraw lockedtrue
W/ActivityManager( 2369): Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/DatabaseUtils( 2369): Writing exception to parcel
E/DatabaseUtils( 2369): java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USE
RS_FULL
E/DatabaseUtils( 2369):         at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13140)
E/DatabaseUtils( 2369):         at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2038)
E/DatabaseUtils( 2369):         at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:607)
E/DatabaseUtils( 2369):         at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
E/DatabaseUtils( 2369):         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
E/DatabaseUtils( 2369):         at android.os.Binder.execTransact(Binder.java:388)
E/DatabaseUtils( 2369):         at dalvik.system.NativeStart.run(Native Method)
D/webview (10740): blockWebkitViewMessage= false
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:302: [0810/204514:INFO:ssl_client_socket_openssl.cc(302)] [cac_debug_log][ssl_client_socket_openssl.cc] GetInstance() c
ac_state_: 0 CAC_CONTEXT_CAC: 3
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:312: [0810/204514:INFO:ssl_client_socket_openssl.cc(312)] ssl_ctx_ is used
D/SSRMv2:Monitor( 2369): SIOP:: AP = 330 (read only)
D/STATUSBAR-NetworkController( 2600): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2600): checkOverflow(384), More:false, Req:false Child:3
D/CallbackProxy(10740): sendMessageToUiThreadSync Package=in.dhouse.simplecards message=103
D/WebCore (10740): uiOverrideUrlLoading: shouldOverrideUrlLoading() returnsfalse
I/GATE    (10740): <GATE-M>DEV_ACTION_ERROR</GATE-M>
V/webkit  (10740): reportError errorCode(-6) desc(Couldn't connect to the server.)
I/GATE    (10740): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:302: [0810/204515:INFO:ssl_client_socket_openssl.cc(302)] [cac_debug_log][ssl_client_socket_openssl.cc] GetInstance() c
ac_state_: 0 CAC_CONTEXT_CAC: 3
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:312: [0810/204515:INFO:ssl_client_socket_openssl.cc(312)] ssl_ctx_ is used
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:302: [0810/204516:INFO:ssl_client_socket_openssl.cc(302)] [cac_debug_log][ssl_client_socket_openssl.cc] GetInstance() c
ac_state_: 0 CAC_CONTEXT_CAC: 3
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:312: [0810/204516:INFO:ssl_client_socket_openssl.cc(312)] ssl_ctx_ is used
D/WebView (10740): loadUrlImpl: called
D/WebView (10740): loadUrlImpl: called
D/webcore (10740):  CORE loadUrl: called
D/webkit  (10740): Firewall not null
D/webkit  (10740): euler: isUrlBlocked = false
I/GATE    (10740): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
D/webcore (10740):  CORE loadUrl: called
D/webkit  (10740): Firewall not null
D/webkit  (10740): euler: isUrlBlocked = false
I/GATE    (10740): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
E/EnterpriseContainerManager( 2369): ContainerPolicy Service is not yet ready!!!
D/EnterpriseDeviceManager( 2369): ContainerId: 0
W/LicenseLogService( 2369): log() is called by non admin
E/ViewRootImpl(10740): sendUserActionEvent() mView == null
I/SurfaceFlinger( 1945): id=878 Removed  (3/5)
I/SurfaceFlinger( 1945): id=878 Removed  (-2/5)
D/SSRMv2:Monitor( 2369): SIOP:: AP = 330 (read only)
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:302: [0810/204517:INFO:ssl_client_socket_openssl.cc(302)] [cac_debug_log][ssl_client_socket_openssl.cc] GetInstance() c
ac_state_: 0 CAC_CONTEXT_CAC: 3
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:312: [0810/204517:INFO:ssl_client_socket_openssl.cc(312)] ssl_ctx_ is used
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:514: [0810/204517:INFO:ssl_client_socket_openssl.cc(514)] ~SSLClientSocketOpenSSL()
D/CordovaLog(10740): file:///android_asset/www/scripts/controllers/HomeCtrl.js: Line 11 : User linkedinAQWmOGo5DeZQspL5OzzJ50-14JmooqP74akYuX8UKvsk1ITeB-IfEMTaHAvOBBN1csC6Sie6WW0L4jGzF-qGmVi6fKd3PEHfC
TI2-f-pEKuxDU3rPkffeE5ODTf4WEy7l8uDrU9n9nh2EvaRQ6CB4KqQnxs_pXb6XmLdhGw6yIPCGEzwqE8 is logged in with linkedin
I/Web Console(10740): User linkedinAQWmOGo5DeZQspL5OzzJ50-14JmooqP74akYuX8UKvsk1ITeB-IfEMTaHAvOBBN1csC6Sie6WW0L4jGzF-qGmVi6fKd3PEHfCTI2-f-pEKuxDU3rPkffeE5ODTf4WEy7l8uDrU9n9nh2EvaRQ6CB4KqQnxs_pXb6XmLdh
Gw6yIPCGEzwqE8 is logged in with linkedin:11
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:514: [0810/204518:INFO:ssl_client_socket_openssl.cc(514)] ~SSLClientSocketOpenSSL()
I/GATE    (10740): <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
V/chromium_net(10740): external/chromium/net/socket/ssl_client_socket_openssl.cc:514: [0810/204518:INFO:ssl_client_socket_openssl.cc(514)] ~SSLClientSocketOpenSSL()
D/SSRMv2:Monitor( 2369): SIOP:: AP = 330 (read only)

Thanks!

**Comment by nraboy** [comment]
That is weird.  You have nothing in your logs that would indicate a problem.

What version of Android are you using and are you sure everything is set up correctly in your LinkedIn and Twitter dashboards?

**Comment by silvamarcel** [comment]
Just for you know, the flow works, but this page appears every time I do login with LinkedIn or Twitter.
About my configurations, 

I have in LinkedIn:
Authentication: 
  - Default Applications Permissions: All are selected;
  - OAuth 2.0: I have 3 fields with "http://localhost/callback", "http://localhost/", "http://localhost:8100/";
  - OAuth 1.0a: Empty for both "Accept" and "Cancel"

I have in Twitter:
Application Settings:
  - Access level: Read-only
  - Callback URL: http://127.0.0.1/callback;
  - Callback URL Locked: No;
  - Sign in with Twitter: Yes.

These are my configurations, I believe that is all ok.

**Comment by nraboy** [comment]
That page should appear only for milliseconds before disappearing when using a provider that doesn't use implicit grants (LinkedIn, Twitter, Withings, etc.).  If you see it for only a moment and it disappears then all is fine because you're just suffering from a race condition.  You can get around it by providing a custom redirect_uri in the options object that points to a legit website.

If you see that screen and it doesn't go away and doesn't give you your access token, that is different.

Which is it?

Thanks,

**Comment by silvamarcel** [comment]
Thanks @nraboy, I will implement this pages later.
