### ISSUE TITLE
Issue?  Bypass credentils when user already logged in

### ISSUE THREAD

**Issue by jbarbara** [nraboy/ng-cordova-oauth#118]
Part of the appeal of open auth especially on mobile is that if you are already logged in to Facebook it would just pass on by the enter login info screen and return the token

Is this possible with this plugin?

I assume the token is saved someplace in safari's cache from previous logins to Facebook.

If this does work please someone point me in the right direction!  If not please confirm and hopefully think about a solution.

PS I trying with both g+ and fb same results, it works fine but just always requires login.

**Comment by nraboy** [comment]
You store the access token yourself.  Add some logic that checks to see if the token was saved to local storage or a cookie.  If it was not, then initiate the login flow, otherwise bypass because you already have a functional token.

Up to you how you want to design your logic for saving and checking the token.

Regards,

**Comment by jbarbara** [comment]
Yes I have done that in the app.  Its more about the first time and the expectation that they could just press register with google and it go right through without logging it saving time and effort on mobile.

Its seems to work that way with a web application.  Any ideas on what could be done to capture that?   Is it that when I log in the Facebook it saves a cookie for Facebook that is accessed bypassing the login when used via open auth to other sites?  Is this due to the fact the in app browser is walled inside the cordova app that it wouldn't be able to pull that same info (basically like a cleared cached)

**Comment by nraboy** [comment]
Yes the data is sandboxed in the application.  If you wanted to improve your process you could include the native Facebook or Google+ plugins and fallback to ng-cordova-oauth if the native applications do not exist.  The native plugins will communicate with the native app where ng-cordova-oauth is browser based.

Regards,
