### ISSUE TITLE
Please add Dribbble support!

### ISSUE THREAD

**Issue by killui** [nraboy/ng-cordova-oauth#121]

**Comment by nraboy** [comment]
Please provide a link to the Dribble oauth documentation.

Regards,

**Comment by killui** [comment]
Here the link to the Dribbble Oauth : http://developer.dribbble.com/v1/oauth/

Regards,

**Comment by nraboy** [comment]
Thanks, I'll look at it as time permits.

**Comment by albert-kay** [comment]
+1 to Dribbble support request.

**Comment by nraboy** [comment]
Unless someone else wants to take the lead on this, I can only work on this as time permits.

**Comment by nraboy** [comment]
This has been added to the development branch https://github.com/nraboy/ng-cordova-oauth/pull/129 and will be merged to the master branch this weekend.

Best,
