### ISSUE TITLE
ng-cordova-oauth.min.js has no line breaks or white space

### ISSUE THREAD

**Issue by nicksam112** [nraboy/ng-cordova-oauth#123]
The entirety of ng-cordova-oauth.min.js is on two lines, save for the first two lines which state the name and authorship. This makes it pretty much impossible to read.

Is this intentional?

Thanks, 
Nick

**Comment by marcussaad** [comment]
@nicksam112 That's a minified version, it's intended to be like that. Please refer to ng-cordova-oauth.js (without the .min in the filename).

**Comment by nraboy** [comment]
Thanks @marcussaad
