### ISSUE TITLE
Keep code DRY and module organization.

### ISSUE THREAD

**Issue by matheusrocha89** [nraboy/ng-cordova-oauth#126]
@nraboy I was looking the code here and I saw that there is many repeated lines, I want to find a better solution for that, what do you think about? 

And do you like the idea of organize each provider as a separated file? What do you think about?

**Comment by nraboy** [comment]
I'd love a better solution, but I've found that even though all providers in the library follow the oauth spec, each have slight differences.

These slight differences make it much harder to strip out duplicate code.

Open to ideas though :-)

**Comment by matheusrocha89** [comment]
Maybe the test abou cordova and inappbrowser will be a begining, I will think in something, write some code and open a pull request. Let's make this ng-cordova plugin Great :+1:

**Comment by matheusrocha89** [comment]
@nraboy BTW, I know here is not the right place but...what about 2 spaces? hahhahaahah (And now I create a war on the project) hahahahahaha

**Comment by nraboy** [comment]
I agree, let's make this project great :-)

**Comment by albert-kay** [comment]
+1 to Dribbble support request.

**Comment by matheusrocha89** [comment]
@nraboy What do you think about separate each provider in one file to avoid have just one big file with all of the providers?

**Comment by nraboy** [comment]
It is a good idea and I wanted to do that in the past but I haven't had the time.  You want to take the lead on that?

The beauty of Grunt / Gulp will allow us to make a distribution file from any number of files :-)

**Comment by matheusrocha89** [comment]
@nraboy Yes, for sure I want :) It will be a pleasure. I already started to code a solution to separate into files and to remove duplication of code. I have a free time these days, I will open a pull request soon. Do you have skype or email or whatsapp? It sometimes I want to contact you to discuss some solutions but the twitter it's not a good way. My email it's in my profile you can send your contact there if you want.

**Comment by matheusrocha89** [comment]
@nraboy When I am separating in files I'm seeing something that I don't like, the principal oauth.provider function will have a lot of params...What to do you think about?
