### ISSUE TITLE
Problems with linkedin provider?

### ISSUE THREAD

**Issue by kevbaker** [nraboy/ng-cordova-oauth#13]
I am unable to get the linkedin provider working:

$cordovaOauth.linkedin(string clientId, string clientSecret, array appScope, string state);

Can you provide a code sample for this?

I am successfully using the Facebook provider.

**Comment by jorgeram** [comment]
Hi nraboy, I have a question with linkedin too. I would be very grateful if you could help:

With facebook you only need to pass the clientId and he will return the token back, but with Linkedin how can I obtain the clientSecret from my clientId?

Thanks in advance!
Regards

**Comment by nraboy** [comment]
Not all Oauth APIs accept implicit grants.  An implicit grant only requires a client id.  For APIs that don't, you'll need to supply both a client id and a client secret.  Both these keys can be found in your providers dashboard (LinkedIn).

**Comment by jorgeram** [comment]
I've tested passing my secret key (provided by linkedin) and it works!

Thank you very much for your help and your work !! :-)
