### ISSUE TITLE
Blank page in in-app browser

### ISSUE THREAD

**Issue by xyNNN** [nraboy/ng-cordova-oauth#130]
Hey folks,

my problem is, that I can't connect to spotify (I tried facebook also) via my ionic application via oAuth.

```javascript 
            var clientId = 'my-client-id';
            $scope.connect = function () {
                $cordovaOauth.spotify(clientId, ['user-read-private', 'playlist-read-private']).then(function (result) {
                    var accessToken = result.access_token;

                    window.localStorage.setItem('spotify-token', accessToken);
                    Spotify.setAuthToken(accessToken);
                }, function (error) {
                    // error handling
                });
            };
```

I've installed the cordova plugin "cordova-plugin-inappbrowser" via 
```
cordova plugin add cordova-plugin-inappbrowser
```

Anyone knows we I've get this blank white page?!

Thanks in advance!

**Comment by nraboy** [comment]
What do your logs say? Blank page equals errors in your logs.

**Comment by xyNNN** [comment]
The problem is that I currently don't see any logs or errors. I can't test it in a browser or via ionic view because it isn't supported. How can I access the logs when I run it through the emulator via cli "ionic emulate ios"? Thanks!

**Comment by promactkaran** [comment]
if using cordova version > 5.0 , then I think you should install cordova-whitelist-plugin , and if using android 4.4 , you can connect your device and open `chrome://inspect` on a chrome tab to see the logs.

**Comment by xyNNN** [comment]
I'm using cordova 5.3.1 and use only iOS for development purposes...

**Comment by promactkaran** [comment]
you can see logs by opening safari on your mac. and then under `develop` select your device. (make sure you have safari `web inspector` ON, on your iphone.

**Comment by xyNNN** [comment]
I've started the emulator, opened the safari and click on "devop" and select under "simulator" the index.html ... I'm getting no error, but the connection to the safari debug tool works fine...

**Comment by nraboy** [comment]
If you aren't finding what you need in iOS, you may want to run it in Android and search for logs.  Just in case reporting is wonky in iOS.

Regards,

**Comment by johnrobertcobbold** [comment]
Hi @nraboy, I am now having the same problem since updating this morning to ios9.
in-app browser is just showing white page now, no error messages in the safari console log

**Comment by xyNNN** [comment]
Hey @johnrobertcobbold,

this sounds "good", hopefully we can fix this issue as fast as possible :+1:

**Comment by nraboy** [comment]
Hmm....

@johnrobertcobbold, it sounds like that could be a very valid reason.  Do you get this in the simulator as well as device?

I want to try to reproduce on my own before we jump to conclusions about iOS 9.

Thanks,

**Comment by gurusinga** [comment]
@nraboy I've got same issue here. The Facebook OAuth does not work on iOS 9, I've tested on iOS 8.3 and 8.4 and it works just fine. FYI, LinkedIn works perfectly on iOS 9

**Comment by mhartington** [comment]
Hey yall, so quick question. For those that are having these issues, have you rebuilt your apps for ios 9? Or are these apps that were already installed on your ios devices when it was runnign 8.x?

**Comment by nraboy** [comment]
Thanks for polling for more info @mhartington :-)

**Comment by xyNNN** [comment]
I had this problem only with the iOS simulator which runs on iOS 9.

**Comment by nraboy** [comment]
Can you try this?:

http://forum.ionicframework.com/t/cordovaoauth-facebook-ios-9-gm-issue/32477/2?u=nicraboy

I've heard reports you can use this temporary fix to get it working.  Not sure when Apache / Ionic will make this fix easier.

**Comment by xyNNN** [comment]
Hey @nraboy,

this temporary fix works for me. Hoping that Apache / Ionic will fix this issue as fast as possible. Thank for your investigation ;) So, we could close this issue due the fact that it isn't a issue on the side of the oauth library?! ;)

**Comment by nraboy** [comment]
I think it is an Apache Cordova issue rather than Ionic.  Someone want to take the time to open a Jira ticket with them?

The joys of upgrading Apple software :-/

Thanks,

**Comment by xyNNN** [comment]
I've created an issue in the issue tracker (see https://issues.apache.org/jira/browse/CB-9691)
