### ISSUE TITLE
Twitter not work

### ISSUE THREAD

**Issue by ZoRDoK** [nraboy/ng-cordova-oauth#131]
Because oauth_callback sent as data field.

**Comment by nraboy** [comment]
Can I get more information?  Not a lot for me to go off of.

**Comment by ZoRDoK** [comment]
Tnx for quick response.

I get "POST https://api.twitter.com/oauth/request_token 401 (Authorization Required)"  in console

When run 
$cordovaOauth.twitter(SECRET, CONSUMER_SECRET, {});

SECRET and CONSUMER_SECRET are valid, and my app work on test requests in a twitter REST panel.

**Comment by ZoRDoK** [comment]
Oh, i found solution!

Twitter not approve default callback url http://localhost/callback at all. When i changed it on app settings and set real url (real domain) all work.

Update:

I think, put oauth_callback not work at all, because after first request callback_url on twitter app settings set to empty string if not checked "Enable Callback Locking"

**Comment by nraboy** [comment]
I think there is a language barrier.  I really have no idea what you're talking about, but if you got it working, then great :-)
