### ISSUE TITLE
ngCordovaOauth for Instagram - Invalid scope field

### ISSUE THREAD

**Issue by zulhfreelancer** [nraboy/ng-cordova-oauth#133]
I followed [this tutorial](http://blog.ionic.io/oauth-ionic-ngcordova/) to create my own Ionic based Instagram Feed app. I use this ngCordovaOauth plugin to help me with the Oauth part.

But, I get stucked at this screen after login into my Instagram account.

![0](https://cloud.githubusercontent.com/assets/3416976/9981491/3f551aaa-5ff1-11e5-8d42-aab369cc6155.jpg)

This is my **app.js** so far:

```
var app = angular.module('starter', ['ionic', 'ngCordova']);

app.run(function($ionicPlatform) {
    $ionicPlatform.ready(function() {
        if (window.cordova && window.cordova.plugins.Keyboard) {
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if (window.StatusBar) {
            StatusBar.styleDefault();
        }
    });
});

app.controller('OauthCtrl', ['$scope', '$cordovaOauth', function($scope, $cordovaOauth) {

    $scope.login = function() {
        var igClientId = "example123456789";
        $cordovaOauth.instagram(igClientId, ["scope=basic"]).then(function(result) {
            alert.log(JSON.stringify(result));
        }, function(error) {
            alert.log(error);
        });
    };

}]);
```
I also try to empty the [scope](https://instagram.com/developer/authentication/) array like this:

`$cordovaOauth.instagram(igClientId, [])`

But it didn't work too.

Btw, this is my redirect URL inside my Instagram Client section:

![screen shot 2015-09-20 at 11 57 17 pm](https://cloud.githubusercontent.com/assets/3416976/9981520/77a2cd84-5ff2-11e5-8466-ce75f6221486.png)

How to solve this problem?

**Comment by nraboy** [comment]
Try downloading ng-cordova-oauth again.  I just did a merge with the development branch based on https://github.com/nraboy/ng-cordova-oauth/pull/125.

Someone contributed an Instagram change that I forgot to migrate to production.

Let me know how it goes.

Best,

**Comment by zulhfreelancer** [comment]
![1](https://cloud.githubusercontent.com/assets/3416976/9981589/bcc3a054-5ff3-11e5-9eaa-244127e2ea0a.jpg)

Ok, I've the latest one of ng-cordova-oauth. Now I get error like inside the screenshot above.

What should I do now?

**Comment by nraboy** [comment]
My assumption is that you disabled implicit grant in your Instagram dashboard:

https://instagram.com/developer/restrict-api-requests/

Find the checkbox and make sure it is enabled.

Best,

**Comment by zulhfreelancer** [comment]
You're correct man! This is my final IG Client settings:

![screen shot 2015-09-21 at 12 25 41 am](https://cloud.githubusercontent.com/assets/3416976/9981674/2e879914-5ff6-11e5-8b8e-51ae4ff3211d.png)

And now I get the access_token!

![2](https://cloud.githubusercontent.com/assets/3416976/9981677/4813a2ba-5ff6-11e5-86eb-984467f32df6.jpg)

Questions:

1. Should I store this access_token into user localStorage?
2. Does this access_token permanent or it will be change in the future?
3. If it's changing, what is the best approach for me to keep it so that user doesn't require to keep login again to use my app (see their Instagram feed)?

Really appreciate your help and thoughts!

**Comment by nraboy** [comment]
I store it in local storage.  Implicit tokens are designed to expire after one hour.  So you'll have to add logic to check the current time vs the time the token was issued.  If the token is considered expired, then the user will need to log in again.

Best,

**Comment by zulhfreelancer** [comment]
I see. So, there's no such thing like "remember me"? My user need to login every 1 hour?

**Comment by nraboy** [comment]
Explicit grants have a refresh token, but they should only be used server side.  Unless you want to build something server side, you should settle with the 1 hour expiration.

This is per the legitimate oauth spec that I followed.

**Comment by zulhfreelancer** [comment]
Sorry nraboy. I couldn't really understand it. Could you explain simpler? :)

**Comment by nraboy** [comment]
You might want to do some research on "explicit grant" and "implicit grant" for oauth.

Best,

**Comment by zulhfreelancer** [comment]
Alright, thanks!
