### ISSUE TITLE
Publish new tag to bower please

### ISSUE THREAD

**Issue by angelxmoreno** [nraboy/ng-cordova-oauth#134]
I ran 
```
$ bower install ngCordova -S
```
and got `"ngCordova": "~0.1.20-alpha"`. I ran into a few bugs like the one in #133 . I am not familiar on how publishing to Bower works but we should push the 1.4 release.

For now we can do 
```
$ bower install https://github.com/nraboy/ng-cordova-oauth.git#0.1.4
```

**Comment by nraboy** [comment]
Yea, so the Ionic Framework guys got sick of me when it came to ngCordova so they are going to be dropping my library in the next release.

I recommend you just include my library, ng-cordova-oauth, in all of its glory separate from ng-cordova.  I still have plans to support this library independent of ng-cordova.

Best,
