### ISSUE TITLE
ERR_CONNECTION_REFUSED page screen when redirecting to callback

### ISSUE THREAD

**Issue by kh411d** [nraboy/ng-cordova-oauth#137]
I've got this splash screen when redirecting to callback
-------------------------
Web page not available

The web page at http://localhost/callback?access_token=xxxxxxxxxxxxxxx 
could not be loaded because:

net::ERR_CONNECTION_REFUSED

-------------------------------

Anyway to remove this page screen??

**Comment by nraboy** [comment]
I need way more information than what you provided:

1. What provider are you trying to use?
2. What mobile platform are you using?
3. What do your device logs say?
4. Is it successful in getting you an access token even though it shows this screen?

The more information I have, the better I can diagnose what is going on.

Regards,

**Comment by kh411d** [comment]
Access token is granted successfully but when redirecting to callback url android doesn't know http://localhost so I changed it to http://10.0.2.2 and it works fine, I tested this on android J, K, and L

**Comment by nraboy** [comment]
Yea it is due to a race condition.  The only way around this is to host your own site and override the redirect_uri to use that site instead of localhost.

**Comment by Dinesh7052** [comment]
Hello ,
I am also getting this same problem , i even tried with my local ip address like http://192.168.0.45/calback
 but still getting same above mentioned error .

**Comment by nraboy** [comment]
Again this is a race condition.  Using another local address will not resolve it.  You need to use an active domain.
