### ISSUE TITLE
Android only solution

### ISSUE THREAD

**Issue by dominicholt** [nraboy/ng-cordova-oauth#138]
This properly works/authenticates with Android, but not a web browser or an iPhone. It just shows a white screen.

**Comment by mdepecker** [comment]
Hi, 
you're right  about Web Browser issue but it's pointed in the repo's readme

This library will NOT work with a web browser, ionic serve, or ionic view. It must be used via installing to a device or simulator.

About, your white screen on IOS, my guess is you're just dealing with this error : webView:didFailLoadWithError - -1200: An SSL error has occurred and a secure connection to the server cannot be made.
This is not a plugin issue, there a little crack in new IOS, and Xcode 7 (people correct me if i'm wrong)
there's a little fix, and by the way @nraboy already pointed it. (something, must be add in your .plist file)

hope it's help

**Comment by dominicholt** [comment]
Unfortunately that's not it. Just get a "cannot connect to server" error on the iPhone.

**Comment by mdepecker** [comment]
Just an other possibility, are you using ionic and live reload ? 
Sometimes live reloads not work when debugging on device !

Could you please paste some of your code ? 
I'm using it for an app at this time and this plugin works on iOS and android 
(Facebook,Twitter,google and Instagram use ) so plugin is not your problem 
There's something somewhere else

**Comment by mdepecker** [comment]
i'm really confused, i'll try to prepare a running example for @dominicholt , 
unfortunately, i'm now running the same error as @dominicholt  pointed.

everything was working this night at 2.00 am (Paris/France), 
during the night my iphone (5.0) update to IOS 9.0.1

**Comment by nraboy** [comment]
Yes iOS 9.x has all kinds of problems right now with hybrid apps.  Issues are popping up all over the forums and Google.

As of right now there is nothing I can do to correct this.  It is up to Apache Cordova to come up with a solution.

Best,

**Comment by dominicholt** [comment]
I suggest this issue be re-opened, as it actually existed prior to the update for iOS 9.x

**Comment by nraboy** [comment]
@dominicholt you've failed to give us necessary information.  No error logs, no information on deployment, etc.

Based on this it is probable to be a configuration issue on your end in the provider dashboard.

This is why I've closed the issue ticket.

Best,

**Comment by dominicholt** [comment]
Sadly the only error message I received (logs or otherwise) was "cannot connect to server", which is pretty much the same error message you get when you try to connect via the web since it is obviously not a valid website.

Since my app worked perfectly fine on Android, I doubt it is a configuration issue, but I welcome any input you might provide on differences between configuration for iOS vs Android.

Thanks.

**Comment by mdepecker** [comment]
Okay , 
@dominicholt, 
I checked a Little my code try to debug it as well and finally I've got this info 
1) this plugin works well in iOS and android
2) the error message that you get is a inappbrowser error and finally not related to this plugin
3) active safari development mode on your iOS device and plug it to your Mac
On safari select development menu and select your device name on the console tab you should see every possible log
If you console log the result of cordovaoauth.<provider>  you should get an access token.
Then for now the ticket could stay closed, since is not related to $cordovaoauth

**Comment by nraboy** [comment]
Thanks for jumping in to help out @mdepecker!

@dominicholt, I'm still waiting on the information we both requested from you.  The very first thing you mention was that it doesn't work in a web browser.  As clearly stated in the README this library will not work in the web browser.  We also asked you if you were trying to use ionic view, ionic serve, ionic live-reload, phonegap build, or similar and you didn't answer.  None of these services will work correctly with this library.  They might work, but not correctly.

If you are questioning your code, try taking a look at this:

https://github.com/nraboy/ng-cordova-facebook-example

I've personally tried that with iOS and Android and it works for both.  I encourage you to use @mdepecker troubleshooting advice as it is pretty good.

Best,
