### ISSUE TITLE
I get exception after login with my Facebook credentials and accept the application.

### ISSUE THREAD

**Issue by sivakumarbdu** [nraboy/ng-cordova-oauth#14]
CordovaWebViewClient.onReceivedError: Error code=-6 Description=net::ERR_CONNECTION_REFUSED URL=http://localhost/callback?#access_token={access_token}-asdfG3Bb9&expires_in=5181123

**Comment by sivakumarbdu** [comment]
Thanks @nraboy 

I already have http://localhost/callback in my facebook application  under Site URL and Mobile Site URL

![facebook_url](https://cloud.githubusercontent.com/assets/718851/5594320/1382cd98-926d-11e4-9064-6576791bced3.png)

**Comment by sivakumarbdu** [comment]
Am I missing anything?

**Comment by nraboy** [comment]
Just to confirm, you did install the InAppBrowser plugin, correct?

**Comment by sivakumarbdu** [comment]
@nraboy  Somehow the plugin is not installed properly when I clone the code from repo. It works perfect.   It was my mistake.

I take help from https://github.com/apache/cordova-plugin-inappbrowser/blob/master/doc/index.md for inapp browser plugin installation.

Thanks @nraboy

**Comment by nraboy** [comment]
I'm glad it worked out :)
