### ISSUE TITLE
$facebookConnectPlugin undefined

### ISSUE THREAD

**Issue by bcbeatty** [nraboy/ng-cordova-oauth#142]
I have the following code for my controller
````javascript
angular.module('my.controllers', ["ionic", "ngCordova"])
.controller('HomeCtrl', ["$scope", "$cordovaOauth", function ($scope, $cordovaOauth, $http) {
    $scope.fbLogin = function ($facebookConnectPlugin) {
        console.log('fbLogin');
        $facebookConnectPlugin.login(["public_profile", "email", "user_friends"])
           .then(function (success) {
               console.log('facebook:' + JSON.stringify(success));              
           }, function (error) {
               // error
               alert("Error: " + error);
           });
    };}]);


```
I've also tried the following:
```javascript
$cordovaOauth.facebook("MyId", ["email", "public_profile"]).then(function (result) {
            console.log('facebook:' + JSON.stringify(result));
        }, function (error) {
            // error
            alert("Error: " + error);
        });
```
with the same issue
I always get an error that  $facebookConnectPlugin is undefined.
I have  `  <div id="fb-root"></div><script src="lib/facebookConnectPlugin.js"></script>` in my index.html

What am I missing?

Thanks

**Comment by nraboy** [comment]
Sorry, I don't know what `$facebookConnectPlugin` is.  You'll have to track down the developer of it for questioning.

I can help you with `$cordovaOauth`, but I'll need a lot more information.  What is wrong with it?

Best,

**Comment by bcbeatty** [comment]
Sorry long day, similar plugins.

When I use the $cordovaOauth.facebook method, facebook gives me an error I need to login. I thought the purpose of $cordovaOauth.facebook  is to log me in. The code is above.

**Comment by nraboy** [comment]
What is the error?

$cordovaOauth uses of course Oauth.  It does not tie together with the native Facebook application.  Sure you can have the native application installed and signed into, but any app using $cordovaOauth will work independently in its own sandboxed environment.

I still need more information from you.  It is best you are not brief otherwise we're going to go back and forth for too long.

Best,

**Comment by bcbeatty** [comment]
I'm getting an error "Not Logged In: You are not logged in. Please login and try again." 
what information are you looking for?

**Comment by nraboy** [comment]
How about some screenshots?  Have you tried this?:

https://github.com/nraboy/ng-cordova-facebook-example

Sounds like your problem is probably with either your Facebook account or how you've configured your application in the Facebook dashboard.  If you're not getting any logs and it presents you with a login flow, the library is doing its job.

Best,

**Comment by bcbeatty** [comment]
I downloaded the sample, when I try to serve this in ionic, I get the following console message when I click the Oath sign in Button "Cannot authenticate via a web browser", I saw the other issues about this. Are there any workarounds for this?
But when I try to run it in an emulator I get the error message "Not Logged In: You are not logged in. Please login and try again"
![capture](https://cloud.githubusercontent.com/assets/1178347/10248726/ff1e6ee2-68e6-11e5-8efa-13a27801e86f.PNG)

**Comment by nraboy** [comment]
You're using some pretty concerning terms:

1. "when I try to **serve** this in ionic".  If you're using ionic serve, you're doing it wrong.
2. "Cannot authenticate via a web browser".  I put that error in there on purpose.

Both these are outlined in the readme of the library.  I encourage you to read it.

Regards,

**Comment by bcbeatty** [comment]
thanks, I understand those points. I used an android emulator for the screenshot. Any advice on that one?

**Comment by bcbeatty** [comment]
I got it working. It was facebook setting for urls for Valid OAuth redirect URIs, App Domains and Site URL all need to be in sync. 
I didn't have OAuth redirect URIs correct

**Comment by yashwanthm** [comment]
I have the same issue here. I have made sure that the URIs are correct and I still face the same issue.

**Comment by nraboy** [comment]
:-)

**Comment by ndelvalle** [comment]
hey @bcbeatty you said you were testing on an ionic app, what urls you used?, `http://localhost/`?.
Thanks in advanced.

**Comment by jablesauce** [comment]
@bcbeatty can you please tell me how you managed to fix the facebookConnectPlugin undefined issue please? Also, @ndelvalle did you manage to find what URLs are required please? Thanks.

**Comment by bcbeatty** [comment]
I signed in with a web page on my laptop. it gave me the true error.

**Comment by Tower450** [comment]
I have the same error, what do you mean by having the wrong Auth0 URL? 

Thanks in advance!
