### ISSUE TITLE
Why i'm saw "website not available" when connected with linkedin?

### ISSUE THREAD

**Issue by phanthinh** [nraboy/ng-cordova-oauth#144]
hi all

i'm saw "website not available" when connected with linkedin.
![4](https://cloud.githubusercontent.com/assets/5910795/10263774/0692a916-6a24-11e5-8417-645878b2c151.png)

Can you help me for this?? @pungoyal 
@seiyria 
@ballmw 
@yalamber

**Comment by nraboy** [comment]
You are suffering from a race condition.  This is common for providers that don't use implicit grants.

The only way around this is if you override the redirect_uri and use something other than localhost.

Regards,

**Comment by phanthinh** [comment]
@nraboy  

How do change localhost? It's work fine with web application and IOS, but not working with android 

Regards,

**Comment by nraboy** [comment]
$cordovaOauth.facebook(app_id, scope, {redirect_uri: "url_here"});

Make the the url matches what you put in the Facebook dashboard.

This plugin is not supported for web browser FYI.

**Comment by akuljana** [comment]
@nraboy how to return to app after redirect?
So, I have same problem with race condition. I changed redirect_uri to something like: example.com/callback and that url is opened after Facebook login.
But how to return to app after that?

**Comment by nraboy** [comment]
What do your logs say?
