### ISSUE TITLE
keeping your tokens safe

### ISSUE THREAD

**Issue by mrbm** [nraboy/ng-cordova-oauth#145]
So with ionic apps, i find that its possible to deconstuct the app (many websites that can do this) and get access to much of the code js

With your plugin (which i am using for facebook and it works great) all I give up in my code is the facebook id, but for a twitter auth I'm giving up my consumerKey and consumerSecretKey...is this not a potential security threat to my twitter account?

Love your thoughts on this.

**Comment by nraboy** [comment]
You are correct, apps are very easy to decompile:

https://blog.nraboy.com/2014/11/extract-android-apk-view-source-code/

It is safe to use oauth providers that make use of implicit grants (client key only).  Oauth providers that make use of explicit grants (client key and client secret) only should be used at your own risk.

Regardless on how safe or unsafe certain providers are, I get endless requests to add them.  I gave up the job of cyber-nanny.  My best advice would be to know what you're getting yourself into and see if it is worth it to you.

Hopefully that gives you some insight?

**Comment by mrbm** [comment]
No I get it, and I'm glad its there. Do you recommend any sorts of obufusion plugins or methods that you think would be be effective?

**Comment by nraboy** [comment]
Always obsfucate / minify your JavaScript code.  It won't stop the dedicated people from breaking in, but it will certainly deter a lot of people.

**Comment by mrbm** [comment]
If you don't mind sharing, what methods or libraries do you use?

**Comment by nraboy** [comment]
See this:

http://blog.ionic.io/minifying-your-source-code/

**Comment by mrbm** [comment]
Great post!! Thanks for all the work you are doing educating people. It's
much appreciated and helping ease the learning curve.
