### ISSUE TITLE
 ERR_CONNECTION_REFUSED page screen when redirecting to callback

### ISSUE THREAD

**Issue by Dinesh7052** [nraboy/ng-cordova-oauth#147]
Hello ,
I am also getting this same problem , i even tried with my local ip address of my server like http://192.168.0.45/calback .
but still getting same above mentioned error .

**Comment by nraboy** [comment]
As I commented on your other ticket, this is a race condition.  You need to use a live domain address rather than an IP if you wish to bypass it.

This is only for explicit grant providers such as Twitter.

Regards,
