### ISSUE TITLE
More Twitter Set Up documentation

### ISSUE THREAD

**Issue by mrbm** [nraboy/ng-cordova-oauth#148]
Loving the plugin, made it really easy for me to set up facebook authentication.

Wanted to give a go for the twitter but had a couple questions.

1. If I am making an app that works with my server where I already have twitter authentication (which i think will be a very common use case for all people using this plugin, how do I set the call back to:  
http://localhost/callback
As suggested in the readme? ( I am assuming its on the options object)

2. Can you provide an example of what goes in the options object or how to set it up?

Thanks again for your great work

**Comment by nraboy** [comment]
The plugin is not designed to work that way.  It is designed to work directly with the Twitter oauth flow, not with the flow of a personal server.

With that said, you'd either have to have the two flows (app and server) run independently, or make revisions to the library to work with your server.

Generally, the options object only contains an override for the redirect uri.  Example options.redirect_uri, in case you don't want to use http://localhost/callback.

Best,
