### ISSUE TITLE
Twitter OAuth does not work

### ISSUE THREAD

**Issue by sriram-dev** [nraboy/ng-cordova-oauth#16]
I tried OAuth with twitter with all the recommended settings as mentioned in site. I notice a problem where in , the promise always gets rejected with message
**The sign in flow was canceled**

**Comment by sriram-dev** [comment]
I did a little digging in the source code and found that , when browserref is closed , 
**https://github.com/nraboy/ng-cordova-oauth/blob/master/ng-cordova-oauth.js#L476** , the browserref exit listener gets called and hence the promise gets rejected, before the processing of main flow is completed. Exit listener might have to be removed from code. Let me know if i can submit a patch for the same.

**Comment by nraboy** [comment]
The `deferred.reject("The sign in flow was canceled")` should only be triggered if the browser was exited before one of the other promise results are returned.  A common scenario being the back button was pressed in Android.

If the sign in flow completes successfully, a resolve should be triggered before closing the browser meaning the reject is not fired.

Would you mind sharing some source code, what device or simulator you're using, and what version?

Regards,

**Comment by sriram-dev** [comment]
I am using moto G to test. Since $http is asynchronous, browser close gets called before the API call is processed. Maybe the close call can be moved inside $http call(both sucess and failure case) to avoid this. I will work on sharing source some source code.

**Comment by nraboy** [comment]
I understand what you are talking about now.

I pushed a revision.  Should correct the problem now.  However, it may flash a page not found screen for a moment.  I'm open for suggestions on fixing the flash.

I have no library recommendations.  Maybe use the official Twitter JS library and plug in the Oauth credentials?

**Comment by nraboy** [comment]
This is in the master branch.
