### ISSUE TITLE
Facebook oauth not working

### ISSUE THREAD

**Issue by YonasBerhe** [nraboy/ng-cordova-oauth#160]
I have successfully added ng-cordova-oauth to my project, I have not gotten an error anywhere in my project. I'm running the application on a Iphone and getting no problems getting the UI up. I have also registered my application with facebook and I have provided a call back URL as well http://localhost/callback. 

Any thoughts as to why I'm not receiving any tokens back?
```
app.controller('loginCtrl', function($scope, $cordovaOauth) {
  console.log('Hello World');
    $scope.facebookLogin = function() {
      console.log('Im here');
        $cordovaOauth.facebook("1705723526329009", ["email"]).then(function(result) {
        console.log("Response Object -> " + JSON.stringify(result));
        }, function(error) {
        console.log("Error -> " + error);
        });
    };
});
```

**Comment by nraboy** [comment]
How are you checking for your logs?

**Comment by matheusrocha89** [comment]
What log messages are you receiving @YonasBerhe ?

**Comment by matheusrocha89** [comment]
@YonasBerhe Still have problem with facebook? Could you print the log?
