### ISSUE TITLE
Facebook - dont complete the browser flow

### ISSUE THREAD

**Issue by dayaki** [nraboy/ng-cordova-oauth#164]
When a user enter his email/password to login with facebook, I get the returned data but the page stays on the login page, the flow dont complete.

**Comment by matheusrocha89** [comment]
Did you configure the URL callback on your facebook app page? You need to configure to `http://localhost/callback`

**Comment by dayaki** [comment]
Yes, I configured it to be http://localhost/callback

**Comment by dayaki** [comment]
I inspected the webview and it seems its popping up two instances of facebook login. see image below

<img width="941" alt="sc" src="https://cloud.githubusercontent.com/assets/815619/11244252/e3c1f6b4-8e0c-11e5-8b87-8d30a1a73371.png">

**Comment by nraboy** [comment]
Can you confirm that you're NOT using ionic serve, ionic live-reload, ionic view, or phonegap build in your testing process?  All of these are incompatible with ng-cordova-oauth.

**Comment by dayaki** [comment]
I am not using any of these....I build and run the app on my Android device..v5.1

**Comment by matheusrocha89** [comment]
@dayaki can you show us how are you calling the oauth for facebook? Cause I used recently and with me it was only calling once and the flow works fine.

**Comment by dayaki** [comment]
This is how am calling it:

$scope.fbSignup = function() {
    $cordovaOauth.facebook("744971867140902", ["email"]).then(function(result) {
      $localStorage.accessToken = result.access_token;
      $state.go('app.home');
    }, function(error) {});  
  };

** I change the client_id to randon numbers here.

**Comment by dayaki** [comment]
Sorry, Problem was from my end, I was calling the fbSignup() twice. Sorry for the troubles.
