### ISSUE TITLE
Test Staging Branch for 0.2.0 Major Refactor

### ISSUE THREAD

**Issue by nraboy** [nraboy/ng-cordova-oauth#167]
Please everyone provide their 0.2.0 testing results in this issue ticket.

Thanks,

**Comment by nraboy** [comment]
Here is the staging branch:

https://github.com/nraboy/ng-cordova-oauth/tree/staging

**Comment by nraboy** [comment]
**Twitter**: Working

**Comment by matheusrocha89** [comment]
**Instagram**: Working

**Comment by matheusrocha89** [comment]
**Facebook**: Working

**Comment by matheusrocha89** [comment]
**Github**: Working

**Comment by matheusrocha89** [comment]
**Spotify**: Working

**Comment by matheusrocha89** [comment]
**Dropbox**: missing injections already created a pull request #169 and tested with the pull request code, it's working. When the pull request be merged it will fix the problem in staging version

**Comment by matheusrocha89** [comment]
**Slack**: Working

**Comment by nraboy** [comment]
Merged #169

**Comment by billy124** [comment]
@nraboy Twitter is working, however for a split second I see an android 404 'web page not available' screen, is there a property I need to inject to avoid this screen?

**Comment by nraboy** [comment]
Twitter, and all other explicit grant types in ng-cordova-oauth, will show a 404 when using localhost as the callback.  This is because of a race condition hit when trying to do X amount of requests before closing the browser.

You have two options:

1. Live with the 404
2. Override the redirect_uri in the options parameter and set it to match in the Twitter dashboard.  You'll have to host the redirect_uri somewhere so it actually exists via a web browser.  Otherwise you'll continue to get a 404 error

Best,

**Comment by matheusrocha89** [comment]
-- UPDATE --
**Dropbox**: Working

**Comment by matheusrocha89** [comment]
**Google**: Working

I think we already tested the most famous ones. What do you think @nraboy ?

**Comment by nraboy** [comment]
@matheusrocha89 can you test LinkedIn with this?  https://github.com/nraboy/ng-cordova-oauth/issues/172

**Comment by matheusrocha89** [comment]
**Linkedin**: Working

@nraboy Tested now and it's working, I received the access_token just fine.

**Comment by nraboy** [comment]
Staging branch 0.2.0 has been merged into the master.  Great work @matheusrocha89!

**Comment by matheusrocha89** [comment]
@nraboy great work for you too, you created the project and this is a very important part.

**Comment by xunxdd** [comment]
thanks a lot, works fine. Have read your articles a lot, very helpful.
