### ISSUE TITLE
LinkedIN authentication returning "Problem authenticating" while the app is actually approved in LinkedIN dashboard

### ISSUE THREAD

**Issue by Requiescat** [nraboy/ng-cordova-oauth#168]
Hi @nraboy,
first of all, thanks a lot for your work ! I'm currently using your sample code https://github.com/nraboy/ng-cordova-oauth-example before implementation in my app.

I'd like to address an issue I have since I am actually able to approve the app with the library (app is show in linkedin approved app dashboard) but the console is returning a "Problem authenticating" error...

Here is the code I use for android platform. I've overridden the uri to avoid the "webpage not available" error I had previously after the inapp browser issue: https://github.com/nraboy/ng-cordova-oauth/issues/57.

```javascript
$scope.linkedINLogin = function() {
        $cordovaOauth.linkedin("id", "secret", ["r_emailaddress"], "randomstring", {redirect_uri: "http://google.com"}).then(function(result){
            console.log(JSON.stringify("res: "+result));
        }, function(error) {
            console.log(JSON.stringify("error: "+error));
        });
    }
```

ionic version: 1.7.10
cordova version: 5.3.3
**ng-cordova-oauth - v0.1.4 (2015-06-28)**

Thanks for you help,
Adrien.

**Comment by matheusrocha89** [comment]
What is the error message the function returns? Could you print it here?

**Comment by Requiescat** [comment]
It's just: 1     316765   log      "error: Problem authenticating"

**Comment by matheusrocha89** [comment]
@Requiescat take a loot on this issue: https://github.com/nraboy/ng-cordova-oauth/issues/32 See if can help you

**Comment by Requiescat** [comment]
Thanks @matheusrocha89 unfortunately, I've tried everything mentioned in #32. I manually pass the url (with the code generated by ngcordovaautho) through my browser and clearly get a positive answer from it: {"access_token":"xxxxxxxxxxxxxxxx","expires_in":5183999} so I don't understand why it fails in the post... Maybe @marcsallent has an idea?

**Comment by Requiescat** [comment]
In fact I figured out this issue only shows up when I'm launching in -console mode...

**Comment by bogini** [comment]
This is a CORS issue
