### ISSUE TITLE
usage example uses a deprecated google scope

### ISSUE THREAD

**Issue by robotvert** [nraboy/ng-cordova-oauth#17]
As per [google's login scopes doc](https://developers.google.com/+/api/oauth#login-scopes) the scope `userinfo.email` scope featured in the example in the README is deprecated.

Since many people blindly copy/paste the sample code, me thinks the example should be updated.

For now the non deprecated, oauth based equivalent seems to be `https://www.googleapis.com/auth/plus.profile.emails.read`, while the "real" equivalent would be OpenID Connect's `email` but this plugin doesn't handle this, does it?

**Comment by nraboy** [comment]
Thanks for pointing this out! It is difficult for me to keep track of everything, so this is much appreciated.

I wan't to say `email` won't work, but you can always give it a try.  I'll update the documentation some time this week to reflect.

Thanks,

**Comment by robotvert** [comment]
Tried already :wink: 
The API returns an invalid scope error after the user enters its credentials.
I'm not so familiar with it but it seems the OpenID Connect dance is slightly different (even though it's based on Oauth).

**Comment by nraboy** [comment]
Well I appreciate you trying :)

**Comment by robotvert** [comment]
My bad, I read the doc like stupid yesterday.

Actually simply setting `email` as the scope instead of `https://www.googleapis.com/auth/userinfo.email` works like a charm.

**Comment by nraboy** [comment]
Thanks for the update!

**Comment by nraboy** [comment]
This change to the README is now in the master.
