### ISSUE TITLE
LinkedIn Problem Authenticating localhost/callback server unexpected error

### ISSUE THREAD

**Issue by xxvii27** [nraboy/ng-cordova-oauth#172]
I got problems authenticating with linkedIn, which in this case the problem comes after inputting my email and password, I got server returned an unexpected error, which results getting an undefined authorization code for the next step. I am using ionic in an android environment. It works fine for facebook and twitter. I have verified my LinkedIn settings, and ensure I have the correct permissions.

**Comment by nraboy** [comment]
Can you try it with staging branch https://github.com/nraboy/ng-cordova-oauth/issues/167

**Comment by xxvii27** [comment]
same thing

**Comment by nraboy** [comment]
I asked @matheusrocha89 to test this if he has time.

**Comment by matheusrocha89** [comment]
@nraboy I will test now to see what could be the problem. Later maybe I will have an answer for you guys.

**Comment by matheusrocha89** [comment]
@nraboy Tested linkedin and it's working... @xxvii27 can you print your console log? Does your app has been already approved for using the scopes you are requesting?

**Comment by xxvii27** [comment]
There are some parse headers when I perform the request is that the problem ? It's weird cause Facebook and Twitter works fine. The cordova inappbrowser basically returned this 
https://www.dropbox.com/s/eg7kyka1ckd3skj/Screenshot_2015-12-04-18-01-01.png?dl=0

**Comment by xxvii27** [comment]
Can I see your sample, if you don't mind ?

**Comment by matheusrocha89** [comment]
yeah, sure. It's a very simple code @xxvii27 

```javascript
$cordovaOauth.linkedin('<client_id>', '<client_secret>', ['r_basicprofile'], 'DCEeFWf45A53sdfKef424').then(function(result) {
    console.log(result);
  }, function(error) {
    console.error(error);
  }
);
```

**Comment by nraboy** [comment]
@xxvii27 do we have an update on this?

**Comment by xxvii27** [comment]
same thing, the problem happens because linked_in response with an error redirect, so that the plugin cannot get the authorization code from the url.

**Comment by nraboy** [comment]
My assumption is you have something configured incorrectly in your LinkedIn account.  We cannot reproduce your problem.

**Comment by xxvii27** [comment]
My bad, I used my secondary email to login, works perfectly, using my primary email.
