### ISSUE TITLE
cannot authenticate via a web browser, using simulator.

### ISSUE THREAD

**Issue by jigsawsoul** [nraboy/ng-cordova-oauth#173]
Hi,

I wonder if you can help, I'm receiving the following error; cannot authenticate via a web browser.

I have followed the following tutorial, http://blog.ionic.io/oauth-ionic-ngcordova/ 

Everything is setup as the examples, I understand there are issues running this using ionic view, live-reload. Although from my understand this should function correctly on Xcode's simulator and devices?

Thanks in advanced,
Richard

**Comment by matheusrocha89** [comment]
@jigsawsoul yes, it should, and I test the ng-cordova-oauth on android emulator Genymotion and works fine, on my android smartphone too.

**Comment by jigsawsoul** [comment]
Are you able to test in iOS simulated without any issues, using ionic emulate?

**Comment by matheusrocha89** [comment]
let me test here

**Comment by matheusrocha89** [comment]
Yep, works fine on iOS simulator too

**Comment by jigsawsoul** [comment]
Are you using ng-Cordova as the tutorial? Or ng-oauth-Cordova?

This is strange :(

**Comment by matheusrocha89** [comment]
Yes, i did this a few minutes ago, works perfect

**Comment by jigsawsoul** [comment]
Okay great I'll double check everything my end and get back to you ASAP

**Comment by matheusrocha89** [comment]
@jigsawsoul Ok, let me know if you still have problems with it

**Comment by nraboy** [comment]
If you're having issues on iOS, make sure you created an ATS policy.  Otherwise requests will be blocked:

https://blog.nraboy.com/2015/10/fix-ios-9-app-transport-security-issues-in-apache-cordova/

Best,

**Comment by jigsawsoul** [comment]
Hi,

I have followed the video, although I don’t have the problem with ATS as you showed within the video.

Could you share a basic working example, I could download and run for testing.

Thanks so much for your help.

**Comment by matheusrocha89** [comment]
@jigsawsoul if you want an small app to test the oauth you can use https://github.com/nraboy/ng-cordova-oauth-example

**Comment by nraboy** [comment]
Have not heard a response in more than 10 days and cannot reproduce.  Closing the issue.
