### ISSUE TITLE
window.cordova.InAppBrowser.open undefined

### ISSUE THREAD

**Issue by claykoh** [nraboy/ng-cordova-oauth#179]
Hey there,

I'm trying to use this plugin but I'm getting the error:
```
undefined is not an object (evaluating 'window.cordova.InAppBrowser.open')
```
Any ideas? I have the inappbrowser plugin installed -- it works via window.open and ngCordova's $cordovaInAppBrowser method

A note: I'm definitely using this library and not ngCordova's version

Thanks!

**Comment by nraboy** [comment]
What provider are you trying to use?

**Comment by claykoh** [comment]
stripe, but I believe it will throw this error on every provider

**Comment by nraboy** [comment]
Try a different one just for the heck of it.  A more popular one like Facebook or Google.  Trying to narrow things down.

**Comment by claykoh** [comment]
Just tried with facebook -- same deal -- if it helps I get the same error when trying to use ngCordova's version of the oauth plugin

**Comment by nraboy** [comment]
What version of Apache Cordova are you using and are you using Android or iOS?

**Comment by claykoh** [comment]
Cordova version 5.4.1 -- iOS

**Comment by claykoh** [comment]
It appears this was caused by trying to access the ng-cordova-oauth functionality before the deviceReady event had been called. Everything appears to work -- sorry for the mistake

**Comment by cseer90** [comment]
![image](https://cloud.githubusercontent.com/assets/5494279/12414547/26976926-bebc-11e5-96a6-cc6f98d6d88c.png)
I wrapped up the call within deviceready, yet it doesn't seem to work. I tried to log InAppBrowser object but it shows as undefined. However, isInAppBrowserInstalled() function returns true! Not really sure what's the issue? :/

**Comment by matheusrocha89** [comment]
Strange, try to remove and install again the inAppBrowserPlugin and try your code again.

**Comment by cseer90** [comment]
Been there. Done that. No help. I guess my InAppBrowser plugin has got corrupted. Anyways, removing the platform and adding it again helped. This might help someone else too. Also, I had updated my Cordova before doing this so if re-adding platform doesn't help, update Cordova as well!

**Comment by matheusrocha89** [comment]
:+1:

**Comment by dcoferraz** [comment]
I had the same issue and upgrading the `cca` to version `0.8.1` solved the issue!
Thanks @cseer90 for the help... Spent a whole day without luck until I found this solution!

**Comment by ziagiseldina** [comment]
It was the same for me. I removed the ios platform and then I added it and it came back to work.
First I tried to remove and add the plugin but it was not helped.

**Comment by Manindarn** [comment]
I'm facing same issue, In my app we used iOS platform version 4.1.0. As per your above suggestion I removed and added the platform still having the same issue, kindly someone help below issue for Cordova iOS InAppBrowser. 
typeerror undefined is not an object(evaluating.cordova.inappbrowser.open)
