### ISSUE TITLE
Error in Success callbackId: InAppBrowser ... : TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by RobiFerentz** [nraboy/ng-cordova-oauth#180]
I'm getting the error in the title and I'm pretty sure it has something to do with the callback uri. 
I've set the linkedin callback uri as instructed.
![screen shot 2015-12-24 at 09 31 04](https://cloud.githubusercontent.com/assets/4889861/11991298/5a6b4fd8-aa21-11e5-9354-911d431c4899.png)

But the error persists no matter what I do. (like creating an actual file named callback in my ionic www folder) .
Is it something I'm missing?

**Comment by nraboy** [comment]
What provider are you trying to use?

**Comment by RobiFerentz** [comment]
Never mind. I kept getting callback urls without the 'code=' querystring because of errors related to the fact that the linkedin auth page doesn't trim usernames. 
Although, I probably would add some checks before calling split . In case of such errors.

Aside from that, the code works well. Thanks.
