### ISSUE TITLE
Incorrect parsing of Venmo's response

### ISSUE THREAD

**Issue by kshaaban-** [nraboy/ng-cordova-oauth#183]
The plugin currently expects the `access_token` to be returned as a **hash** parameter of the `redirect_uri`. It also expects the response to have a `expires_in` time.

But according to the current [Venmo API Docs](https://developer.venmo.com/docs/authentication), the `access_token` is returned as a **query** parameter in the `redirect_uri`.
And for the Client Side Flow, all generated tokens expire after 30 minutes of the time they were issued so no `expires_in` parameter is returned.

**Comment by nraboy** [comment]
This has been merged to development
