### ISSUE TITLE
Getting "you are not logged in" error in facebook .

### ISSUE THREAD

**Issue by AtulaGuleria** [nraboy/ng-cordova-oauth#186]

**Comment by matheusrocha89** [comment]
This lib have a dependencies of inAppBrowser Plugin, you can't test on a browser, just on emulators or devices, see the README description of the project.

**Comment by nraboy** [comment]
Is there an issue?  Original poster gave us no details.

**Comment by AtulaGuleria** [comment]
#matheusrocha89 
I am using it on my android device. 

#nraboy
When I am logging in fb , I am getting this error "you are not logged in" 
N my page just stop there

**Comment by nraboy** [comment]
Still not really any information to go off of.  We can't help you without all the details.  Are you getting through the entire flow?  Do you get that message somewhere during the flow?  Does this error show up in the logs or the UI? Etc.

My guess, without the details, is that you're getting this error when trying to use the Facebook API, not oauth sign in.

Regards,

**Comment by AtulaGuleria** [comment]
Yes I am getting this error during the flow .
When I press the log in button then a new error page opens up and saying ' you are not logged in'.

**Comment by AtulaGuleria** [comment]
I have checked my fb api and set my callback url as " http://localhost/callback".
Please guide.

**Comment by nraboy** [comment]
This page happens before prompting you with an opportunity to enter credentials?

**Comment by AtulaGuleria** [comment]
Yes
It does.

**Comment by nraboy** [comment]
Sounds like you haven't configured something correctly in the Facebook developer dashboard.  I encourage you to read through their documentation.

**Comment by nraboy** [comment]
You get this error because you didn't set the oauth callback correctly.  I had this problem the other day.

**Comment by ser-j** [comment]
Hi
Can someone help me ? :)

I have a similar problem, like  AtulaGuleria  had. When I pressed login btn, I got error "Not logged in: You are not logged in. Please login and try again"

![mibile_screen](https://cloud.githubusercontent.com/assets/3288143/19143625/f1383d40-8bad-11e6-8969-6a452e88d6d4.png)

I am trying to test it with Phonegap Developer App on iOS device (also tried with android (the same result)).

I have investigated this issue, and looks like it related to FB app configuration, specifically "Valid OAuth redirects url field" in Client OAuth settings? But I am not sure what should be there if I am using mobile APP(not web version).

![oauth_settings](https://cloud.githubusercontent.com/assets/3288143/19143759/a12b3464-8bae-11e6-88f0-efdd10b9b029.png)

Also I have added iOS platform to FB APP, I got a bundle ID in config.xml file. Is it correct? Or how I have to configure iOS platform? What I missed?

![ios_app_settings](https://cloud.githubusercontent.com/assets/3288143/19143839/0d4c15b4-8baf-11e6-8c0a-96f71d231a3c.png)

And here is a code example in Angular which I was using:
![code](https://cloud.githubusercontent.com/assets/3288143/19143867/33ff58ba-8baf-11e6-9bb0-67152e25e1b6.jpeg)

PS: I have tried the same with vkontakte, and it works for me. THANKS!

Please ask if I was missing something? I will provide any extra information.
