### ISSUE TITLE
Best way to implement both native android & web oauth approaches

### ISSUE THREAD

**Issue by gmork** [nraboy/ng-cordova-oauth#187]
This works like a charm on a native device for Twitter and Gmail, great work! The only thing needed after installing the plugin was removing the original OAuth.io javascript API from my index.html. However, if I ever want to use the same codebase for both the Android device and a Web approach (e.g. desktop client) I will need to put some conditional logic in place for this.

Bringing me to the actual question: on what level should this be done best? One could query for the used device in the app.js itself and use different OAuth objects for both approaches. But one could probably just as well rely on the ionic build system to alter some variable and keep the same JS code in place for both approaches (seems like a cleaner solution). Maybe there are even other options?

Since I've only just started using Ionic any help would be much appreciated!

**Comment by nraboy** [comment]
Sorry, this library makes use of Apache Cordova plugins.  It will never work in a web browser and there are no plans to try to change this.

You'll have to come up with your own solution if you wish to expand this library beyond mobile.

Regards,
