### ISSUE TITLE
Please consider rename the generic names of the factories as $facebook or $google

### ISSUE THREAD

**Issue by gpincheiraa** [nraboy/ng-cordova-oauth#189]
Hi!
I've been using this library for authenticate with the social networks and works pretty neat, But because that the names of the factories as $facebook are too much generic, i've get problems with names in collision. A example for this, it's the case with the library https://github.com/GoDisco/ngFacebook. 
I'd suggest change this name for others less generic like `$ngCordovaFacebook` or `$ngFacebookCordova`. Also i'd suggest that use of **IIFE** in the files of this library, because the names of functions are also too much generic and they'll collide with third party libraries or developer code that use this library.

Best regards

**Comment by matheusrocha89** [comment]
@nraboy what do you think about that?

**Comment by nraboy** [comment]
I don't mind if the internals change, but the convention $cordovaOauth or $cordovaOauth.Facebook will not.

To summarize, as long as end users of ng-cordova-oauth don't experience breaking changes I am fine.

Can you verify that this is what you mean?

**Comment by matheusrocha89** [comment]
Yes, this is what I mean. Just inside changes, no user end break changes

**Comment by nraboy** [comment]
I'm fine with this

**Comment by matheusrocha89** [comment]
Ok, I will try to do this tonight

**Comment by nraboy** [comment]
This is now in the master
