### ISSUE TITLE
$cordovaOauth.google is not a function

### ISSUE THREAD

**Issue by Manindrateja** [nraboy/ng-cordova-oauth#191]
$cordovaOauth.google is not a function
i added dependencies as mentioned.

**Comment by matheusrocha89** [comment]
Can you give me more information? Snippet of you code, where are you testing it?

**Comment by Manindrateja** [comment]
$cordovaOauth.google(clientId, ["https://www.googleapis.com/auth/urlshortener", "https://www.googleapis.com/auth/userinfo.email"]).then(function(result) {
                console.log(JSON.stringify(result));
            }, function(error) {
                console.log(error);
            });

i added $cordovaOauth in my contoller as dependency

**Comment by nraboy** [comment]
Did you inject it into your angular module?  Did you include it to the scripts area of your index.html?

**Comment by Manindrateja** [comment]
I did inject it, otherwise adding dependency would have given an error

i tried console.log of  $cordovaOauth ,  i got some only 6 months in that
something like show and etc..

**Comment by gpincheiraa** [comment]
If you do `console.log($cordovaOauth)`, what do you get?

**Comment by nraboy** [comment]
Original requestor is unresponsive.  Closing the ticket.
