### ISSUE TITLE
Race condition problem - Web page not available

### ISSUE THREAD

**Issue by akuljana** [nraboy/ng-cordova-oauth#192]
After Facebook login, I'm redirected to:

"Web page not available
The web page at http://localhost/callback?access_token=xxxxxxxxxxxxxxx 
could not be loaded"

I changed redirect_uri to active domain, something like: example.com/callback and that url is opened after Facebook login.

But how to return to app after that?

**Comment by cainmodyo** [comment]
I got the same issue with Twitter, in an Ionic App.
I'm using inAppBrowser & whitelist Plugins, sha.js v1.6.
browserRef trigger loaderror due net::ERR_CONNECTION_REFUSED

Any ideas?

**Comment by nraboy** [comment]
What do your logs say?

You're not using ionic serve, ionic live reload, or ionic view, correct?

**Comment by cainmodyo** [comment]
I'm testing in a real android device. inAppBrowser is open, after authentication it go to callback url (http://localhost/callback?access_token=xxxxxxxxxxxxxxx ), but get net::ERR_CONNECTION_REFUSED on screen.
I added a listener to loaderror event in browserRef and it is triggered.

**Comment by nraboy** [comment]
Interesting, I'm wondering if Apache made a change that sends localhost to the error listener now.  @matheusrocha89 do you want to help me add `loaderror` events to all the providers?

**Comment by matheusrocha89** [comment]
@nraboy I will help for sure. The last update of inappbrowser plugin was 6 days ago. I didn't update the plugin on my ng-cordova-oauth-example project and it's working, I will try to update later and see if I can reproduce the same error.

**Comment by cainmodyo** [comment]
Hey guys, thanks in advance, more info about versions.
I removed inappbrowser v1.2.0, and added v1.0.0 > cordova plugin add cordova-plugin-inappbrowser@1.0.0
Now, when it try to redirect to http://localhost/callback?xxxxx, both events are triggered 
for a second the screen show net::ERR_CONNECTION_REFUSED and then get back to the app correctly.

**Comment by nraboy** [comment]
So can we conclude that the problem exists only in the InAppBrowser versioning and not Apache Cordova base?

**Comment by akuljana** [comment]
Confirming, after removing inappbrowser v1.2.0 and adding v1.0.0. problem is solved.
Thank you!

**Comment by Leeaandrob** [comment]
@cainmodyo I did downgrad for v1.0.0 and I had the same error, http://localhost/callback?xxxxx, the screen show net::ERR_CONNECTION_REFUSED.

Any solution?

Thanks

**Comment by matheusrocha89** [comment]
@akuljana @Leeaandrob @cainmodyo we moved this issue to here #193
