### ISSUE TITLE
InAppBrowser 1.2.0+ Breaks Library

### ISSUE THREAD

**Issue by nraboy** [nraboy/ng-cordova-oauth#193]
Figured this would be the best thing to do since I'm getting messages on every platform that I use.

Apache Cordova released version 1.2.0 of their InAppBrowser plugin.  In this version, dead or non-existent pages will trigger the `loaderror` event listener rather than still piping into the `loadstart` event.  The ng-cordova-oauth library currently expects that all page load events end up in the `loadstart` listener regardless on if they exist or not.

Why does ng-cordova-oauth currently fail?

ng-cordova-oauth by default will use http://localhost/callback as the redirection and `loadstart` listener.  Because this URL will never exist, it will now never make it into the `loadstart` event, but the `loaderror` instead.

The fix?

There are three things you can do:

1. Downgrade to the Apache Cordova InAppBrowser version 1.1
2. Host your own callback URL and override the optional `redirect_uri`
3. Wait patiently for me and @matheusrocha89 to get a permanent fix in place

To consolidate all the messages, it would be appreciated if everyone is directed to this GitHub issue.  It will contain updates on the issue and reflect resolution when ready.

cc @mlynch @pbernasconi @mhartington

**Comment by matheusrocha89** [comment]
@akuljana @Leeaandrob @cainmodyo

**Comment by xyberzues** [comment]
Suppose I am in LoginCtrl, in the browser the URL is "http://localhost/#/app/login", is this same redirect_uri I use ng-cordova-oauth, assuming in-appbrowser is enabled

**Comment by nraboy** [comment]
Until a fix is put into place, anything localhost will not work as a `redirect_uri`.  You must host a page for example, http://www.yourwebsitehere.com/callback and use that instead.  Because when the browser hits it, the page will actually exist and not error out.

**Comment by landa18** [comment]
im using ionic, i remove inappbrowser plugin and then install a lower version

cordova plugin add cordova-plugin-inappbrowser@1.0.0

this solve the problem for me.

**Comment by xiaoerge** [comment]
Downgrading doesn't fix every issue.

With InAppBrowser 1.0.0

Android 4.1 works
Android 5.1 works
Android 5.1.1 same localhost error

**Comment by rbarriuso** [comment]
As a workaround, you can listen for the "loadstop" event to sniff the URL.

**Comment by Leeaandrob** [comment]
I have that change this for FIREBASE :(

**Comment by nraboy** [comment]
@matheusrocha89 and I found reports that this is an actual bug with the InAppBrowser plugin and not a change in features:

https://issues.apache.org/jira/browse/CB-10407
https://github.com/apache/cordova-plugin-inappbrowser/pull/136

The library still works fine in iOS, but not Android.  Has to do with the new WebViewClass.

**Comment by nraboy** [comment]
It looks a fix was moved to the master branch for InAppBrowser, but a tag has not yet been created:

https://github.com/apache/cordova-plugin-inappbrowser/commit/8da5e25eeee892590f3ddb781a4fde8e9f8ef512

**Comment by jwuliger** [comment]
This sticks. I just tried the new code and I get Ionic build errors with that change.

**Comment by nraboy** [comment]
So you get different problems with the new InAppBrowser master?

**Comment by jwuliger** [comment]
Yeah. I used @master and the new method that was added to the android Java won't compile. I downgraded to version 1.1.1 to get my app working again.

**Comment by nraboy** [comment]
Unfortunately I think we need to sit and wait for a few days until Apache corrects this.  I see other people reporting issues to them as well.

**Comment by jwuliger** [comment]
Yeah. Hopefully soon! The latest version of the Splashscreen plugin is broken also. At least for android. It's been crazy!

**Comment by nraboy** [comment]
So the Apache Jira says that the master branch is currently in testing, but won't see a tag until everything is done which could take X amount of days.

If you wish to use the master branch instead of the stable tags, you can do something like this:

```
cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser
```

Be warned because they say other stuff broke as well.

Best,

**Comment by matheusrocha89** [comment]
@nraboy Cordova 6.0 released but the version of inappbrowser is pinned on 1.2.0 in this release version. I think we need to wait a little more

**Comment by raminalievru** [comment]
How do you correct an error in AppBrowser in case of authorization in an application made in Cordoba ? 

while Ionic Framework is used and cordovaOauth library in $cordovaOauth.facebook recall method, an error in IOS appears (see the screenshot). 

The error is shown on the  "isInAppBrowserInstalled" function, in the cordovaOauth library , it says it cannot locate inAppBrowser while it is switched on and works fine in android.

screenshot: https://www.dropbox.com/s/x2briaaqjikt13z/IMG_9607.PNG?dl=0

**Comment by rastermax** [comment]
Thanks for catching that.
I have the same issue with openFB (small rest fb lib).
for now using 1.1.1 of InAppBrowser.

**Comment by nraboy** [comment]
Someone reported that 1.2.1-dev fixes the issues.  Can be seen here:

https://github.com/nraboy/ng-cordova-facebook-example/issues/1#issuecomment-178209221

I've not verified this, but in any case it is not a stable release yet.

**Comment by jduelfer** [comment]
I am currently using 1.2.2-dev and i get the same problem with Google.

**Comment by nraboy** [comment]
The following shows they are still working on it:

https://issues.apache.org/jira/browse/CB-10407?focusedCommentId=15128111&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15128111

Best,

**Comment by craigvl** [comment]
Getting same issue on 1.2.0

**Comment by nraboy** [comment]
@craigvl yes we know, that is why I made this ticket.

**Comment by nraboy** [comment]
Rumor has it that this has been now corrected as seen in this comment:

https://github.com/nraboy/ng-cordova-facebook-example/issues/1#issuecomment-181395917
https://cordova.apache.org/news/2016/02/04/plugins-release.html

I've not verified though.

**Comment by jwuliger** [comment]
Nice! I will have to test this out.

**Comment by jwuliger** [comment]
Well, I can confirm that it works. Infact it works really well. It seems to be allot faster!  :+1:

**Comment by nraboy** [comment]
Sounds promising :-)

**Comment by matheusrocha89** [comment]
:+1: Great news.

**Comment by nraboy** [comment]
Just tested ng-cordova-oauth with Apache Cordova 6.0 and the InAppBrowser 1.2.1 and it worked flawlessly.

Looks like everything is back to normal again.  I encourage everyone to get the latest version of ng-cordova-oauth though.

Best,

**Comment by matheusrocha89** [comment]
They released the 1.3.0 version today. I think it's stable too.

Em qua, 10 de fev de 2016 11:32, Nic Raboy <notifications@github.com>
escreveu:

**Comment by akkimads** [comment]
in linked developer.com, what should we write in all callback urls fields ?

**Comment by domharrington** [comment]
This is still broken for me with cordova 6.1.1 and cordova-plugin-inappbrowser 1.4.0. Is anyone else still having problems?

**Comment by rastermax** [comment]
last time i checked it worked again. will soon rebuild my app and review my facebook stuff, will let you know if I see differences.

**Comment by m-vdv** [comment]
I'm experiencing the same as @domharrington described.

**Comment by jeslomo** [comment]
Hi, i've the same problem that @m-vdv and @domharrington .

I've Ionic version: 1.3.1, cordova  6.1.1 and cordova-plugin-inappbrowser 1.4.0 "InAppBrowser".

**Comment by domharrington** [comment]
I ended up resorting to using a redirect_uri that is a live site. This means the inappbrowser resolves and then the app picks up the `loadstart` event. I wasnt actually using this `ng-cordova-oauth` plugin but my own implementation. This seemed like the most active place to ask about the issue.

**Comment by m-vdv** [comment]
@domharrington Confirmed! Passing a redirect_uri that is a live site works.

@nraboy I had to overwrite the redirect_uri directly, setting it through options didn't work :/
Tried var options = { redirect_uri : 'http://mywebsite.com/callback' }; and then passing options as the last param.

**Comment by jeslomo** [comment]
Thanks @m-vdv  i've solved setting anything in redirect_uri.

$cordovaOauth.twitter("XXX", "XXX", {redirect_uri: 'http://YYY.ZZZ'})

**Comment by m-vdv** [comment]
Guys quick note, 

If you're using a live site callback url such as:
_http://mywebsite.com/callback_ 
Your server might automatically redirect that url to the version with a slash at the end: _http://mywebsite.com/callback/_

This fires the loadstart event twice causing ng-cordova-oauth to request the OAuth token twice.
The second token call will throw an error, causing issues!

So the solution is, use callback url:
_http://mywebsite.com/callback/_
