### ISSUE TITLE
Enable option to open in system browser

### ISSUE THREAD

**Issue by magnusburton** [nraboy/ng-cordova-oauth#194]
Hello!
I suggest adding an option to let the developer choose whether or not to open in the inappbrowser or in the system browser (iOS: Safari etc).

http://docs.phonegap.com/en/2.9.0/cordova_inappbrowser_inappbrowser.md.html#window.open
```html
target="_system"
```

I think that'd help many people. Thank you!

**Comment by nraboy** [comment]
System browser has limitations that won't work correctly with this library.
