### ISSUE TITLE
isInAppBrowserInstalled() returns false in cordova 6.0.0

### ISSUE THREAD

**Issue by Slessi** [nraboy/ng-cordova-oauth#200]
Since updating to Cordova 6.0.0, isInAppBrowserInstalled always returns `false`.
Tested on Android with cordova-android@5.1.0.

```javascript
cordovaPluginList.map(
    function(plugin) {
        return plugin.pluginId;
    });
```

`plugin` no longer has a `pluginId` property, but instead an `id` property. Which makes the `inAppBrowserNames` variable used here, an array of `undefined`. [Evidence](http://puu.sh/mRSpp/95db5ed83d.png)

```javascript
return inAppBrowserNames.some(function(name) {
    return formatedPluginList.indexOf(name) != -1 ? true : false;
});
```

So it returns `false`. [Evidence](http://puu.sh/mRS45/c3edc6173b.png)

Maybe do something like this?
```javascript
return plugin.id || plugin.pluginId;
```

Edit: Made a pull request for it #202

**Comment by nraboy** [comment]
https://github.com/nraboy/ng-cordova-oauth/pull/202 has been merged
