### ISSUE TITLE
Immediate use of ng-cordova-oauth results in unresponsive app.

### ISSUE THREAD

**Issue by ryanggrey** [nraboy/ng-cordova-oauth#204]
I discovered while trying to use ng-cordova-oauth that using the `google` function at the end of a controller results in the app no longer responding to gesture events. I haven't tested any other functions (such as `facebook`).

This issue only occurs if the function is called immediately as part of the apps initial launch. If the function is called later (triggered by the user later in the app's lifecycle) then all is well.

I've added an example project here with as much detail as I could add - https://github.com/ryanggrey/cordova-oauth-issue

**Comment by nraboy** [comment]
I won't be able to look at this for two weeks since I'm going to be on tour.  Maybe @matheusrocha89 can have a look if he has time?

I don't feel like these would be related.  Does the app freeze if you just try to launch the InAppBrowser in your controller?  That is essentially all the plugin is doing.

**Comment by matheusrocha89** [comment]
I think tomorrow I investigate that

Em seg, 8 de fev de 2016 22:19, Nic Raboy <notifications@github.com>
escreveu:

**Comment by ryanggrey** [comment]
> Does the app freeze if you just try to launch the InAppBrowser in your controller? That is essentially all the plugin is doing.

I haven't tried presenting and dismissing the in-app-browser directly (rather than via the ng-cordova-oauth plugin). I'll give this a go today if time permits and report back.

**Comment by ryanggrey** [comment]
I've stripped ng-cordova-oauth out of the demo app and instead use the InAppBrowser directly. The same issue occurs, which must mean the problem is in cordova-plugin-inappbrowser (or I'm using it incorrectly). I've updated my sample project to reflect my findings.

I'll continue to report my findings here as I'm guessing you'll want to know what the problem is as it appears to affect your plugin. If that's not the case then please let me know and I'll stop posting here.

**Comment by ryanggrey** [comment]
My demo app's repo has been renamed - https://github.com/ryanggrey/cordova-plugin-inappbrowser-issue

**Comment by matheusrocha89** [comment]
@ryanggrey Maybe the problem is with your code, you don't need to use the `$ionicPlatform.ready` on your controller. The controller will run only after the `$ionicPlatform.ready` on the `app.js`. Try to remove that and test again to see if it works.

**Comment by ryanggrey** [comment]
@matheusrocha89 Thanks for the suggestion! I gave that a go, but it unfortunately doesn't fix the issue.
