### ISSUE TITLE
It's killing me: webView:didFailLoadWithError - -1004: Could not connect to the server.

### ISSUE THREAD

**Issue by vgnrgithub** [nraboy/ng-cordova-oauth#206]
Hi,

I developing an app with Ionic and one of the functions is to sign in using Instagram. I followed exactly all your indications and It's giving me this error every time: webView:didFailLoadWithError - -1004: Could not connect to the server.

- I have these lines in my config.xml: 
      <allow-navigation href="*"/>
      <allow-intent href="http://*/*" />
      <allow-intent href="https://*/*" />
      <access origin="*"/>

Here's my code:

$scope.signininstagram = function(){
		$cordovaOauth.instagram("MyClientID", ["basic","public_content"]).then(function(result) {
        }, function(error) {
            // error
            console.log("ko");
            console.log(error);
        });
	}

What am I doing wrong?

Thank you

**Comment by vgnrgithub** [comment]
Sorry, I forgot to indicate these lines of config.xml:
allow-navigation href="*"
allow-intent href="http://*/*" 
allow-intent href="https://*/*"
access origin="*"

**Comment by nraboy** [comment]
For iOS, did you set up an ATS policy?  iOS 9 requires an ATS policy to access URLs that are not HTTPS with a valid certificate.

**Comment by nraboy** [comment]
Did an ATS policy correct your issue?

**Comment by vgnrgithub** [comment]
Hey Nic,
I already set up an ATS policy. Now the project is working. After hours trying I realize that I was not building for ios specifically (ionic build ios). After running It seem It works fine now.
Thank you for helping. By the way, do you know what are the best practices to optimize memory usage on ionic projects?

**Comment by nraboy** [comment]
I'm glad you got it working!

In regards to optimizations, that is best asked in the forums, not here :-P
