### ISSUE TITLE
Twitter - no response from service

### ISSUE THREAD

**Issue by jmav** [nraboy/ng-cordova-oauth#208]
When using 

`$cordovaOauth.twitter(string consumerKey, string consumerSecretKey, object options);`

there was no response from success or error callback. Problem was in version of jsSHA library.

As already written in docs: **jsSHA 1.6.0 Secure Hash Library (Twitter, Withings, and Magento only)** this is ok, but it isn't so noticeable as it should. I have read multiple issues & I noticed that users had similar problems.

Please make this notice about jsSHA version more noticeable in README.md. Maybe you could make version check of jsSHA lib, or better make dependency.

Thx for great work, Jure

**Comment by nraboy** [comment]
It is at the top of the README:

https://github.com/nraboy/ng-cordova-oauth#requirements

I'm not sure how I can be more clear in that.  I mean it is in the clearly labeled requirements section.  If people don't read the requirements, I'm thinking that is their problem.

Best,

**Comment by jmav** [comment]
Totally agree,

but making user/friendly documents, makes your library more popular.
I was solving this problem for 2 hours, already gave up.

Take this as goodwill to help you improve the lib.

**Comment by nraboy** [comment]
I'll make note of it.  The goal is to get the latest version working, but haven't had the time.

Happy to accept contributions to the project as well if you want to lend a hand.

Best,
