### ISSUE TITLE
log out from facebook

### ISSUE THREAD

**Issue by DhyanandraSingh** [nraboy/ng-cordova-oauth#215]
I am creating app for which i used cordova. 
I used ng-cordova-oauth  for login with facebook.
but I need a facility of log out from app how could i do that using ng-cordova-oauth.

**Comment by nraboy** [comment]
Forgetting the tokens not good enough?

**Comment by DhyanandraSingh** [comment]
I want to provide logout facility to my customers. If they want to log out I think i should make a logout option in my app.
One more question I think token has a limited lifetime what if a token expires.

**Comment by nraboy** [comment]
Well if you delete your tokens from your apps local storage, then you are logged out.  If you want to do anything further you'll have to read the official docs for the provider you're using.  This library will only do Oauth, everything else is up to you.
