### ISSUE TITLE
when I was trying to login to google Oauth I am getting console errors as

### ISSUE THREAD

**Issue by anveshnara** [nraboy/ng-cordova-oauth#216]
hi Nraboy,
Console Error as.
Error: [$injector:unpr] Unknown provider: $cordovaOauthProvider <- $cordovaOauth <- LoginPageController 
 Thanks,
Anvesh

**Comment by nraboy** [comment]
That means you didn't include the library correctly or you have a typo.

**Comment by anveshnara** [comment]
hi nraboy,
what is the use of optional parameter ??
Thanks,
Anvesh

**Comment by nraboy** [comment]
```
{
    redirect_uri: "url"
}
````

If you want to use a different callback than the localhost default.

**Comment by Saqib92** [comment]
i am having same error. and i have included libraries correctly.

**Comment by mosinski** [comment]
@Saqib92 https://blog.ionic.io/oauth-ionic-ngcordova/

> There are some things to note about OAuth with ngCordova:

> It will **only work** on your device or simulator. 
   It will **not work** in the web browser.
   All redirect / callback URIs must point to http://localhost/callback; otherwise, the login flow will not complete.
