### ISSUE TITLE
Facebook Error

### ISSUE THREAD

**Issue by celomamp** [nraboy/ng-cordova-oauth#218]
Hi!

I'm trying do implement the facebook Oauth but when I test it, I get a facebook error screen, like that:

![captura de tela de 2016-02-25 20 21 08](https://cloud.githubusercontent.com/assets/5561771/13337975/695cff1a-dbfd-11e5-920a-9be1e72039f3.png)

I already tried logout of my device's facebook app and from mobile chrome and still get the same error.

Any idea what this error could be?

**Comment by celomamp** [comment]
PS: The message says:

You still not entered. You're not connected to Facebook. Enter and try again.

**Comment by nraboy** [comment]
Looks like you do not have your oauth_redirect url correctly configured in the Facebook dashboard or your app has not been set to public in the dashboard.

**Comment by benhur10cp** [comment]
celomamp, você conseguiu resolver esse seu problema? estou com o mesmo. obrigado.
