### ISSUE TITLE
LinkedIn cancel android problem

### ISSUE THREAD

**Issue by adinu** [nraboy/ng-cordova-oauth#219]
I am developing an ionic app. On successful authentication of Linkeidn (using cordovaOauth), I am getting a glimpse of web page not available for all android devices.

Also if the user clicks on "Cancel", the user is directed to permanent "web page not available" page.
![m539m](https://cloud.githubusercontent.com/assets/7447585/13422500/e429c8ce-df9d-11e5-9fc4-56a27e3dcff9.png)

**Comment by nraboy** [comment]
Providers that do not offer implicit grant types suffer from a race condition.  This can be bypassed by hosting your own callback page and overriding the default local callback by passing in an optional redirect_uri.

Best,

**Comment by adinu** [comment]
hi,

thanks for your quick help. however, i am not sure what to do.
i have tried hosting my own callback page - however it is on localhost:8081/callback and not in localhost/callback. can you please advice what to do?

and how should i bypass the optional redirect_uri?

**Comment by nraboy** [comment]
```
$cordovaOauth.linkedin("CLIENT_ID", "SECRET_KEY", [], "", {redirect_uri: "http://yourwebsitehere.com/callback"});
```

Localhost will always show that message.  It needs to be a real hosted webpage if you want to get beyond this.

Best,
