### ISSUE TITLE
cannot authenticate vi a web browser

### ISSUE THREAD

**Issue by mmarcantoni** [nraboy/ng-cordova-oauth#221]
Hi,
i use telerik platform with:
-cordova 5,
-inApp browser plugin v1.1.1
-Whitelist plugin v1.2
-crosswalk
-Angular 1.4.8
When i test login in my app (debug mode), i had "cannot authenticate vi a web browser".
I test Facebook.
Thanks for help

**Comment by nraboy** [comment]
I'm not familiar with Telerik Platform, but if you're getting an error talking about the web browser, it means you're trying to serve the application rather than install it.

Regardless of the framework, you need to compile and install this application.  Live sync and serving will not work.

Best,
