### ISSUE TITLE
LinkedIn error when opening InAppBrowser

### ISSUE THREAD

**Issue by DBZFYAM** [nraboy/ng-cordova-oauth#222]
Hi,

I've been struggling for a while to find a solution for this so I'll try to ask here. I 'inherited' a project which uses LinkedIn to log into the application with the code below:
    // $cordovaOauth.linkedin(string clientId, string clientSecret, array appScope, string state);

```
$cordovaOauth.linkedin(clientId, clientSecret, ["r_fullprofile"], 'DCEeFWf45A53sdsdfKef424').then(function(result) {
      // Get extra details
}, function(error) {
      ionicToast.hide();
      console.log('app.js 2 error');
      console.log(error);
});
```

When clicking on a button, it opens a InAppBrowser but the window stays empty and does nothing. In the Xcode console I see the following:

```
2016-03-08 15:18:07.790 MM Coach[648:280620] Setting the WebView's frame to {{0, 0}, {375, 623}}
2016-03-08 15:18:07.796 MM Coach[648:280620] THREAD WARNING: ['InAppBrowser'] took '26.397949' ms. Plugin should use a background thread.
2016-03-08 15:18:08.533 MM Coach[648:280620] webView:didFailLoadWithError - -1004: Could not connect to the server.
2016-03-08 15:18:08.535 MM Coach[648:280620] Error in Success callbackId: InAppBrowser970752184 : TypeError: undefined is not an object (evaluating '(event.url).split("code=")[1].split')
```

Does anyone have any idea how to fix this? The LinkedIn functionality used to work in a previous release. Also tried readding the inappbrowser plugin without luck. It seems to get stuck at the the requestToken of the plugincode below:

```
var browserRef = window.cordova.InAppBrowser.open('https://www.linkedin.com/uas/oauth2/authorization?client_id=' + clientId + '&redirect_uri=' + redirect_uri + '&scope=' + appScope.join(" ") + '&response_type=code&state=' + state, '_blank', 'location=no,clearsessioncache=yes,clearcache=yes');
        browserRef.addEventListener('loadstart', function(event) {
          if((event.url).indexOf(redirect_uri) === 0) {
            requestToken = (event.url).split("code=")[1].split("&")[0];
```

I'm building the app with ionic build ios and running it through Xcode. Also doesn't seem SSL related as I found in another post (ATS). Testing on iPhone with iOS 9.2.1

Thanks in advance!
Greetings,
Stefan

**Comment by nraboy** [comment]
You might try updating the following:

* The Apache Cordova Platform (not CLI)
* Ionic Framework (not CLI)
* The InAppBrowser Plugin
* The ng-cordova-oauth library

My guess is something is dated and needs to be updated.

**Comment by DBZFYAM** [comment]
Thank you very much for the reply!

Strange.. I've updated the Cordova platform and Ionic Framework with the commands below (found these in the documentation. I assume this is the way?). Also removed the InAppBrowser and oauth library and readded the newest ones but still have the same problem. On my Iphone I get an empty screen and in the simulator I get "The requested URL /callback was not found on this server", while it it correctly set in the configuration. Also same error in the console as above

```
cordova platform update android
cordova platform update ios
ionic lib update
```

**Comment by nraboy** [comment]
Just to confirm, you're not using Ionic Serve, Ionic View, Live Reload or similar, correct?  You also have the correct oauth callback in the correct location in the LinkedIn dashboard, correct?

I cannot reproduce this so my guess is that it is a configuration issue or how you're running it.

**Comment by DBZFYAM** [comment]
No I'm just using ionic build ios and manually running by opening the project in Xcode and run either in simulator or on real iphone. Also have the callback set to http://localhost/callback in LinkedIn indeed. I'll see if I can set up a new project and copy all views/code over. Maybe it works then when I re-add the plugins. 

Strange thing is it that the version currently available on the app store is functioning fine and since I received the code it hasn't worked. Think something might not be compatible then indeed

**Comment by nraboy** [comment]
Beyond updates to accommodate the latest Apache Cordova and InAppBrowser editions, nothing has changed in the library as far as provider logic.

**Comment by DBZFYAM** [comment]
I've found the problem with the code. I was using the permissions ["r_fullprofile"] which is no longer accepted by LinkedIn (probably to protect people's privacy). After changing this to ["r_basicprofile", "r_emailaddress"], I still got all data I needed and the login screen worked. I do see a short white screen (/callback) after logging in, but it proceeds with the welcome process within 1 or 2 seconds. Thanks for the help Nic!

**Comment by nraboy** [comment]
Providers that use explicit grant types like LinkedIn will always show a short delay of a page not found.  It is due to a race condition.  The only way to get around this is if you override the callback in the library to a page that truly exists on the internet.

I wouldn't let it bother you.  I've heard no reports of complaints.

Best,
