### ISSUE TITLE
No Yahoo support

### ISSUE THREAD

**Issue by rashnk** [nraboy/ng-cordova-oauth#223]
does it support yahoo?

**Comment by nraboy** [comment]
Does Yahoo have an Oauth API?

**Comment by rashnk** [comment]
https://developer.yahoo.com/oauth/

**Comment by nraboy** [comment]
Adding this for reference:

https://developer.yahoo.com/oauth2/guide/flows_implicitgrant/

When time permits it will be added.

**Comment by ant0ha** [comment]
Created PR for this https://github.com/nraboy/ng-cordova-oauth/pull/257

**Comment by ant0ha** [comment]
PR updated

**Comment by nraboy** [comment]
This has been merged to development.  It will make its way into the master branch with a version soon.
