### ISSUE TITLE
Does not trigger the facebook API on Android with the most recent version of ngCordova and phonegap cli-6.0.0.

### ISSUE THREAD

**Issue by hindsricardo** [nraboy/ng-cordova-oauth#227]
So i upgraded my ngCordova package to the most recent version.  As a result  my reference to cordovaOauth in my controller was broken as though it did not exist. So I added ng-cordova-auth separately outside of ngCordova and referenced it in my module.. see below.

**angular.module('app', ['ionic', 'app.controllers', 'app.services', 'ngCordova','ngCordovaOauth'])**

Here is my bower lib files:
![image](https://cloud.githubusercontent.com/assets/4805670/13849980/3808ca8c-ec26-11e5-8d84-76d9d7dc0ee2.png)

I can now go through the full facebook auth on my IOS emulator, but the facebook API is not triggered for Android. 

Not sure if it helps but i'm using phonegap cli-6.0.0

**Comment by nraboy** [comment]
What do your logs say?

**Comment by hindsricardo** [comment]
So I reinstalled ng-cordova-oauth and now i'm getting a response. I'm getting an error message that inappbrowser could not be found. I think i can solve this one though.
