### ISSUE TITLE
Invalid redirect_ur. This value must match a URL regisitered with the API Key

### ISSUE THREAD

**Issue by nguyennguyen101088** [nraboy/ng-cordova-oauth#229]
I integrate login with linkedin using ng-cordova-oauth, but I got error that: Invalid redirect_ur. This value must match a URL regisitered with the API Key.
I tired fix it but I can't
Please help me resolve this.
Thanks

**Comment by matheusrocha89** [comment]
By default the lib use as redirect_uri `http://localhost/callback` you can register this url as your redirect url on linkedin app config or you can pass this propery as a parameter to use the one you already register there, the lib allows you that.

**Comment by nguyennguyen101088** [comment]
Hi matheusrocha89 and nraboy
I tried config Authorized Redirect URLs: http://localhost/callback (I used http://localhost:8088/signin-linkedin before) but I can run my app. Could you please help me resolve this.

**Comment by nraboy** [comment]
I don't think providers will let you specify a port.  If you added **http://localhost/callback** to LinkedIn as the callback and it's not working, I think you have other problems in your LinkedIn dashboard.

Regards,

**Comment by nguyennguyen101088** [comment]
@nraboy, thanks for your support, I fixed that issue. But I got an issue different is after authentication account with Linkedin sucessful then my app display a blank page before continue run my app.
Could you please help me resolve that.
Thanks and Regards

**Comment by nraboy** [comment]
Not really sure what you're talking about.  Pictures and logs please.
