### ISSUE TITLE
not get facebook account info when login

### ISSUE THREAD

**Issue by nvcken** [nraboy/ng-cordova-oauth#23]
My implement is ionic , ngCordova to build android app
I use ngCordovaOauth to do facebook login
But when press login button I call
$scope.facebookLogin = function() {
        $cordovaOauth.facebook("CLIENT_ID_HERE", [""]).then(function(result) {
            // results
        }, function(error) {
            // error
        });
    }

Then it open window facebook  login require type Email/ password to login, why it dont get facebook logined account on my android phone device and then just ask accept only ...?

**Comment by nraboy** [comment]
$cordovaOauth is web based sign in.  It does not interact with the native application so there is no relationship to any existing account on the device.

**Comment by nvcken** [comment]
oh now I see, so please help me for any plugin to do login with exist account on device ?

**Comment by nraboy** [comment]
The InAppBrowser is just a web browser.  If you want to access account information from the native app, you'll need a different plugin and library as mine will not accomplish this.
