### ISSUE TITLE
Conflict with Google Maps API

### ISSUE THREAD

**Issue by tombrokeoff** [nraboy/ng-cordova-oauth#234]
Maybe I just dont know how to properly do this, but I am attempting to use the oauth in an app that also uses the Google Maps API.  I immediately run into issues because I include Google first then the oauth JS and when I attempt to use google.maps.LatLng(), it throws an error "Cannot read property 'LatLng' of undefined."  In order to get around this, I renamed google within ng-cordova-oauth.min.js, since I am not using it anyhow, just the facebook oauth, but I thought it might be an issue.

**Comment by nraboy** [comment]
Hey @tombrokeoff can you try the staging branch of this repository?  There is a fix in place, but I haven't had enough people test it yet to merge it into the master branch.

cc @matheusrocha89

**Comment by tombrokeoff** [comment]
Sure thing.  I'll reply back in a bit.

**Comment by tombrokeoff** [comment]
Seems to work for me :)

**Comment by nraboy** [comment]
Perfect! I just tagged the master at 0.2.5.  Should have the fixes you need now :-)

**Comment by tombrokeoff** [comment]
Awesome.  Glad I could contribute a tiny, tiny bit.

**Comment by nraboy** [comment]
Every little bit helps.  Feel free to pick up one of the issue tickets if you're feeling daring one day.
