### ISSUE TITLE
Build core framework for Ionic + AngularJS

### ISSUE THREAD

**Issue by nguyennguyen101088** [nraboy/ng-cordova-oauth#236]
Hi @nraboy,

I want to build a core framework for Ionic + AngularJS, so that every time a new project with ionic + AngularJS I brought out of use. So we will not spend time to initialize the project. Could you please tell me the main components I have to have in my core framework and What should I do? 

Thanks

**Comment by nraboy** [comment]
How is this related to ng-cordova-oauth?

**Comment by nguyennguyen101088** [comment]
@nraboy, I'm sorry about that, I think I posted the wrong place.
