### ISSUE TITLE
'The sign in flow was canceled' issue

### ISSUE THREAD

**Issue by thomasMary** [nraboy/ng-cordova-oauth#24]
Hi,

I'm trying to login with Twitter, i've followed the procedure:
-cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git
-set  http://localhost/callback as the callback / redirect uri
- add sha1.js
Here is my problem, when I login on twitter, I received the following error: "The sign in flow was canceled". So I jump into your code, and I found this lines:
browserRef.addEventListener('exit', function(event) {
      deferred.reject("The sign in flow was canceled");
});
So I tried to comment it, and the authentification succeeded. Is it possible the exit event could be send before then end of the authentification process ? Or Am I simply doing something wrong ?
Thanks

**Comment by nraboy** [comment]
What version of the library are you using?  Are you using the ng-cordova-oauth, or ng-cordova version?

This issue should be corrected in the ng-cordova-oauth version, but I've not yet pushed the changes to ng-cordova managed by Driftyco.

Please let me know and we'll start there.

Thanks,

**Comment by nraboy** [comment]
Make sure the version you're using has the .finally block as seen here:

https://github.com/nraboy/ng-cordova-oauth/blob/master/ng-cordova-oauth.js#L551-L555

**Comment by thomasMary** [comment]
Indeed, i'm using the ng-cordova version.

**Comment by nraboy** [comment]
Sorry about that.  Since this is just a hobby project, I can fall behind on keeping things in sync.

I'll report back to this ticket when the Driftyco library has been updated.

**Comment by nraboy** [comment]
Created the following pull request:

https://github.com/driftyco/ng-cordova/pull/566

Once Driftyco accepts, your problems should be resolved.

**Comment by thomasMary** [comment]
Thanks a lot ! :)

**Comment by Kaushick** [comment]
I got an error "Validation failed: Not a valid URL format" when added  "http://localhost/callback" as redirect uri in twitter app. Can you please tell me the solution?

**Comment by nraboy** [comment]
Twitter is the only exception where it doesn't need to be `http://localhost/callback` because they allow you to override it via the API call.  I recommend you put something like `http://example.com/callback` in the Twitter dashboard.  $cordovaOauth will take care of the rest.

**Comment by Kaushick** [comment]
Thanks a lot. Can you help me once again? When I'm using $cordovaOauth.twitter("consumerKey", "consumerSecretKey"); in response I'm getting access_token, access_token_secret, screen_name and user_id. Now when I'm calling twitter's "users/show.json" api with screen_name and user_id it is throwing an error "Bad Authentication data". Now my question is how can I authenticate my api call?

**Comment by nraboy** [comment]
Hi @kaushick,

This library was only intended to get you as far as the Oauth credentials.  I'm going to have to direct you to the Twitter RESTful API documentation if you need help using it:

https://dev.twitter.com/rest/public

My assumption is you're either forgetting to include the Authorization header in your API requests, or your signature is incorrect in the header.

https://blog.nraboy.com/2014/11/understanding-request-signing-oauth-1-0a-providers/

Also for future reference, please open new GitHub issue tickets.  You are commenting on a closed issue that is not related to what you're asking.

Regards,

**Comment by Kaushick** [comment]
Sorry for commenting here. But I've a last question. For 'users/show.json' call I need to generate the Authentication header and attach it?

**Comment by WangYinXing** [comment]
Hi.
I am getting this message after i logged in Linkedin.
The sign in flow was canceled

Here is my code.

$cordovaOauth.linkedin("---", "---", [
        "r_basicprofile",
        "rw_company_admin",
       // "r_fullprofile",
        //"r_contactinfo",
        //"r_network",
        "r_emailaddress"],
        "DCEeFWf45A53sdfKef424").then(function(result) {
            alert(JSON.stringify(result));
        }, function(error) {
            alert(JSON.stringify(error));
        });

Please help me kindly.

**Comment by longedok** [comment]
@WangYinXing Hello, I had the same issue with linkedin sign in, turned out I had a wrong permission in my 'scope' array ("r_fullprofile"). I can recommend you to debug the code of the cordovaOauth plugin to see what error linkedin returns in the redirect url.

**Comment by gbrennon** [comment]
I'm having the same issue with facebook login :(
