### ISSUE TITLE
Why window/inappbrowser don't close after login?

### ISSUE THREAD

**Issue by Malkafly** [nraboy/ng-cordova-oauth#243]
i`m stuck on this screen: http://s32.postimg.org/822fvo5np/Simulator_Screen_Shot_May_3_2016_10_31_59_AM.png

O click on authorize, make a loading spin (strava side) and nothing come. The window don`t close or any other callback.

my code is rly simple:
`$cordovaOauth.strava('11XXX', 'XXXXXXXXXXXXXXXa4c78b87345fe0890bd1',['public']).then(function(result) {`

did i miss something?

AHhh btw, great work nraboy :D

**Comment by nraboy** [comment]
What do your logs say?

**Comment by nraboy** [comment]
> 2016-05-03 14:32:24.094 hiBike[8447:387132] webView:didFailLoadWithError - -1004: Could not connect to the server.

Did you do the appropriate whitelisting and ATS fixes for iOS 9?  Apple is very strict when it comes to security.

**Comment by Malkafly** [comment]
i don't think so... i install whitelist plugin only, i will search for this "ATS fixes" right now

**Comment by nraboy** [comment]
This could help:

https://www.thepolyglotdeveloper.com/2015/10/fix-ios-9-app-transport-security-issues-in-apache-cordova/

**Comment by jbeullen** [comment]
Have found the bug and a potential fix.
@nraboy 
Take a look at this:
https://github.com/nraboy/ng-cordova-oauth/blob/master/src/oauth.strava.js#L32

I think this should be
`var requestToken = (event.url).split("code=")[1];`

When I change this in the ng-cordova-oauth/dist/ng-cordova-oauth.js, it seems to work fine.

**Comment by nraboy** [comment]
Seems weird to me that it would resolve by adding a `var` in there.

I will see about getting this into the project this week.  I really don't think that would make a difference though.

Best,

**Comment by jbeullen** [comment]
Here is an extract of my log:
> May 10 12:14:52 xxx myapp[33777]: webView:didFailLoadWithError - -1004: Could not connect to the server.
> May 10 12:14:52 xxx myapp[33777]: Error in Success callbackId: InAppBrowser888559593 : ReferenceError: Can't find variable: requestToken

By adding the `var` the I could get it to work. 

If you look other providers, the `var` is there.
https://github.com/nraboy/ng-cordova-oauth/blob/master/src/oauth.adfs.js#L26

My 2 cents

**Comment by nraboy** [comment]
Ah!  I didn't realize you were actually getting this error:

```
ReferenceError: Can't find variable: requestToken
```

Not used to platforms complaining like that.  Looks like this is definitely worth fixing for all the providers that are part of this library.

Thanks,

**Comment by Malkafly** [comment]
strange indeed, but putting 'var' did the trick

**Comment by nraboy** [comment]
This should be corrected in commit https://github.com/nraboy/ng-cordova-oauth/commit/cf495b1ec93c951002041f079e94ed44cc519c3f also known as version 0.2.7
