### ISSUE TITLE
Error when trying to contribute

### ISSUE THREAD

**Issue by bbuie** [nraboy/ng-cordova-oauth#244]
I'm trying to add a module for Netatmo and I get the following error when trying to run `grunt test` or when trying to compile js.

Any ideas? What version of node do I need?

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/benbuie/.nvm/versions/node/v4.4.3/bin/node" "/Users/benbuie/.nvm/versions/node/v4.4.3/bin/npm" "run" "test"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ng-cordova-oauth@0.2.5 test: `grunt test`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng-cordova-oauth@0.2.5 test script 'grunt test'.
npm ERR! This is most likely a problem with the ng-cordova-oauth package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng-cordova-oauth
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ng-cordova-oauth
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/skinsaver/www/lib/ng-cordova-oauth/npm-debug.log

**Comment by bbuie** [comment]
Nevermind. I had to install grunt-cli. I'm pretty sure the required version of node is 0.10 but can someone confirm?

**Comment by nraboy** [comment]
Grunt should work with newer versions of Node.
