### ISSUE TITLE
Possible Issue with Strava

### ISSUE THREAD

**Issue by nraboy** [nraboy/ng-cordova-oauth#246]
Per a blog comment by Francisco found here:

https://www.thepolyglotdeveloper.com/2014/07/using-oauth-2-0-service-ionicframework/#comment-2666724136

Strava may not be functioning correctly.  Strava support was added in commit https://github.com/nraboy/ng-cordova-oauth/commit/7587faaf9a74d4018c6c0bfe25427bf91fd8afb2 and can be further read about via the original request ticket https://github.com/nraboy/ng-cordova-oauth/issues/9.

Pending Strava tokens for testing.

**Comment by faldunate** [comment]
thank you Nic, I could solve the problem, I change the Content Security Policy

old meta
``` <meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"> ````
new meta
``` <meta http-equiv="Content-Security-Policy" content="default-src *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; style-src  'self' 'unsafe-inline' *"> ```
