### ISSUE TITLE
Twitter error code 135

### ISSUE THREAD

**Issue by agomezmoron** [nraboy/ng-cordova-oauth#248]
Sometimes when you try to connect to Twitter you get the following error:

code: 135
Message: TimeStamp Out of Bounds

Seeing a twitter thread: https://twittercommunity.com/t/timestamp-out-of-bounds/287 it can be related to the epoch conversion.

**Comment by nraboy** [comment]
I feel like this is out of the libraries control.  If the users device has an incorrect time it is on them.

Any input on this?

**Comment by nraboy** [comment]
Adding @matheusrocha89 for his 2 cents

**Comment by matheusrocha89** [comment]
@agomezmoron I tested here and it was working on Genymotion and on my Android. Did you check if the time on your device or emulator is correct?

**Comment by nraboy** [comment]
I think he means it only happens sometimes for people which leads me to believe the devices that experience failure, have the incorrect date/time set in their device.  I could be wrong.

**Comment by matheusrocha89** [comment]
If it's this I believe the problem it's the time... I will try later with wrong time to see if I can simulate the same error message

**Comment by agomezmoron** [comment]
Hi,

@matheusrocha89 as @nraboy said, it happens only sometimes. The emulator has the date/time set correctly using the Windows Host one. That error occurred 2 times in more than 500 logins. I think it is a corner case - emulator/device is overloaded maybe and it's working slow.

Thanks!
