### ISSUE TITLE
How i get the information from already open facebook app from smartphone.

### ISSUE THREAD

**Issue by jackmasi** [nraboy/ng-cordova-oauth#252]
@nraboy In my mobile i have a facebook application already login. When i use ng-cordova-oauth its again asking the credentials with new page. Its not picking the already opened application. So please suggest any idea to resolve this type situation. The requirement is if facebook app already logged in the phone it directly pick from there. otherwise it needs to opent the facebook sign in page. Its samething for Google+ and linkedin also.

**Comment by nraboy** [comment]
ng-cordova-oauth works independent from other plugins and applications.  It is completely sandboxed.

If you want to use the auth based on your native apps, you'll have to find a different plugin.

Best,
