### ISSUE TITLE
Can be decoupled from Angular

### ISSUE THREAD

**Issue by slorber** [nraboy/ng-cordova-oauth#255]
Hi,

I'm not using Angular but I'm interested by the code in this repo.

I don't have time to wait for this to be done but as a suggestion, I would have liked to use the code in this repo. I can't because it's tightly coupled to Angular while it seems to me most OAuth/InAppBrowser login stuff doesn't really have to be.

I think in the future it could be great to extract some stuff into another project that could be used by non-angular users as well.

**Comment by nraboy** [comment]
Cool thought, but I have no plans to make this library for anything beyond Angular.  It is open source, feel free to use it as you wish.
