### ISSUE TITLE
facebook graph api 2.0 ending

### ISSUE THREAD

**Issue by tbro028** [nraboy/ng-cordova-oauth#260]
Need to upgrade the api as this one is ending in August 2016

**Comment by nraboy** [comment]
Please provide a link where you see that v2 is being deprecated.

**Comment by tbro028** [comment]
https://developers.facebook.com/docs/apps/changelog

Initially I received an email saying:

Clique has been making recent API calls to Graph API v2.0, which will reach
the end of the 2-year deprecation window on Monday, August 8, 2016. Please
migrate all calls to v2.1 or higher in order to avoid potential broken
experiences.

**Comment by nraboy** [comment]
Bumped to v2.6 in commit https://github.com/nraboy/ng-cordova-oauth/commit/44ba5587cb3598b119204d3cf29872dc47ecf9cb

Thanks for bringing this up :-)
