### ISSUE TITLE
$cordovaOauth.twitter doesn't work : it seems to be undefined

### ISSUE THREAD

**Issue by NicsTr** [nraboy/ng-cordova-oauth#262]
Hi,

I tried (and succeed) using this ngCordova plugin with Google Plus.

But with the twitter method nothing happened as if it didn't exist.

There is my minimal code which doesn't as described by the doc (The alert "Ready" is shown, but not the alert "After cordovaOauth.twitter") :

 `$ionicPlatform.ready(function() {`
 					`alert("Ready");`
 					`$cordovaOauth.twitter("<myConsumerKey>", "<myConsumerSecret>");`
 					`alert("After cordovaOauth.twitter");`
 				`});`

Thanks in advance for helping me through this.

**Comment by nraboy** [comment]
https://github.com/nraboy/ng-cordova-oauth#support
