### ISSUE TITLE
Twitter Redirection Issue

### ISSUE THREAD

**Issue by technotip** [nraboy/ng-cordova-oauth#264]
Twitter doesn't take http://localhost/callback as its callback URL.

I used http://127.0.0.1/callback but still it's not working. When it redirects, it shows error on my IONIC app.

**Comment by alexfradiani** [comment]
Same here. When I run the $cordovaOauth.twitter(... call all I get is a log in console that says "log". Completely blind about this, need some help.

**Comment by nraboy** [comment]
@technotip you cannot use 127.0.0.1, it must be localhost or you must override the url in an optional parameter.

I've tested Twitter recently and it works fine.  If you'd like support please refer to this:

https://github.com/nraboy/ng-cordova-oauth#support

**Comment by technotip** [comment]
@nraboy, I've even used localhost. In both cases the redirected page gets stuck for some seconds ..!
Please see the screenshot I've attached with this message.

![screenshot_20160701-152556 1](https://cloud.githubusercontent.com/assets/4805549/16518729/12f4b948-3fa2-11e6-8d2e-a419bb3b38bd.png)

**Comment by alexfradiani** [comment]
For the callback issue... I used a tinyurl instead, is working now.

**Comment by daraul** [comment]
I tried this with a tinyurl, and without (I'm also using firebase in the same app), and the error page shows up for a _second_, before returning the response and proceeding as normal. Not necessarily a problem, but some of my users might wonder what that is. 

My `$ bower list`:

├─┬ angular-animate#1.5.3 (latest is 1.5.9-build.4996+sha.e50e91c)
│ └── angular#1.5.3 (latest is 1.5.9-build.4996+sha.e50e91c)
├─┬ angular-sanitize#1.5.3 (latest is 1.5.9-build.4996+sha.e50e91c)
│ └── angular#1.5.3
├─┬ angular-ui-router#0.2.13 (latest is 1.0.0-beta.1)
│ └── angular#1.5.3 (1.5.9-build.4996+sha.e50e91c available)
├─┬ angularfire#2.0.1
│ ├── angular#1.5.3 (1.5.9-build.4996+sha.e50e91c available)
│ └── firebase#3.2.1 (3.3.0 available)
├── hello#1.13.4 extraneous
├── ionic not installed
├── jsSHA#1.6.0 (latest is 2.2.0)
├── ng-cordova-oauth#0.2.10
├─┬ ngCordova#0.1.27-alpha
│ └── angular#1.5.3 (1.5.9-build.4996+sha.e50e91c available)
└── platform.js#1.3.1


If I should include any other information, please let me know.

**Comment by mariomka** [comment]
Same problem here. "Webpage not available" is shown a few seconds before is closed and application continues.

**Comment by mariomka** [comment]
Ok, just use any online uri as "redirect_uri" option to avoid the message...

**Comment by daraul** [comment]
I added my firebase URL as the `redirect_uri` option and that worked. Now I don't have `localhost/callback` in either my twitter app or in my ionic app itself, though. The docs mentioned that that is essential. Will test further to see if there are any problems

**Comment by nikmahes** [comment]
I added my firebase URL as the redirect_uri but getting similar error page.

![whatsapp image 2017-01-18 at 9 40 31 pm](https://cloud.githubusercontent.com/assets/7761396/22072088/2e221314-ddc7-11e6-99e6-3c0d1afa8bc3.jpeg)

Anyone else faced similar issue ?
