### ISSUE TITLE
Issue Box Oauth After Login InApp browser remains for 2 sec .

### ISSUE THREAD

**Issue by anveshnara** [nraboy/ng-cordova-oauth#269]
When I was Trying logged in using Box Oauth after login InApp Browser stay for 2 sec loadstart event triggered then Browser close, InApp Browser remains 2 sec after login with localhost url and paramas as access_token.

**Comment by nraboy** [comment]
Any provider that uses explicit grants will have a delay unless you override the redirect URL to one that you host remotely.
