### ISSUE TITLE
Support for Yammer Oauth

### ISSUE THREAD

**Issue by thereallukesimpson** [nraboy/ng-cordova-oauth#27]
Please consider adding support for Yammer OAuth:

https://developer.yammer.com/v1.0/docs/authentication
https://developer.yammer.com/v1.0/docs/oauth-2

Might look something like:

$cordovaOauth.yammer(string loginUrl, string clientId);

where loginUrl = https://www.yammer.com/dialog/oauth?client_id=[:client_id]&redirect_uri=[:redirect_uri]
and redirect_uri = http://localhost/callback

**Comment by nraboy** [comment]
Thanks, I'll look into this

**Comment by nraboy** [comment]
@thereallukesimpson 

Can you please test this.  I've pushed Yammer support to the development branch of this project.

https://github.com/nraboy/ng-cordova-oauth/commit/50ee97643ec71b2ad19e18397466805cfe46a274

When you test it and confirm it works, I'll push it into the master.

Thanks,
