### ISSUE TITLE
Are there any plans for supporting Fitbit?

### ISSUE THREAD

**Issue by othmaan** [nraboy/ng-cordova-oauth#271]

**Comment by nraboy** [comment]
Do you have a link to their Oauth API documentation?

**Comment by othmaan** [comment]
dev.fitbit.com/docs/oauth2

I understand that this not an issue, but I couldn't add a tag "feature request".

**Comment by nraboy** [comment]
Duplicate ticket https://github.com/nraboy/ng-cordova-oauth/issues/323
