### ISSUE TITLE
not getting email after facebook success oauth.

### ISSUE THREAD

**Issue by devkamboj** [nraboy/ng-cordova-oauth#277]
$cordovaOauth.facebook("my_app_id", ["email,public_profile"]).then(function(result) {
            $localStorage.accessToken = result.access_token;
            console.log(result);
}

i using above code but not getting **email** in **result** only **access token** is coming.

**Comment by nraboy** [comment]
The point of oauth is to get tokens that you then use towards provider APIs to get more information.

Unless it says in the documentation that the email should be returned with the access token, it is working correctly.  Feel free to share the documentation if its there.

Best,

**Comment by devkamboj** [comment]
` $http.get("https://graph.facebook.com/v2.2/me", {params: {access_token: result.access_token, fields: "name,email", format: "json" }}).success(function (data, status, headers, config) {
        fbemail=data.email;
        console.log(data);
    }).error(function (data, status, headers, config) {
        alert("Error: " + error);
    });`

by this we can get email
