### ISSUE TITLE
Facebook invalid permission

### ISSUE THREAD

**Issue by TheNuclearCat** [nraboy/ng-cordova-oauth#279]
Hi,
I am trying to getting the user email but while logging in i´m getting the following error
![screenshot_20160821-234139](https://cloud.githubusercontent.com/assets/19869755/17839957/60205086-67f9-11e6-8f65-a47023d16e13.png)
:
Thats my code:
`$scope.fbLogin = function () {
   window.cordovaOauth.facebook("APPID", ["public_profile"], {redirect_uri: "http://localhost/callback"}).then(function(result){
        displayData(window.http, result.access_token);
    },  function(error){
            alert("Error: " + error);
    });
};`

(I have replaced the APP ID here.)
Any ideas why this is happening ?

**Comment by nraboy** [comment]
are you receiving an access token?

**Comment by TheNuclearCat** [comment]
No, the error function is called with the error instead of the function with the result, that should contain the access token.

**Comment by TheNuclearCat** [comment]
Any updates @nraboy  :D?

**Comment by nraboy** [comment]
Sounds like you didn't configure something correctly in your Facebook dashboard.

**Comment by TheNuclearCat** [comment]
I have played around a bit with the settings and still getting the same error :(
