### ISSUE TITLE
Google errors with "Cannot authenticate via a web browser"

### ISSUE THREAD

**Issue by mzarella** [nraboy/ng-cordova-oauth#28]
I was following along with the readme, and this is the snippet of code I'm using to auth with Google:

```js
  $cordovaOauth.google("RANDOM_NUMS_AND_LETTERS_HERE.apps.googleusercontent.com", ["mario.zarella@gmail.com"])
    .then(function(result) {
      debugger;
      console.log("Response Object -> " + JSON.stringify(result));
     }, function(error) {
      console.log("Error -> " + error);
    });
```

The above code always ends up erroring, and here's the output:
```
Error -> Cannot authenticate via a web browser
```

Any advice?

**Comment by nraboy** [comment]
Yes it means don't use a web browser.  I added that error message to make it obvious to everyone that this library only works on a device or simulator.

Should work fine when you use on a device or simulator.

**Comment by mzarella** [comment]
I will have to figure out how to debug apps on the phone then (no clue how yet), thanks for your work

**Comment by nraboy** [comment]
You might check out this post I made on the subject:

https://blog.nraboy.com/2014/12/debugging-android-source-code-adb/

I'm going to close this ticket since there is no problem, but feel free to comment on it if you run into trouble.  Or catch me on Twitter @nraboy

**Comment by nadeemkhan** [comment]
hi Nic i'm using device still getting this error "Cannot authenticate via a web browser" please have look log below thanks.

06-04 18:05:10.150    8879-8879/com.ionicframework.c826084 I/chromium﹕ [INFO:CONSOLE(62)] "Cannot authenticate via a web browser", source: file:///android_asset/www/js/controllers/controllers.js (62)

**Comment by nraboy** [comment]
Are you using ng-cordova or ng-cordova-oauth?

**Comment by nadeemkhan** [comment]
i'm using ng-cordova-oauth actually i'm new in ionic please help me out thanks

**Comment by nraboy** [comment]
Few questions:

1. Are you using Crosswalk in your application?
2. How are you adding the InAppBrowser plugin?
3. Are you using Ionic Serve, Ionic Live-Reload, or Ionic View?
4. Is this error happening on a device or simulator?

Regards,

**Comment by nadeemkhan** [comment]
1. Nope
2. i just added "cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git" via command in my project root directory
3. it's working on ionic server and did't checked yet on ionic view i'm using Android Studio on mac
4. this happening coming on my android device.

**Comment by nraboy** [comment]
Don't use Ionic Serve, Ionic View, or Ionic Live-Reload.  They are known to have compatibility problems with the InAppBrowser plugin as indicated in the README.

Regards,

**Comment by DreamYahia** [comment]
hello

make sure that you included the cordova.js on your index.html
if you use latest cordova please make sure that you replaced any line contains 
cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser")
to
cordovaMetadata.hasOwnProperty("cordova-plugin-inappbrowser")

**Comment by billy124** [comment]
Hi, I am getting this error my Android phone, 
- I have in app browser installed
- am using ionic run android to install the app on my phone, and not using ionic serve etc

**Comment by DreamYahia** [comment]
@billy124 if you have error 32 can not authenticate you  just make sure that you add encode for localhost/callback in the js file

or please copy you error here

**Comment by billy124** [comment]
@DreamYahia, Hi, am getting this error "Cannot authenticate via a web browser"

**Comment by YahiaAgwa** [comment]
@billy124 
ok try this link
https://github.com/nraboy/ng-cordova-oauth/issues/28#issuecomment-156944096

**Comment by billy124** [comment]
@DreamYahia 

I have the ng-cordova.js ref in my index.html 

<script src="lib/ngCordova/dist/ng-cordova.js"></script>

Also cant not find any instance of this code ' cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser")'

**Comment by YahiaAgwa** [comment]
https://github.com/nraboy/ng-cordova-oauth/blob/master/dist/ng-cordova-oauth.js
if(window.cordova) {
/* Code*/
                } else {
                    deferred.reject("Cannot authenticate via a web browser");
                }
in your index.html just make sure that you include the cordova.js script tag on the top of your page
<script src="cordova.js"></script>

**Comment by billy124** [comment]
Hmm had to change my sha version to 1.6.1 instead of 2.0.2 - http://stackoverflow.com/questions/30916991/chosen-sha-variant-is-not-supported

And its all seems to be working now, nice one for your support @DreamYahia 

The twitter auth worked fine now however for a split second I see an android 404 page, am guessing I need to set a callback to show a loading screen?

**Comment by YahiaAgwa** [comment]
@billy124 
sounds good 
congratulations

**Comment by nraboy** [comment]
Since this thread is active, can I get you guys to help test the staging branch?:

https://github.com/nraboy/ng-cordova-oauth/issues/167

Thanks,

**Comment by erikhu** [comment]
@nraboy 
i have the same problem in the divice , i know that problem is because runs in web server , but i try in device and show the same problem , you know why? thnks @nraboy

**Comment by nraboy** [comment]
That error is triggered when `window.cordova` is null or undefined which could mean a few things:

1. You didn't wrap your call in an `$ionicPlatform.ready` which means your app isn't ready to use the plugin
2. The plugin is corrupted and needs to be reinstalled
3. You are using Ionic Serve, Ionic View, or Ionic Live-Reload when you shouldn't be

Regards,

**Comment by erikhu** [comment]
@nraboy thnks for fast review , see this is the code 

$ionicPlatform.ready(function(){

      var myToken = JSON.parse(window.localStorage.getItem(Twitter.llave));
    
      if(myToken === '' || myToken === null){
         $cordovaOauth.twitter(Twitter.id , Twitter.secret,{}).then(function(succ){
          myToken = succ;
          window.localStorage.setItem(Twitter.llave, JSON.stringify(succ));
          $twitterApi.configure(Twitter.id , Twitter.secret , succ);
          $scope.showHomeTimeLine();
         } , function(error){
            console.log(error);
             $scope.debug = error;
         });

      }else{
        $twitterApi.configure(Twitter.id , Twitter.secret , myToken);
        $scope.showHomeTimeLine();
      }

  });

**Comment by erikhu** [comment]
hey thknssss , i love u , just i was foget put the cordova.js

**Comment by nraboy** [comment]
Glad you got it :-)
