### ISSUE TITLE
Twitter OAuth Callback Issue

### ISSUE THREAD

**Issue by SoftYorAdmin** [nraboy/ng-cordova-oauth#287]
When I am using the API, for the Twitter, it is working absolutely fine but after the twitter auth process it showing the browser for few seconds (showing the callback url not found) and then it is automatically closing and working as it should. But it looks rather odd to show this to my ionic app users.
FYI: I m using callback url as "http://localhost/callback" in my ionic app.
I have seen the same issue in you issue list, but not sure what's elegant way for twiiter oauth. 
Appreciate your co-operation.

**Comment by nraboy** [comment]
For providers that don't offer implicit grants (Twitter), you'll need to override the redirect URL to one that actually exists remotely if you want to get rid of the screen.

Best,
