### ISSUE TITLE
New provider request (Pinterest)

### ISSUE THREAD

**Issue by bartello1982** [nraboy/ng-cordova-oauth#29]
I have a hard time to add "Pinterest" support by myself. Is there someone more familiar with OAuth who will be able to add it to this great plugin?

**Comment by nraboy** [comment]
Thanks, I'll take a look and see what is possible.

**Comment by nraboy** [comment]
I'm trying to find the oauth documentation for Pinterest, but cannot find it.  Are you sure Pinterest offers Oauth endpoints?

Can you link me to the documentation?

Thanks,

**Comment by bartello1982** [comment]
Hi Nic,
this is the only thing which I found and I tryied to implement it base on this --> http://wiki.gic.mx/pinterest-developers/

thanks for your time

**Comment by nraboy** [comment]
It doesn't sound like Pinterest advertises Oauth making this seem a little hackish if it even works.  You sure this is a wise solution?

**Comment by nraboy** [comment]
It appears Pinterest no longer supports the Oauth 2.0 functionality.  The documentation has been removed and all third party documentation no longer works.

Closing this ticket.  Sorry,
