### ISSUE TITLE
Error: $cordovaOauth is undefined

### ISSUE THREAD

**Issue by Saqib92** [nraboy/ng-cordova-oauth#290]
Everything done as described. 
[Take a look at my code. ](http://stackoverflow.com/questions/39808256/cordovaoauth-error-in-ionic-cordova-mobile-app)

this is how my console looks like :( 
all dependencies are injected as mentioned. Even my Facebook button is working fine. 
Error: $cordovaOauth is undefined
$scope.googleLogin@http://localhost:8100/js/controllers.js:86:3
anonymous/fn@http://localhost:8100/lib/ionic/js/ionic.bundle.js line 27638 > Function:2:221
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:65427:9
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8100/lib/ionic/js/ionic.bundle.js:30395:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8100/lib/ionic/js/ionic.bundle.js:30495:20
@http://localhost:8100/lib/ionic/js/ionic.bundle.js:65426:7
defaultHandlerWrapper@http://localhost:8100/lib/ionic/js/ionic.bundle.js:16787:3
createEventHandler/eventHandler@http://localhost:8100/lib/ionic/js/ionic.bundle.js:16775:9
triggerMouseEvent@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2953:3
tapClick@http://localhost:8100/lib/ionic/js/ionic.bundle.js:2942:3
tapMouseUp@http://localhost:8100/lib/ionic/js/ionic.bundle.js:3018:5

**Comment by nraboy** [comment]
I see this in your logs:

```
http://localhost:8100
```

Per the README, you cannot use Ionic Serve or any other similar technology.  The application needs to be compiled and installed to your device.  The logs will look different if that were the case.

Best,
