### ISSUE TITLE
How to add a new provider ?

### ISSUE THREAD

**Issue by bonninf** [nraboy/ng-cordova-oauth#294]
I'm trying to add support for the Xee provider and for this I added the oauth.xee.js file and modified the oauth.js file as expected.
However, using in my code, I get the error "$cordovaOauth.xee is not a function". What is normal because the see support is not added neither to ng-cordova-oauth.js nor to ng-cordova-oauth.min.js

What is the process to make that? Should I copy manually the code to ng-cordova-oauth.js?

Thanks for your help
Francois

**Comment by nraboy** [comment]
After adding your changes to the source files you need to build it with grunt.  Did that still not work?

**Comment by bonninf** [comment]
I did know about Grunt. I installed and launched it and all is well working.

Thanks Nic for your help and your very good job.
François

**Comment by nraboy** [comment]
Awesome! Submit a PR request when you're done :-)
