### ISSUE TITLE
ERROR: $cordovaOauth.weibo not working

### ISSUE THREAD

**Issue by phanthinh** [nraboy/ng-cordova-oauth#300]
Hi @nraboy 

I have used code below: 

```
$cordovaOauth.weibo('wxbdca28a6636fcaf5', 'c733009b7ac63e490555f56d6da94f99', ['snsapi_userinfo'], {language:"en",forcelogin: true}).then(function(result) {
        // todo
      }, function(error) {
          // error

      });
```

And see error message at console log of xcode. See attachment pls
![screen shot 2016-10-30 at 12 11 10](https://cloud.githubusercontent.com/assets/5910795/19834635/f7d77e50-9e99-11e6-9524-dca792998c93.png)

Can you help me resolve it?

**Comment by nraboy** [comment]
That error doesn't look related to this library.  Can you provide logs that prove that it is related?
