### ISSUE TITLE
How to open share dialog 

### ISSUE THREAD

**Issue by Sam747** [nraboy/ng-cordova-oauth#302]
I am using Ionic framework my fblogin module is working perfctly  but i have no idea how to invoke share box

**Comment by nraboy** [comment]
Sharing or Facebook APIs is not in the scope of this library.  This library is for oauth only, everything else you'd have to read the Facebook documentation.

**Comment by Sam747** [comment]
Thanks for the answer. There is one thing more I would like to clarify that using this plugin i dont have to put my fb app secret key anywhere  in php sdk i have to put my secret key also.
