### ISSUE TITLE
Google Auth Not working on iOS

### ISSUE THREAD

**Issue by nrnaveen0492** [nraboy/ng-cordova-oauth#306]
![image1](https://cloud.githubusercontent.com/assets/7919923/20298571/ae84785c-ab3c-11e6-9508-8a8380258a79.PNG)

**Comment by davidellolio** [comment]
+1

**Comment by nraboy** [comment]
Google released a statement back in August that it was removing support for the web view, which hybrid applications depend on:

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

Google support will be dropped from ng-cordova-oauth.  Instead you should use the Apache Cordova plugin for the Google SDKs.  It wraps the native Google SDK.

Other providers continue to work correctly.

Best,
