### ISSUE TITLE
Google will no longer allow OAuth requests to Google in embedded browsers, In the coming months

### ISSUE THREAD

**Issue by abdullah-abusall** [nraboy/ng-cordova-oauth#309]
In the coming months, we will no longer allow OAuth requests to Google in embedded browsers known as “web-views:
https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html
Is there a plan to work around this and use the device browser for OAuth requests as they request?
or if there is any way I could prepare for it from now?

Thanks for your great efforts!

**Comment by abdullah-abusall** [comment]
Just noticed your note here:
https://github.com/nraboy/ng-cordova-oauth#important-note-about-google
So I guess there is nothing to be done?

**Comment by nraboy** [comment]
You'll have to use whatever Apache Cordova offers as far as a native plugin solution.

**Comment by skotturi** [comment]
@abdullah-abusall have you found an upgrade path?
