### ISSUE TITLE
Problems with Foursquare

### ISSUE THREAD

**Issue by SduyXD** [nraboy/ng-cordova-oauth#31]
I Have this code that works fine on Emulator, but with device doesn't do anything

User.controller "UserController", ($scope, $cordovaOauth) ->
  $scope.CLIENT_ID = "FOURSQUARE_CLIENT_ID"

  $scope.login = ->
    $cordovaOauth.foursquare $scope.CLIENT_ID
      .then (result) ->
        console.log "Response Object -> " + JSON.stringify result
      .then (error) ->
        console.log "Error -> " + error

I don't known what i'm forgetting

**Comment by nraboy** [comment]
What is the error you get?  Also, what isn't working correctly?

**Comment by SduyXD** [comment]
My error is with the Device.
Device Won't open oauth window it just don't do anything
But with Emulator this code works fine.

**Comment by nraboy** [comment]
What do your logs say?  If it doesn't work you're going to have errors in your logs.

**Comment by SduyXD** [comment]
O.o it seems to be a problem with my routes now its working Ok
