### ISSUE TITLE
I cant login outh with instagram

### ISSUE THREAD

**Issue by alvarheras** [nraboy/ng-cordova-oauth#310]
I cant outh with instagram with more than basic scope. What it is the problem ? I send 

```
$cordovaOauth.instagram(CLIENT_ID,"scope=basic+public_content+relationships+follower_list").then(function(result) {

            $scope.usuario.token = result.access_token;
            userFactory.setUser($scope.usuario);

            $timeout( function() {
                $state.go('app.browse');
            }, 200 );

        });
```

But y only can access to basic information and client only authenticate to basic permision. Please i need. Thx

**Comment by nraboy** [comment]
You might want to validate in the API docs that the scopes you wish to use support implicit grants.  If they do, then make sure you're using the correct scopes.  If they don't, you'll need to use something else.

This library is based off the API docs.  If you're getting an access token it is doing its job.  Actually using the service is something you'll need to read about.

Best,
