### ISSUE TITLE
Security issue - Session keys, token are getting stored 

### ISSUE THREAD

**Issue by lakshaydulani** [nraboy/ng-cordova-oauth#314]
I have implemented Linkedin authentication in an Ionic app.
The InfoSec has come up with this issue that session keys and other tokens are being stored in the app_webview folder.

![screen shot 2017-01-04 at 12 33 38 pm](https://cloud.githubusercontent.com/assets/1629056/21634166/0f49a7ec-d27b-11e6-87f4-698f8dc4de65.png)

Please let me know if there is some configuration which I havnt done. Or any other approach.

Sorry for creating an issue. I checked for the same but didnt find issue for this.

Thanks!

**Comment by nraboy** [comment]
Please see the following line:

https://github.com/nraboy/ng-cordova-oauth/blob/master/src/oauth.linkedin.js#L30

Based on this line we have the following piece of code:

```
clearsessioncache=yes,clearcache=yes
```

That said, nothing should be cached after the InAppBrowser closes.  You might raise an issue ticket with Apache Cordova if data is being stored.  There is nothing in this library that would store anything as it is heavily dependent on the Apache Cordova InAppBrowser.

Best,
