### ISSUE TITLE
Facebook integration: Need to enter fb login credentials even if already logged in to facebook

### ISSUE THREAD

**Issue by kristerd** [nraboy/ng-cordova-oauth#315]
When the user is logged in to facebook in the FB-app or in the browser, the user still needs to enter his/hers fb username and password. 

I'm not sure if this should work or not, but what I expected was that you should only need to click a button to grant access to the app as long as you are logged in (As I'm used to doing elsewhere). 

**Am I doing something wrong or is this how it is supposed to work?**

**Comment by nraboy** [comment]
This plugin uses the InAppBrowser with REST, not the Facebook SDK.  It is a sandboxed login, so regardless where else you are signed into Facebook you'll have to sign in again.

Best,

**Comment by kristerd** [comment]
Ok, thanks for the reply @nraboy :)
