### ISSUE TITLE
Twitter oauth not giving me the email

### ISSUE THREAD

**Issue by l-lawliett** [nraboy/ng-cordova-oauth#324]
I have enable the twitter to give access to user email but when i check the response it not returning the email for the user

**Comment by nraboy** [comment]
This is an oauth library.  All it cares about is the tokens, not user information such as emails:

https://github.com/nraboy/ng-cordova-oauth/blob/master/src/oauth.twitter.js#L81-L91

Above are the lines that figure out what is returned in the response.

Best,
