### ISSUE TITLE
Not able to get email in response in twitter

### ISSUE THREAD

**Issue by simerjit-fwrk** [nraboy/ng-cordova-oauth#325]
Here is the code I am using
`$cordovaOauth.twitter('key', 'secret_key').then(function(result){
 console.log(JSON.stringify(result))
})`
I am getting screen_name, oauth_keys, but unable to get Email. However I have already requested for email in twitter app. Help me to figure this Out! Thanks in advance!
![screen shot 2017-04-25 at 3 54 49 pm](https://cloud.githubusercontent.com/assets/24409710/25380931/a3c2f440-29cf-11e7-9612-c0a73eaf5e9c.png)

**Comment by nraboy** [comment]
Duplicate to inquiry https://github.com/nraboy/ng-cordova-oauth/issues/324

If you're interested in **paid support**, you can reach out here:

https://www.thepolyglotdeveloper.com/hire-me/

Best,
