### ISSUE TITLE
Login Twitter error

### ISSUE THREAD

**Issue by lsparedes** [nraboy/ng-cordova-oauth#326]
Hello, I've been trying to create a twitter login with oauth cordova for weeks. I do not know if I let anything happen but nothing gives me code error, I just do not deploy the modal to login. Could you help me please.

**Comment by nraboy** [comment]
Hi,

If you'd like to purchase support for this library, you can do so here:

https://www.thepolyglotdeveloper.com/hire-me/

Otherwise, please take your questions to the Ionic Framework, Apache Cordova, or PhoneGap forum boards.  The issue tracker is for bugs and feature requests only.

Best,
