### ISSUE TITLE
Problem w/ implementing Venmo OAuth.

### ISSUE THREAD

**Issue by arjunblj** [nraboy/ng-cordova-oauth#33]
I've been trying to implement Venmo OAuth – these are the settings I currently have set:

![screenshot 2015-02-07 11 06 52](https://cloud.githubusercontent.com/assets/1711143/6092732/a5ca663a-aeb9-11e4-8db5-e9867cee0fe5.png)

`app.coffee`, with my routes: https://gist.github.com/arjunblj/626f3be50d9233b9af3c
`controllers.coffee`: https://gist.github.com/arjunblj/f014ba685947cc2e223e
`login.html`, the main login template: https://gist.github.com/arjunblj/2eede80e4ea4e572b935

I was first having issues with setting the callback to `http://localhost/callback` as it didn't have the Ionic port. I tried adding the port (the one `ionic serve` attaches) and it was working on web but was giving me issues on the simulator/iPhone. It was solved int he simulator when I used my computer's hostname.

Would love to know what a good pattern for this is. Thanks!

**Comment by nraboy** [comment]
Thanks for the ticket.

I know I could do this myself, but to save me some time, can you please link the Venmo Oauth documentation this ticket?

Thanks,

**Comment by arjunblj** [comment]
Here it is: https://developer.venmo.com/docs/authentication :-)

**Comment by nraboy** [comment]
Hi @arjunblj 

I just added Venmo to the development branch:

https://github.com/nraboy/ng-cordova-oauth/commit/7e4cc326771b706d7e9c8904c6218929ecfd8851

Can you please download the development branch, test it, and get back to me if it works.  It should.

Also, you cannot use `ionic serve` with this library.

Thanks,
