### ISSUE TITLE
Google errors with "Cannot authenticate via a web browser" 

### ISSUE THREAD

**Issue by pallaviMN** [nraboy/ng-cordova-oauth#330]
1) I am using ionic project 
2) Included ng-Cordova.js, cordova.js, ng-cordova-oauth.js
3) Have inculded cordova in app browser plugin 
4)Using ionic run android But still getting the mentioned error while running in android device

Using hybrid app

**Comment by nraboy** [comment]
Duplicate ticket https://github.com/nraboy/ng-cordova-oauth/issues/283
