### ISSUE TITLE
How to terminate facebook long lived?

### ISSUE THREAD

**Issue by kurtnovice** [nraboy/ng-cordova-oauth#334]
Hi folks, I am in desperate need of guidance. I have been using ionic v1 and my app uses php laravel as the back-end. I manage to get login to work using ng-Cordova oAuth and get a long-lived token for each login. However when I logout, I realize that the long-lived token is still valid and there is no way I can terminate it by firing facebook graph API requests. So far the only measure I can do is deleting the token from local storage and from my server database as well. Funny thing is the ngCordova doesn't have any logout function.

 I tried calling php curl DELETE /{user-id}/permissions using graph facebook URL. Didn't work, tested the validity of the token and yet still it is valid. Anyone has a solution?

**Comment by nraboy** [comment]
This documentation might help:

https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow#logout

It is out of the scope of this plugin. You'll have to consult the Facebook documentation.

Best,
