### ISSUE TITLE
Facebook API 2.6 deprecated on 13 July

### ISSUE THREAD

**Issue by jonners99** [nraboy/ng-cordova-oauth#341]
Facebook is deprecating v2.6 of its API on 13 July 2018 which this package uses. The version should be upped, ideally to latest. Could this also be a configurable option like redirect_uri?

**Comment by jonners99** [comment]
[https://github.com/nraboy/ng-cordova-oauth/pull/342](url)

**Comment by TheQueenOfHearts90** [comment]
[annotations.zip](https://github.com/nraboy/ng-cordova-oauth/files/2431158/annotations.zip)
