### ISSUE TITLE
 strange behaviour on firefoxos

### ISSUE THREAD

**Issue by carloscarcamo** [nraboy/ng-cordova-oauth#35]
Hello all, I need some help.

I want to login using a github account but I have an strange behaviour in my app, after I've logged in on github, the app redirects to my index but it seems that the app embeds the index instead of redirecting to it. See the image below.
![firefoxos](https://cloud.githubusercontent.com/assets/2413746/6231108/25e57404-b68a-11e4-8a09-a62fec181344.png)

You can see [here](https://github.com/mozillaSv/github-issues-app/blob/master/www/js/app.js) my app.js code and also the [manifest.webapp](https://github.com/mozillaSv/github-issues-app/blob/master/www/manifest.webapp) code.

my login function:
```js
$cordovaOauth.github('27879518b3200cb586da', '3451fe872df74723655133d8e2c20c68417a4079', ['email'])
.then(function(data){
  console.log(data);
  $rootScope.user = data;
  $rootScope.$apply($rootScope.user);
  $rootScope.userStatus = true;
  $state.go('home');
}, function(err){
  alert(err);
});
```
And the app manifest:
```json
{
  "launch_path": "/index.html",
  "installs_allowed_from": [
    "*"
  ],
  "version": "0.0.1",
  "name": "github-issues",
  "description": "An app for manage your issues at github",
  "developer": {
    "name": "Mozilla El Salvador",
    "url": "http://carloscarcamo.me"
  },
"icons": {
    "60": "/icon/icon-60.png",
    "128": "/icon/icon-128.png"
  },
"redirects":[{
    "from":"http://localhost/callback",
    "to":"/index.html"
  }]
}
```
Note: the redirects at the end of the app manifest is necessary because firefox simulator gives 404 error with http://localhost/callback, so I redirect from http://localhost/callback to my index.

Any thoughts about what i'm doing wrong?

**Comment by nraboy** [comment]
See the official documentation for the required InAppBrowser plugin:

https://github.com/apache/cordova-plugin-inappbrowser/blob/master/doc/index.md#addeventlistener

The event listener, an essential component, is not compatible with Firefox OS.

Because of this, my implementation of Oauth will never work for Firefox OS.  The browser flow will always process in error.

Regards,

**Comment by carloscarcamo** [comment]
Ok. thanks for the info, I will try another way for Oauth!
