### ISSUE TITLE
Twitter login - No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by mrozlukasz** [nraboy/ng-cordova-oauth#36]
Hi,
I have problems with getting the *$cordovaOauth.twitter* working in my ionic app. The full error message is:
```
"XMLHttpRequest cannot load https://api.twitter.com/oauth/request_token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mywebsite.com' is therefore not allowed access. "
```
My config.xml has the following entry:
```javascript
  <access origin="*"/>
```
Is this a bug, or am I missing something?

ionic version: 1.0.0-beta.14
ng-cordova-oauth version: 0.0.8

**Comment by nraboy** [comment]
You may want to read this great tutorial by @saimon24:

http://ionicframework.com/blog/displaying-the-twitter-feed-within-your-ionic-app/

I'm sure he'll add some input to this ticket as well.

Regards,

**Comment by saimon24** [comment]
1. Are you trying to get it running in your browser? As your Origin seems to be http://mywebsite.com, I am curious how you get that URL when called from a device. Cordova Plugins only work on devices!

2. Have you set the correct credentials inside your app?

3. Have you set http://localhost/callback as Callback URL on your created Twitter App?

If those things don't fix your problem, just provide some code and environment you are testing on!

**Comment by mrozlukasz** [comment]
Thanks for quick responces.
A 1. Yes, I'm testing it on my android device with inappbrowser plugin. 
A 2. Yes app credentials are ok, double-checked that
A 3. Yes Twitter app has a localhost callback

I'll try to do implement this following http://ionicframework.com/blog/displaying-the-twitter-feed-within-your-ionic-app/
I've already done cordova0auth.google() authentication method, and it is working fine, I thought it should work similarly. 

All the best

**Comment by mrozlukasz** [comment]
It occured that Ionic Livereload command:
```
ionic run android -l
```
caused my problem. Without -l option it works like a charm.
