### ISSUE TITLE
ng-cordova-oauth is overriding $http.defaults in my application

### ISSUE THREAD

**Issue by mrozlukasz** [nraboy/ng-cordova-oauth#37]
Hi, 
Today I've found some strange behaviour after triggering some requests.
My app:
* Own backend with such REST methods like 
** http://mywebsite.com/api/v1/auth/signin/local/ for sign in to app directly via login/pass
** http://mywebsite.com/api/v1/items/ for authorized users
** http://mywebsite.com/api/v1/items/:item for authorized users
....
* Sign in/up through Twitter/Facebook/Google

The problem I've found, step by step:
* Fail local signin with e-mail and password that do not exist (response ex. 404)
* Open Twitter login with $cordovaOauth.twitter() method, and cancel the process (back button in android)
* Again trigger local signin with same login/pass like previously and got different responce (400 BAD REQUEST)

I was scretching my head what had just happened there, but Chrome Dev Tools explained everything. 
After the twitter request from cordova0auth, requests to my own backend contained Twitter's Authorization header.
The fix is quite simple: http://stackoverflow.com/questions/11876777/set-http-header-for-one-request
If i find some time this weekend I could do a pull request for you.

Best regars,
Łukasz

**Comment by nraboy** [comment]
I just pushed the fix for Twitter since it appears you're using that.  I'll work on the other providers shortly.

Thanks for pointing this out!
