### ISSUE TITLE
Twitter Ouath

### ISSUE THREAD

**Issue by promactkaran** [nraboy/ng-cordova-oauth#39]
$scope.twitterlogin = function(){
   $cordovaOauth.twitter('my_key','my_secret').then(function(result){
        $log.info("result  "+JSON.stringify(result));
        alert("result" + JSON.stringify(result))
      }, function(error){
           $log.error("error   "+error);
        });
   }

While running this code, I am getting an error "null"
I have set my call back url to : http//localhost/callback
What is wrong ? I am working on ios platform iOS 8.1

**Comment by nraboy** [comment]
Have you followed this great tutorial by @saimon24?:

http://ionicframework.com/blog/displaying-the-twitter-feed-within-your-ionic-app/

I haven't received any other reports, but now @saimon24 is included in this issue and I'm sure he'll jump in the help out.

Regards,

**Comment by promactkaran** [comment]
As it turns out, you have to stop your live reload server, and then continue with your Ouath.twiiter! it would work then. Thanks for the link though!

**Comment by nraboy** [comment]
Glad you got it working :-)

**Comment by raviverma89** [comment]
still getting null in error handler.
need help

**Comment by nraboy** [comment]
I encourage you to read through the issue tickets for this project.  Answers to this have been provided many times.
