### ISSUE TITLE
Re-sign in and authorize each time for Google

### ISSUE THREAD

**Issue by rickyk586** [nraboy/ng-cordova-oauth#4]
The re-sign is due to
`clearsessioncache=yes,clearcache=yes`
in window.open()

If this is removed, you no longer have to log in each time.

Having to authorize each time is due to
`approval_prompt=force`

If you change that to `approval_prompt=auto`, you don't have to authorize each time.

The window wasn't closing every time after making these changes. Adding a timeout around the close call seems to have fixed this:

    setTimeout(function(){
        browserRef.close();
    }, 10);

**Comment by nraboy** [comment]
@rickyk586,

Can you please try the latest ng-cordova-oauth and tell me if you still suffer from the `browserRef.close()` issue?

Thanks,

**Comment by nraboy** [comment]
The browser closing issue should be corrected as of commit 2abc489f564cbf336b1ba504a0411d3738369405

**Comment by sagarhedau** [comment]
Can you please let me know how we can prevent  "approval_prompt" when I logged in for the first time using oAuth in ionic mobile application. Though I have set approval_prompt=auto
