### ISSUE TITLE
Support for Odnoklassniki (OK.ru)

### ISSUE THREAD

**Issue by MrPro100** [nraboy/ng-cordova-oauth#42]
Odnoklassniki, OK.ru is a social network service for classmates and old friends. It is popular in Russia and former Soviet Republics.

Please do Oauth provider for this...Thanks.

[Api documentation](http://apiok.ru/wiki/pages/viewpage.action?pageId=42476300)

**Comment by nraboy** [comment]
I'm worried I won't be able to help with this one because I don't know Russian.  The API documentation is in English, but I'll still need to create an account and register an application.

I encourage you or someone else to fork this project and add this provider.

Regards,
