### ISSUE TITLE
Facebook/Google login stuck on "cannot GET /callback screen" on second browser click.

### ISSUE THREAD

**Issue by dragonfire1119** [nraboy/ng-cordova-oauth#43]
After signing in and accepting. It sends me back to the callback say "cannot GET /callback". If I click the Done in the browser it brings an alert up saying "The sign in flow was canceled".

**Comment by nraboy** [comment]
Did you register your Google application as a web app or mobile app?  It needs to be a web app.

The more information you can give me the better since what you provided is very vague.

Thanks,

**Comment by dragonfire1119** [comment]
It's a web app. I noticed when there's a second step of the login you get stuck at that screen. Example: when your logging in with Facebook and you accidentally enter the wrong password and it comes back as a error. 

Then you try it again with the correct username & password and it accepts it. Then it redirects you to the cannot GET /callback & your stuck there. So you have to close that browser window and try again. So if you have to go anywhere in the browser window a second time it fails to initialize the event on the cannot GET /callback. 

That doesn't work with google because you have to accept & agress after you login. I hope this is more info for you. I'm using the ionic platform & the ngCordova. I've also tried it with your repo file to instead of ngCordova.

**Comment by nraboy** [comment]
I'll play around with what you described and report back.

Regards,

**Comment by dragonfire1119** [comment]
@nraboy Just wanting to check if you figured this out maybe. Thanks for your time.

**Comment by nraboy** [comment]
I just tested it and here are the steps I followed:

1. Open application
2. Click login to initiate the cordovaOauth flow
3. Enter incorrect username / password to receive error via Google
4. Enter correct username / password on the same screen that is presenting the error

I received an access token without issue.

If my steps differ from yours let me know.  Otherwise I think you have an issue with your Google configuration, not with the mobile app.

Regards,

**Comment by dragonfire1119** [comment]
My steps

Facebook
======
1. Login with a failed password.
2. Try to login again with a successful password.
3. Successfully logs in.
2. Redirect back to a white screen then it just gets stuck there.

Google
======
1. Login with a successful password.
2. Goes to the accept the scopes screen.
3. Redirect back to a white screen then it just gets stuck there.

Seems like a second step fails to call the event on the white screen.

The white screen redirects you to the redirect uri that you told me to put on the Google api screen.

**Comment by nraboy** [comment]
Just to confirm.  Your issue happens with both Facebook and Google?  I am confused because the ticket title says Google.

Regards,

**Comment by dragonfire1119** [comment]
Are you using the ngCordova or your repo file. Because I'm using.

1. ngCordova ~0.1.12-alpha
2. ionic #1.0.0-rc.0

I think the ionic 1.0 is using angularjs 1.3

**Comment by nraboy** [comment]
I am using the latest version of ngCordovaOauth.

I support both versions (ngCordova and ngCordovaOauth), but because you've posted in my ngCordovaOauth repository rather than ngCordova I assumed you were using that version.

In either scenario, for Google and Facebook, I haven't made any recent changes.

**Comment by nraboy** [comment]
And yes, I am using the latest version of Ionic, Cordova, and the InAppBrowser plugin.

My assumption is still that you have a configuration issue in your Google or Facebook dashboard.

**Comment by dragonfire1119** [comment]
Here's my config on both platforms

Facebook
======
Platform: website
Site URL: http://localhost/callback
Mobile Site URL: http://localhost/callback

Google
======
Platform: Client ID for web application
REDIRECT URIS: http://localhost/callback
JAVASCRIPT ORIGINS: http://localhost/
API: BigQuery API, Debuglet Controller API, Google Cloud SQL, Google Cloud Storage, Google Cloud Storage JSON API , Google+ API

That's all I changed in those new api credentials.

**Comment by nraboy** [comment]
For Facebook you need to specifically set the Oauth callback URL.  Neither of the two you listed are correct.

For Google you need to not set the JavaScript Origins URL.  It is a field that can be left blank and must be left blank for proper usage.

Based on what you provided, my assumption is Facebook doesn't know where to redirect and Google is rejecting requests that don't come from http://localhost/.  Both reasons why it probably isn't working.

Regards,

**Comment by dragonfire1119** [comment]
So I'm guessing the README is not saying put ``http://localhost/callback`` in the website platform Redirect URI your saying put it in the Advanced > Valid OAuth redirect URIs for Facebook? 

I took the JavaScript Origins URL and emptied that field.

Both platforms are redirecting me back to the callback. I see the callback white screen just on the second try to login with both of them it just stays there and doesn't give me the token.

Facebook

Platform: website
Advanced > Valid OAuth redirect URIs: http://localhost/callback

Google

Platform: Client ID for web application
REDIRECT URIS: http://localhost/callback
JAVASCRIPT ORIGINS: empty
API: BigQuery API, Debuglet Controller API, Google Cloud SQL, Google Cloud Storage, Google Cloud Storage JSON API , Google+ API

Thanks for your time.

**Comment by nraboy** [comment]
Are your scopes correct?  My assumption is you're getting more errors in your logs than you think.

Please share your client keys and I'll test them with my code that I've confirmed working.

Regards,

**Comment by dragonfire1119** [comment]
Facebook
=====
```
$scope.facebookLogin = function() {
    document.addEventListener("deviceready", function () {
        $cordovaOauth.facebook("536014456534960", ["email"]).then(function (result) {
            alert('result.access_toke
        }, function (error) {
            // error
        });
    }, false);
}
```
Google
======
```
$scope.googleLogin = function() {
    document.addEventListener("deviceready", function () {
        $cordovaOauth.google("25002918116-n4l4sjhuip2sp9goke32pnr40pijkbu0.apps.googleusercontent.com", ["https://www.googleapis.com/auth/plus.me", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"]).then(function (result) {
            alert(result.access_token);
        }, function (error) {
            alert("Error -> " + error);
        });
    }, false);
}
```

**Comment by nraboy** [comment]
Both worked fine for me using your codes:

```
$scope.googleLogin = function() {
    $cordovaOauth.google("25002918116-n4l4sjhuip2sp9goke32pnr40pijkbu0.apps.googleusercontent.com", ["https://www.googleapis.com/auth/urlshortener", "https://www.googleapis.com/auth/userinfo.email"]).then(function(result) {
        console.log(JSON.stringify(result));
    }, function(error) {
        console.log(error);
    });
}
```

```
$scope.facebookLogin = function() {
    $cordovaOauth.facebook("536014456534960", ["email"]).then(function(result) {
        console.log(JSON.stringify(result));
    }, function(error) {
        console.log(error);
    });
}
```

Maybe your device or simulator is having issues?

**Comment by dragonfire1119** [comment]
I've used the Ionic View, Phonegap, Appgyver they both do the same things. I can never get the simulator to come up without failing. I might try it on my android though I'm trying it on my iPhone 6 plus right now. I guess it's something on my end. I'm starting a fresh ionic project right now to see if that one is corrupted maybe.

**Comment by nraboy** [comment]
To my knowledge the InAppBrowser has issues with the Ionic View.  No idea what Appgyver is, but Phonegap should work if you've set everything up correctly.

**Comment by nraboy** [comment]
I suggest you use Genymotion over the stock Android simulator.

**Comment by dragonfire1119** [comment]
The Phonegap app I have to kill the server to get it not to refresh the app when I open up the InAppBrowser. When I kill the server it seems like the $http doesn't work LOL. Ill try out the genymotion thanks. Seems like problem after problem today with this. Does the genymotion have a console log?

**Comment by nraboy** [comment]
You need to use ADB with Genymotion:

https://blog.nraboy.com/2014/12/debugging-android-source-code-adb/

It is the closest to a real Android device you can get.

**Comment by dragonfire1119** [comment]
@nraboy I got it to work by creating a whole new project & I'm using the simulator now. The Phonegap app doesn't seem to work with your scripts but the sims do. Thanks so much for your help.

**Comment by nraboy** [comment]
I'm happy we found a working solution!

I think all those other products have problems with the Apache Cordova InAppBrowser.  Beyond the InAppBrowser, the library source code is very simplistic.

Regards,

**Comment by cmvee** [comment]
First, many many thanks for your work (and tutorials) on the library!

Just wanted to chime in and say that I've had a similar problem with Google Authentication  (or perhaps it is Ionic or InAppBrowser). Specifically, when running in iOS on a phone (within Ionic View) the app never gets past the screen where you touch "Accept" where Google asks if you approve of the different scopes for which the app has made a request.

* running within iOS simulator on computer - works
* running within Ionic View on Android - works
* running within Ionic View on Android - hangs

I'm not sure how to debug the app when it is running on the phone within Ionic View. I realize Ionic is not your handiwork, but figured I'd post this issue nonetheless.

For measure, I have not attempted authentication with any other providers at this point.

I call a login view which loads a LoginController which runs the auth code and redirects to a /mail view upon success (at least, it does in all cases except for the one stated - running inside Ionic View on an iPhone). I've tried remote debugging via jsconsole, but I suspect the ```ionic upload``` does something to strip out console.log, or the Ionic View app suppresses them, because I get nothing.

In my app.js:
```
.state('login', {
    url: '/login',
    templateUrl: 'templates/login.html',
    controller: 'LoginController'
  })
```
In my controllers.js:
```
angular.module('starter.controllers', ['starter.services', 'ngCordovaOauth'])

.controller('LoginController', function($scope, $location, $cordovaOauth) {

  $scope.googleLogin = function() {
    console.log("Making OAuth call...");
    $cordovaOauth.google("385715641747-d90f9g1gnfb3lbhksaa4t28t91g6ekmk.apps.googleusercontent.com", ["https://www.googleapis.com/auth/contacts.readonly", "https://www.googleapis.com/auth/gmail.readonly"]).then(function(result) {
        console.log("Response Object -> " + JSON.stringify(result));
        window.localStorage.setItem("access_token", result.access_token);
        $location.path('/tab/mail');
    }, function(error) {
        console.log("Error -> " + error);
    });
  };
    
})
```

My Google callback URL is http://localhost/callback and the origin is empty.
I'm using Ionic 1.0RC1

**Comment by nraboy** [comment]
I've heard the Ionic View has a lot of problems with the InAppBrowser.  I encourage you to build and install like you would a native application.

`ionic build ios` then open the Xcode project produced and install it to your device or simulator.

Regards,

**Comment by dragonfire1119** [comment]
@cmvee Ya ng cordova works fine in the simulator. You can also run ``ionic emulate ios/android``.

**Comment by chocksmith** [comment]
I have been struggling with this for 2 or more days.
It just do not work. I get stuck on the "cannot GET /callback" screen, no matter what.

I am trying Facebook login.

My setup:
- Site URL: http://localhost/callback
- Mobile Site URL: http://localhost/callback
- Ionic: 1.4.1
- I ran:

            cordova plugin add org.apache.cordova.inappbrowser
            cordova plugin add cordova-plugin-whitelist

- At my app.js:

            angular.module('starter', ['ionic', 'ngCordova','starter.controllers', 'starter.services','app-constants','ui.utils.masks.br.phone'])

- At my login-service.js:

            angular.module('starter.services')
    		.service('LoginService', function($http, apiEndPoint, $location, $cordovaOauth) 

	....

            facebookLogin: function() {
                return $cordovaOauth.facebook(appID, ["email", "read_stream", "user_website", "user_location", "user_relationships"]).then(function(result) {
                    
                    accessToken = result.access_token;
                    console.log(JSON.stringify(result));
                    return accessToken
                }, function(error) {
                    alert("There was a problem signing in!  See the console for logs");
                    alert(error);
                    console.log(error);
                });
            },

- At config.xml:

    \<access origin="*"/\>

- Running both on iOS emulator and iOS real device. Emulation both via ionic emulate ios and via Xcode.

I have already reinstalled everything, even Nodejs.

I get this:
![screen shot 2015-05-15 at 10 46 16](https://cloud.githubusercontent.com/assets/999451/7654406/38b6bfae-faf3-11e4-850f-119db4131cfe.png)

**Comment by nraboy** [comment]
What does the console.log error message show?

**Comment by chocksmith** [comment]
Nothing relevant, I believe:

    2015-05-15 11:20:25.015 CasaDoBicho[2416:416771] Apache Cordova native platform version 3.8.0 is starting.
    2015-05-15 11:20:25.016 CasaDoBicho[2416:416771] Multi-tasking -> Device: YES, App: YES
    2015-05-15 11:20:25.018 CasaDoBicho[2416:416771] Unlimited access to network resources
    2015-05-15 11:20:25.701 CasaDoBicho[2416:416771] Resetting plugins due to page load.
    2015-05-15 11:20:26.175 CasaDoBicho[2416:416771] Finished load of: file:///Users/rodrigo/Library/Developer/CoreSimulator/Devices/5CA96D3E-95B3-4D69-922C-597794D9E0EE/data/Containers/Bundle/Application/5922AD8E-FE80-4D20-9663-A32AAA10A5F3/CasaDoBicho.app/www/index.html#/login
    2015-05-15 11:20:27.331 CasaDoBicho[2416:416771] Setting the WebView's frame to {{0, 0}, {375, 623}}
    2015-05-15 11:20:27.342 CasaDoBicho[2416:416771] THREAD WARNING: ['InAppBrowser'] took '88.574951' ms. Plugin should use a background thread.

**Comment by chocksmith** [comment]
Being more precise.
The log I posted was the emulator's log. 
For some reason, it does not show the error shown by the second alert(), which is "Problem authenticating".

Running at the device, the Xcode console shows more information. It shows:

    webView:didFailLoadWithError - -1004: Could not connect to the server.

It makes no sense for me.

**Comment by chocksmith** [comment]
I solved!! The problem is not the ngCordovaOauth.
What was happening is that Facebook was returning an error code instead of the access_token.

May I suggest changing:

                    deferred.reject("Problem authenticating");

for:

                  if ((event.url).indexOf("error_code=100") != 0)
                    deferred.reject("Facebook returned error_code=100: Invalid permissions");
                  else
                    deferred.reject("Problem authenticating");

at facebook: function (clientId, appScope)

**Comment by nraboy** [comment]
I assume you tested this and it works.  Want to submit a pull request so you get credit?

**Comment by chocksmith** [comment]
Yes. It works. Thanks very much. 
Sure, I will do it.
Tks

**Comment by senthilkumar04** [comment]
@nraboy hi, i am able to get the access token successfully but the issue is before it reaches the success function in the loginservice, it shows a white page with error called "Webpage cannot be displayed with url - http://localhost/callback?#access_token=sdfsdf" and then it is getting redirected to the page which i have given in the success function

**Comment by nraboy** [comment]
What repository are you using (ng-cordova or ng-cordova-oauth)?  Also, can you confirm that you're testing on a device or simulator WITHOUT using ionic serve, ionic view, ionic live-reload, or phonegap build?  The four of those will not work correctly.

Usually the webpage cannot be displayed errors happen with the providers that do not offer implicit grants, but Facebook and Google does.  Are you using a different provider?

Regards,

**Comment by senthilkumar04** [comment]
@nraboy i am using ng-cordova and i am using ionic view to test the app. but i found a work around for this problem by creating a callback file in the www directory so that it cant display webpage not found but this is not a correct fix i guess plz help

**Comment by nraboy** [comment]
Sorry, but I told you ionic view will not work correctly.  I also asked to know which provider you're using, but you have not given me that information.

**Comment by senthilkumar04** [comment]
i am using $cordovaOauth provider to connect with facebook

**Comment by nraboy** [comment]
The only thing I can recommend to you is to stop using Ionic View.  I clearly put in the README that it is not compatible.

Regards,

**Comment by Mayur23491** [comment]
Hello I am using Cordova app using Visual Studio 2015 community and simply login in the app using google authentication it's pretty fine login is done by open it in new window (in mobile it open's browser) but after login it gives me the three pop up messages and than don't do anything.

The messages are (which are coming after login process and gives allow permission):
1) gap_init:2
2) gap:[null,"CoreAndroid","messageChannel","CoreAndroid237153815"]
3) gap:[null,"CoreAndroid","show","CoreAndroid237153816"]

by pressing these messages as "OK" it's just showing me my first page from where I logged in using Google and returned url after login is:

http://localhost:4400/?code=4/chL63O9SMzMFZGOlqcB9TFMVUFxWj0E4GYEuVFDQ3gM#.

My configured url settings in console.developers.google.com are:
Authorized JavaScript origins = localhost://4400:index.html
Authorized redirect URIs = http://localhost:4400
and when I am calling the api in that in redirect_uri I pass localhost://4400

I am supposed to go on the second page i.e. index2.html but no such process takes place after window gets popped up.

Where am I doing wrong please suggest me anyone as soon as possible. Thank you

**Comment by nraboy** [comment]
Why are you specifying a port?  This is leading me to believe you are trying to use some serving technology like ionic serve or ionic view.  I cannot stress this enough, those are not compatible.  I also do not know what localhost://4400 is.

You need to set **http://localhost/callback** as your redirect_uri / callback
