### ISSUE TITLE
Upgrade to Graph API v2.x

### ISSUE THREAD

**Issue by jonchen92** [nraboy/ng-cordova-oauth#44]
I got message when login to Facebook with ngCordovaOauth: You must upgrade this app to Graph API v2.x, v1.0 will be deprecated on April 30, 2015

**Comment by nraboy** [comment]
Thanks!

As soon as I have time I'll work on a fix.  For technical reference, please see here:

https://developers.facebook.com/docs/apps/upgrading

**Comment by nraboy** [comment]
Just pushed a change with Facebook 2.0.

Thanks again for reporting it!
