### ISSUE TITLE
Support for Stripe.com

### ISSUE THREAD

**Issue by umbrella-anton-karmazin** [nraboy/ng-cordova-oauth#47]
https://stripe.com/docs/connect/oauth

**Comment by nraboy** [comment]
Thanks, I'll take a look at this when I have some extra time.

**Comment by nraboy** [comment]
Hi @umbrella-anton-karmazin 

I added Stripe support to the development branch:

https://github.com/nraboy/ng-cordova-oauth/commit/ad79be267db13f179dab2dcad2756f71ccc0e9ce

Can you please download, test, and report back?

Thanks,
