### ISSUE TITLE
Add Rally Support

### ISSUE THREAD

**Issue by nraboy** [nraboy/ng-cordova-oauth#5]
Add support for the Rally provider as documented here:

https://github.com/RallySoftware/rally-oauth-examples

**Comment by nraboy** [comment]
Hey @ogomezm 

I added Rally support to the latest development branch.  Can you download, test it, and report back as to whether or not it works for you?

https://github.com/nraboy/ng-cordova-oauth/commit/13776453ffcdc4878987169cf376dae50f6db56d

Thanks,

**Comment by ogomezm** [comment]
Sure, I will test it this evening.

**Comment by nraboy** [comment]
Thanks!

**Comment by nraboy** [comment]
Did you get a chance to test it?

**Comment by ogomezm** [comment]
I tried to test it but I could not finish it.
Let me try to finish it this weekend.

I promised to test it but I am just preparing a concert for next Friday
22nd of May and I am a bit crazy with all that.

If you plan to visit Barcelona, let me know, I can give you some tickets
for free.
