### ISSUE TITLE
How to get the refresh_token?

### ISSUE THREAD

**Issue by kramer65** [nraboy/ng-cordova-oauth#52]
I'm using ng-cordova-oauth in my Ionic/Cordova app to authenticate my app users with google. This all works fine, but the response does not provide me with a refresh_token. As I understand it now, it turns out that ng-cordova-oauth 

> uses the [Implicit grant type](https://tools.ietf.org/html/rfc6749#section-1.3.2) of OAuth 2.0, which per the specification is meant for "clients implemented in a browser using a scripting language such as JavaScript". With this flow the client is directly issued an Access Token, and only that. 

So as far as I understand from [these google oauth docs[(https://developers.google.com/accounts/docs/OAuth2#scenarios) I need to obtain the Authorization code from within the app, send this Authorization code back to my server, and then obtain the `access_code` and `refresh_code` from my server. Is that correct?

And if I'm correct, can I use ng-cordova-oauth to obtain the Authorization code? All tips are welcome!

**Comment by nraboy** [comment]
Hi,

I don't necessarily recommend using anything but the implicit grant type.  Specially when it is available to you.  The other type of authorization should be kept server side.  For all providers that offer implicit grants, that version has been added to ng-cordova-oauth.

However, if you'd like to go against the grain, I've done a tutorial on this:

https://blog.nraboy.com/2014/07/using-oauth-2-0-service-ionicframework/

You can certainly add it to a forked version of this repository.

Regards,

**Comment by kramer65** [comment]
@nraboy 
Thank you for your answer (and thank you even more for creating this awesome lib). I would be happy to only use implicit grant type, but the thing is that my service will be providing server side gmail scraping to extract usable information extracted from the email to the user, and for this I absolutely need the refresh token.

As I understand it I need to save the apiKey and the clientId in the ionic app if I want to get the refresh_token. According to [this answer on StackOverflow](http://stackoverflow.com/a/29157848/1650012) it is not a security vulnarability to save the apiKey and clientId in the Ionic app source code. Do you agree with that?

**Comment by nraboy** [comment]
If you still wish to obtain a refresh token, you'll need to store both the client id and client secret in your application.  Honestly, yes this is a security risk:

https://blog.nraboy.com/2014/11/extract-android-apk-view-source-code/

The purpose behind implicit grants is that you are not storing your secret key in the application making it safe even if it is discovered.

I know you probably don't want to hear this, but scraping data client side is going to be brutally slow for a lot of mobile devices.  This is something that would normally be done server side, then distributed to the app via a RESTful request.

I can't stop you from using a secret key or doing this client side, but you have my two-cents on the subject.

Happy to point you in the right direction either way.

Regards,

**Comment by kramer65** [comment]
Hi @nraboy, I didn't want to frighten you; I wasn't actually planning to scrape the gmail api from the app, I've got a backend server for that. The thing I'm trying to achieve is simply that the user can authorize us through their app to scrape their gmail. So I won't be actually using the refresh_token within the app, I simply want to obtain it from within the app and send it on to my server (my api) to store and use it from there (if there's a better way to do this I'm all ears/eyes).
I want to do it this way because (if I understood it correctly) I can't use my server to authorize the user from within my ionic app. As far as my knowledge goes I need to use pure Javascript from within the app for that, which is what brought me to your (excellent) plugin.

If you could point me into the right direction so that I can let my users authorize me from within my ionic app to somehow (serverside or via the client side to the server or otherwise) get a gmail refresh token I would love to hear it.. :)

**Comment by nraboy** [comment]
I'd do a hackish solution similar to this:

1. Launch the InAppBrowser to call some page on your web server.
2. The page on your web server redirects to the auth flow using the client id and secret key
3. The web server redirects to `http://localhost/callback` or whatever your app is listening for, while appending maybe an access_token to the URL
4. The app stores the access_token and closes the InAppBrowser
5. The web server stores the refresh token

You should be able to hack something together based on the source code of ng-cordova-oauth and the link I gave you.  You're basically just using an InAppBrowser and closing it when your needs are met.  The web server takes care of the rest.

Does this make sense?
