### ISSUE TITLE
Please merge dev branch to master

### ISSUE THREAD

**Issue by MrPro100** [nraboy/ng-cordova-oauth#54]
Hi. I add Odnoklasniki provider and you acept my pull request to dev branch. Please merge dev branch to master and pull requested it to ng-cordova. It would be desirable to have everything in one place. Thanks

**Comment by nraboy** [comment]
Hi,

I have a full-time job that eats up a lot of my availability.  This is a project I do in my spare time as a hobby, so changes happen slowly.

If you don't want to wait for me to have time to merge the changes, I encourage you to merge your changes into ng-cordova.

Regards,

**Comment by MrPro100** [comment]
No I just thought that you forgot about my pool request ). I'm already added this functionality at current project in the source code for ng-cordova. 

Just as much as possible when you have some free time, please drain all in one branch and send poll request to @driftyco . Thanks again for you work :)
