### ISSUE TITLE
dropbox -- what is app key [can we make dynamic]

### ISSUE THREAD

**Issue by inceptivetech** [nraboy/ng-cordova-oauth#59]
Hi,
Thanks for an excellent plugin, I want to use this in my mobile app, however I want to provide my user to push some files on their dropbox, in such cases how app key can be dynamic? do users have to register an app in dropbox first.

Regards,
Suhas

**Comment by nraboy** [comment]
The app key has no affect on users.  You must register the app you plan on distribute with Dropbox and then users will access their own account with their own credentials.

Regards,
