### ISSUE TITLE
IOS webView:didFailLoadWithError - -1004

### ISSUE THREAD

**Issue by Shaolin23** [nraboy/ng-cordova-oauth#61]
I'm running into an issue with Ionic and logging in via LinkedIn. Inappbrowser opens as expected, but upon logging in via the LinkedIn dialog / page I'm getting the following error:

webView:didFailLoadWithError - -1004: Could not connect to the server.
&
Error -> Problem authenticating

Any thoughts? I'm not doing anything fancy outside of the demo code - here's my payload code:

$scope.loginWithLinkedIn = function(){
    var clientId = "ID";
    var clientSecret = "SECRET";
    var appScope = ['r_basicprofile'];
    var state = "dev-09999";

    $cordovaOauth.linkedin(clientId, clientSecret, appScope, state).then(function(result) {
    console.log("Response Object -> " + JSON.stringify(result));
    }, function(error) {
    console.log("Error -> " + error);
    });
  };

I should add that I'm using the latest version of Cordova and cordova-plugin-inappbrowser 1.0.1-dev

**Comment by MyBoon** [comment]
Probably related to #32

**Comment by Shaolin23** [comment]
Unfortunately I'm running on device every time - still encountering the error.

**Comment by MyBoon** [comment]
odd. Did you try to to provide an empty array for appScope? (so it gonna match how your app is configured on linkedin side).

Also make sure you have **http://localhost/callback** as OAuth 2.0 Redirect URLs.
What did you put as 'JavaScript API Domains'?

**Comment by Shaolin23** [comment]
Callback was set to http://localhost/callback.

Here's my code:

  $scope.loginWithLinkedIn = function(){
    var clientId = "key";
    var clientSecret = "secret";
    var appScope = ['r_emailaddress', 'r_basicprofile'];
    var state = "DCEeFWf45A53sdfKef424";

    $cordovaOauth.linkedin(clientId, clientSecret, appScope, state).then(function(result) {
    console.log("Response Object -> " + JSON.stringify(result));
    }, function(error) {
    console.log("Error -> " + error);
    });
  };

I left the domains area empty - should I set this to anything e.g. http://*?

Thanks!

**Comment by MyBoon** [comment]
Try

```js
var appScope = [];
```

and for the domains : **http://localhost/callback,http://localhost/**

**Comment by nraboy** [comment]
Can you guys confirm the following?:

1. You are **not** testing via `ionic serve` or `live-reload`.
2. You are not using the Ionic View app.
3. You are not using a cloud building service such as Phonegap Build.
4. What version of iOS are you testing with?
5. Are you using a device or simulator?

Thanks,

**Comment by Shaolin23** [comment]
Some answers:

1. We're testing using ionic build ios
2. We're not using the view app
3. Not using Phonegap build
4. IOS Version 8.1.3
5. Device (iPhone 5S)

As I was typing this, I was also running a build incorporating MyBoon's suggestions - they worked! (partially). I got the initial 1004 error, but then I got the token return!

I'm guessing this is the race condition described above? I can work around that now - thanks for your help guys.

**Comment by Shaolin23** [comment]
Something else to add - not sure if it has anything to do with things.

I updated the inappbrowser plugin to the latest - 1.0.1-dev, and had to update the plugin check id in ng-cordova-oauth.js to 'cordova-plugin-inappbrowser'

**Comment by nraboy** [comment]
You're not the first person to report this in the past 3 days.

What version is installed when you just run a plain `cordova plugin add org.apache.cordova.inappbrowser`?  If you're using a nightly or beta version of the plugin, I don't yet plan on updating the library to reflect.  Has to be a stable release.

Thanks,

**Comment by Shaolin23** [comment]
It installs 0.6.0

Thanks!

**Comment by nraboy** [comment]
Yea, when Apache updates their plugin repository to reflect the latest version, I will integrate the change.  Until then it will have to remain a manual process for anyone who wants to be bleeding edge.

Sorry about that.

**Comment by Shaolin23** [comment]
No need to apologize! Thanks for creating a great product, and prompt attention to our issue.

**Comment by Shaolin23** [comment]
So switching back to inappbrowser 1.0.1-dev broke things again. I'm not really sure what I'm doing wrong. Should I try uninstalling the latest and go back to the ngCordova version (0.6.0)?

What's the best way to clear current plugins and ensure that I'm not leaving residual bits of different versions of inappbrowser around? Remove platform then add?

**Comment by MyBoon** [comment]
@nraboy Yeah like I said in #32 : "Works like a charm if you build the ionic project and run it on your device." For me, **browserify** was the problem.

**Comment by Shaolin23** [comment]
Hey MyBoon, can you please elaborate on this? As far as I can tell, I'm no using browserify - unless that's part of the default Ionic IOS build process. Please forgive my ignorance - I'm not very experienced in Phonegap / Ionic apps in general. Thanks.

**Comment by MyBoon** [comment]
@Shaolin23 : [browserify](http://browserify.org/) is a dev tool that I'm using. It's not part of the standard ionic build process. I was just letting know @nraboy what was the source of the problem for me.

**Comment by nraboy** [comment]
@Shaolin23, I know this is a little further than you probably wanted to go, but have you tried to build it for Android?  If you throw your project on GitHub, I can take a look and see if I get the same results.

**Comment by nraboy** [comment]
Please see the following:

https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101083345

I got that error, but it seems to have no negative effect on the authentication process.

**Comment by phanthinh** [comment]
Hi @MyBoon @nraboy 

I'm experiencing a similar 
error - upon submitting email and pass through the login dialog I instantly get 
"webView:didFailLoadWithError - -1004"

--------------------------------------- CODE EXAMPLE --------------------------------------
Index.html using code: 
<script src="lib/ngCordova/dist/ng-cordova.js"></script>
<script src="cordova.js"></script>

App.js using code:
document.addEventListener("deviceready", function () {
  $cordovaPlugin.someFunction().then(success, error);
}, false);
....
angular.module(ModuleID, ['ionic', 'ngCordova'])
....

Linkedin.js using code:
Linked.CLIENTID = "75eqw61w9zeubd";
Linked.CLIENTSECRET = "WDWHs6D4B9GUpOkW";
$cordovaOauth.linkedin(Linked.CLIENTID,Linked.CLIENTSECRET, ["r_basicprofile","r_emailaddress"]).then(function(r) {
  // results
  console.log("OK");
  console.log(r);
}, function(error) {
  console.log("FAIL LIB");
  console.log(error);
});


Can you help me this issue? Also, I have test on the ion-lab and serve then it's working fine. Just only not working when build app with Xcode.

Thanks
