### ISSUE TITLE
Error 32 ( Authentication Error ) on Twitter Search API

### ISSUE THREAD

**Issue by asuwend1** [nraboy/ng-cordova-oauth#64]
Hi guys,

I have read many threads on this topic, including: https://github.com/nraboy/ng-cordova-oauth/issues/45
and http://blog.ionic.io/displaying-the-twitter-feed-within-your-ionic-app/ but I suspect I might be missing something here. I'm using "ng-cordova-oauth": "~0.1.0" since it should have the latest fix for related problems.

Problem: "Data:  {"errors":[{"code":32,"message":"Could not authenticate you."}]}" from $http.get(url)... on iOS where var url = 'https://api.twitter.com/1.1/search/tweets.json?q=%40twitterapi';  (Twitter Search API)
Note: This Twitter Status API URL (same as the tutorial by @saimon24) would work fine though 'https://api.twitter.com/1.1/statuses/home_timeline.json'. I could get the correct data back.

I also followed Simon's post by calling this prior to the API call

---------------------
    function createTwitterSignature(method, url, queryObj) {
        var token = angular.fromJson(getStoredToken());
        var oauthObject = {
            oauth_consumer_key: clientId,
            oauth_nonce: $cordovaOauthUtility.createNonce(10),
            oauth_signature_method: "HMAC-SHA1",
            oauth_token: token.oauth_token,
            oauth_timestamp: Math.round((new Date()).getTime() / 1000.0),
            oauth_version: "1.0"
        };
        var signatureObj = $cordovaOauthUtility.createSignature(method, url, oauthObject, queryObj, clientSecret, token.oauth_token_secret);
        $http.defaults.headers.common.Authorization = signatureObj.authorization_header;
    }
--------------------------

Anyone know why it I got code 32 only on the search API? 

Thank you,
ari

**Comment by nraboy** [comment]
Just to confirm.  Using this library you can successfully get an access token?

**Comment by asuwend1** [comment]
Hi Nic,
yes, I was able to get an access token which is good enough to get https://api.twitter.com/1.1/statuses/home_timeline.json .
ari

**Comment by nraboy** [comment]
Unless @saimon24 has any ideas, my Twitter knowledge stops at Oauth, hence why I haven't made an API library.  As long as Oauth works, which you've confirmed, then I'm happy :-)

You may want to ask in the official Twitter forums to see if a bug has been introduced in their API:

https://twittercommunity.com/

Sorry about that.

**Comment by asuwend1** [comment]
Hi Nic,
Thank you for your thought. I will post this question at twittercommunity and will link it to this post. 
Ari

**Comment by asuwend1** [comment]
I have moved this question to twittercommunity: https://twittercommunity.com/t/error-32-authentication-error-on-calling-the-twitter-search-api/36268

Thank you again for the input, Nic.

**Comment by nraboy** [comment]
No problem.  Please report back if something good happens :-)

**Comment by asuwend1** [comment]
Hi Nic,

Just to update, it seems that this problem is triggered IF the query string contains special character that changes on URL encoding. On further investigation it's because the oauth signature generated by cordova ($cordovaOauthUtility.createSignature) does not match the signature generated by twitter - this mismatch most likely causes this error 32.

**Comment by nraboy** [comment]
Thanks for sharing.  I wonder what is happening incorrectly with the special characters.

**Comment by jason-engage** [comment]
@asuwend1 Hey I'm having the exact same issue as you. I have it working for the timeline link, but haven't got it working for search/tweets. I even tried using this really simple query with no special chars:  https://api.twitter.com/1.1/search/tweets.json?q=yoga

Have you had any luck in pinpointing the issue?: Here's the few lines of code that are supposed to work:
                
               var search_tweets_url = 'https://api.twitter.com/1.1/search/tweets.json?q=yoga';
                createTwitterSignature('GET', search_tweets_url);
                return $resource(search_tweets_url).query();

Cheers

**Comment by jason-engage** [comment]
@nraboy any idea what might not be matching up in the signature function?

**Comment by nraboy** [comment]
Getting oauth working is as far as my help will go.  It sounds like there is no issues with getting an access token.  I don't know the Twitter API and this library was never designed to make the API work.

If you cannot get an access token, I'd be happy to help.  Otherwise, I recommend posting in the Twitter developer forums.

Best,

**Comment by jason-engage** [comment]
Ok hopefully I can figure it out and provide it to ngcordova.

**Comment by nraboy** [comment]
You might want to talk to @saimon24 and read his tutorial on the topic:

http://blog.ionic.io/displaying-the-twitter-feed-within-your-ionic-app/

Best,

**Comment by jason-engage** [comment]
That's already covered in higher in this thread, and that's not the issue. Signing this url works fine: 

https://api.twitter.com/1.1/statuses/home_timeline.json

but not this one for example:

https://api.twitter.com/1.1/search/tweets.json?q=yoga

Notice the extra parameter. 

Postman does it right, so I'm going to try to figure out why that is, compared to the createTwitterSignature function

**Comment by jason-engage** [comment]
So here's the code below for anyone that wants to query the Twitter API using ngCordova. There was no issue with ngCordova's createSignature function. This solution requires jQuery to convert an oauthObj to a parameter string.

Here's the main code I used that is based on @saimon24's createTwitterSignature function. And don't forget to add another parameter to it which accepts an Object of your querystring parameters and pass those into the bodyParameters of createSignature(). He has it set to {}, but it should be a variable if you want to do more than login or GET static URL's! BuildParamString and buildParamObj are my own custom functions, you should build your own too.

                //This could be any API Endpoint on Twitter that accepts params
                var search_tweets_url = 'https://api.twitter.com/1.1/search/tweets.json';

                //Add a third parameter to createTwitterSignature function and pass in an object of the search params - make sure it goes into 'bodyParameters'. Also make sure you 'return oauthObject;' at the end of that function. As he wrote it, it returns nothing.
                var oauthObj = createTwitterSignature('GET', search_tweets_url, buildParamObj(keywordObj));

                //Save and Delete the signature because $.param screws it up
                var sigTemp = oauthObj.oauth_signature;
                delete oauthObj.oauth_signature;
                
                //Convert OAuth object to params, adjust for signature
                //Using $http because $resource gives me config errors for action query. Callback instead of promise :( 
                //Make sure to use the $q library
                
                $http.get( search_tweets_url +'?' + buildParamString(keywordObj) + '&' + $.param(oauthObj) + '&oauth_signature=' + sigTemp )
                .success(function(data, status, headers, config) {
                    console.log('Successul HTTP Request', data);
                    tweets = data.statuses;
                    q.resolve(tweets);
                })
                .error(function(data, status, headers, config) {
                    console.log('Rejected HTTP Request ', status, headers);
                    q.reject(reject);
                });

Let me know if you have questions. Good luck

**Comment by nraboy** [comment]
Sounds like someone should blog about this ;-)

Feel free to post the link here if one of you guys does so.

**Comment by saimon24** [comment]
@jason-engage Could you explain a bit more how you build the bodyparams and the paramsstring? Or how the final request signature should look like..

Thanks!

**Comment by jason-engage** [comment]
@saimon24 The bodyparams obj is the 4th parameter of the $cordovaOauthUtility.createSignature function. 

As per @nraboy suggestion I wrote up a blog post on it here: http://en.gg/using-ngcordova-and-cordovaoauth-to-query-twitters-search-api/

Feel free to create your own post and adapt my content if you feel you can make it clearer. For now that's the best I can do. Thanks for the code guys.

**Comment by saimon24** [comment]
As this seemed like a tricky topic to me, I decided to create a AngularJS wrapper library called ngTwitter: https://github.com/saimon24/ng-twitter

For more information check out the according tutorial on my blog: http://devdactic.com/twitter-rest-api-angularjs/

**Comment by nraboy** [comment]
Thanks for sharing this @saimon24!

**Comment by jason-engage** [comment]
Nice work @saimon24
