### ISSUE TITLE
 Could not found InAppBrowser plugin 

### ISSUE THREAD

**Issue by kahwooi** [nraboy/ng-cordova-oauth#66]
I am using ngcordova $cordovaOauth for authentication.

I have added the InAppBrowser:
```cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git```

I and also using Crosswallk as the browser:
```ionic browser add crosswalk```

But when I debug using Chrome I got this error:
```Could not found InAppBrowser plugin```

```cordova plugin list``` give me this result:
cordova-plugin-inappbrowser 1.0.1-dev "InAppBrowser"

but inside ng-cordova.js it is looking for:
```var cordovaMetadata = cordova.require("cordova/plugin_list").metadata;
                if(cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser") === true) {```

**Comment by nraboy** [comment]
There have been reports that the InAppBrowser plugin does not work correctly with Crosswalk.

Can you try to add the plugin using the following:

```
cordova plugin add org.apache.cordova.inappbrowser
```

Regards,

**Comment by kahwooi** [comment]
It works by using this plugin:

```cordova plugin add org.apache.cordova.inappbrowser```

**Comment by TheBosZ** [comment]
It's actually because of the name change with latest Cordova. They're changing all the plugins to a different naming scheme. I'm going to submit a pull request allowing the change.
