### ISSUE TITLE
facebook login error message

### ISSUE THREAD

**Issue by AgentChris** [nraboy/ng-cordova-oauth#68]
hi, great job with the plugin , I have a problem though when i test my app with android , ionicview on my android device everything go well, but when i try to run it on ionicview on my ios device i get the following error:
the page you requested cannot be displayed right now.It may be temporarily unavailable, the link you clicked on may be broken or expired, or you may not have the permission to view this page

**Comment by nraboy** [comment]
I heard the Ionic View app has issues with the InAppBrowser plugin.  You may want to raise an issue in the Ionic forums or bug tracker.

Building your app with the plugin included will work fine, but you must build it yourself, not with any view app.

Regards,
