### ISSUE TITLE
no data returned

### ISSUE THREAD

**Issue by LearningTools** [nraboy/ng-cordova-oauth#69]
hi all, I can not login with facebook oauth, I have the following code controller

```javascript
angular.module('starter').controller('entryController',
	function($scope, $cordovaOauth, $localStorage, $location){

		$scope.fbLogin = function() {
        	$cordovaOauth.facebook("XXXXXXXXXX", ["email"]).then(function(result) {
            //$localStorage.accessToken = result.access_token;
            //$location.path("/profile");
            console.log('Response Object ->' + JSON.stringify(resutl));
        }, function(error) {
            alert("There was a problem signing! See the console for records");
            console.log("Error -> " + error);
        });
    	}


	});
```

when I press the button loguearme with facebook I get the warning callback function of Error,
anyone knows, I am doing wrong?

**Comment by nraboy** [comment]
What is the error message you receive?

**Comment by LearningTools** [comment]
the error is the function alert
function(error) {
            alert("There was a problem signing! See the console for records");

this shows how from my mobile phone when running

**Comment by nraboy** [comment]
That is your custom error message.  What is the actual error message?

**Comment by LearningTools** [comment]
from the browser console me generates this error
Error -> Can not authenticate via a web browser

running the application from my phone shows me the custom alert

**Comment by nraboy** [comment]
You cannot use this library from a web browser.  It has to be from a device or simulator.

If you are still getting an error from your device or simulator, the error message will be different.  Are you still getting one from your device or simulator?

Regards,

**Comment by LearningTools** [comment]
if from my device not only shows the authentic custom error message

**Comment by nraboy** [comment]
You're going to have to dig into your ADB logs if you want to see the actual message.  Only your custom message will appear in the alert.

https://blog.nraboy.com/2014/12/debugging-android-source-code-adb/

Regards,

**Comment by LearningTools** [comment]
o.k thanks for the help
