### ISSUE TITLE
Common OAuth2 support

### ISSUE THREAD

**Issue by geminiyellow** [nraboy/ng-cordova-oauth#70]
hi everyone, i want to use ngCordovaOauth in my project. but , it look link not support common oauth2.
what can i do?

`satellizer` support the common oauth2, but i use ngCordova something other. 

@nraboy could you help me add the common oauth2 function?

**Comment by nraboy** [comment]
What provider are you trying to use?  There are around 20 providers as part of ngCordovaOauth that support Oauth 2.0.

Regards,

**Comment by geminiyellow** [comment]
@nraboy first thanks for your work. i knew there are over 20 providers, but if it not in your list, e.g. #67 , #53 , #30 , #47 ... i must wait until you add something. can not add something more common? and i think your there are lots of same code in your source. if you can create a `ngCordovaOauth2Utility ` like [ngCordovaOauthUtility](https://github.com/nraboy/ng-cordova-oauth/blob/master/ng-cordova-oauth.js#L1234) , i think i will be more better than now.

**Comment by nraboy** [comment]
This is only a side project of mine.  I'd love for you to contribute to the library as well if you've got more time than me :-)

Otherwise, you'll have to wait on my schedule or until someone else jumps in.

Regards,

**Comment by geminiyellow** [comment]
@nraboy oh, sorry for my rude, got it , i will try it later.
