### ISSUE TITLE
Instagram Auth Issue

### ISSUE THREAD

**Issue by AlMon** [nraboy/ng-cordova-oauth#71]
I'm currently developing an app for a client and he's getting an insider's view throughout the process thanks to Ionic View. Amazing how you can do this! But in any event, this app requires access to the Instagram API. I'm now setting up the log in screen, I tested it on Android and it seemed to be fine, but my client tested it on his iPhone and iTouch and wasn't able to tap the "Authorize" button as he was trying to grant access to the app.

I tested it on my iPad thinking it could have been just a problem with his devices, however unlikely it would be that the issue would be found in two devices, and it didn't work for me either. 

Since I was positive this was something to do with my code, I tried to recreate it with the oAuth example app just changing the parameters to Instagram ones, but the result is the same. Any idea on how I could proceed or what the problem could be?

**Comment by nraboy** [comment]
The Ionic View has issues with the InAppBrowser plugin that ngCordovaOauth relies on.  I recommend you only test with a compiled version of the application, whether it be Android or iOS.

Does this help?

Regards,

**Comment by AlMon** [comment]
That was my suspicion. Oh well, I'll have to make do some other way. Thanks for the help!
