### ISSUE TITLE
No redirect with Foursquare

### ISSUE THREAD

**Issue by JBKaloya** [nraboy/ng-cordova-oauth#73]
Hello !
I'm using a button to log-in with Foursquare on my IOS app built with Ionic, here is my code 

$cordovaOauth.foursquare("CLIENT_ID", ["email"]).then(function(result) {
    console.log("Response Object -> " + JSON.stringify(result));
}, function(error) {
    console.log("Error -> " + error);
});

The problem is that the login window appears but when I enter my username and password nothing happens: I'm stuck on this webview.
Thanks !
![unnamed](https://cloud.githubusercontent.com/assets/1856550/7554484/07e96f3c-f72b-11e4-9b27-b81370cfef5c.png)

**Comment by nraboy** [comment]
What do your error logs say?

**Comment by JBKaloya** [comment]
The problem is that I launch my app on Ionic View so I can see the error logs. But the problem isn't coming from Foursquare because my app redirect URL are correctly set.

**Comment by nraboy** [comment]
The Ionic View has problems with the InAppBrowser plugin that this library depends on.  I recommend you build and install directly to your device or simulator.

Let me know how that goes for you.

Regards,
