### ISSUE TITLE
Google OAuth2 is hanging after final button click

### ISSUE THREAD

**Issue by MWaser** [nraboy/ng-cordova-oauth#74]
InAppBrowser starts up correctly calling the following URL:

https://accounts.google.com/o/oauth2/auth?clientid=371315153373-024ti04td3d2biggn7h55n3bkh1s92cv.apps.googleusercontent.com&redirect_uri=http://localhost/callback&scope=email&approval_prompt=force&response_type=token

and showing the "<Application> would like to " screen (with the Cancel & Accept button)

Hitting Accept will cause InAppBrowser to call:

https://accounts.google.com/o/oauth2/approval?as=- &lt;variable&gt;&hl=en_US&pageId=none&xsrfsign=APsBz4gAAAAVVD&lt;variable&gt;

and remain grayed out waiting for a response (which never comes).  It is still possible, though, to cancel using the x in the upper right (and receiving the "Error: the sign in flow was cancelled).

Hitting Cancel will cause InAppBrowser to call:

https://accounts.google.com/o/oauth2/approval?as= &lt;variable&gt;&hl=en_US&pageId=none&xsrfsign=APsBz4gAAAAVVD&lt;variable&gt;

and, like Accept, remain grayed out waiting for a response (which never comes).  Cancelling using the x in the upper right also works just like Accept.

I note that the second url does not include the redirect_uri but have no clue if that matters.

I used the latest versions of ng-cordova-oauth and cordova-plugin-inappbrowser.

**Comment by nraboy** [comment]
I think you mentioned this on Twitter, but for documentation purposes can you please provide the following:

1. What platform(s) does this fail on?
2. What platforms(s), if any, does this succeed on?
3. Are you testing using a device or simulator?
4. Are you using ionic serve, ionic live-reload, or ionic view?
5. How are you installing the InAppBrowser?
6. Are there any errors while it is hung up?

Thanks,

**Comment by MWaser** [comment]
1. It fails on Windows Phone (native) and iPhone6 (Ionic View).  
2. It works on Kindle (both native and Ionic View).
3. Always devices :-)
4. Ionic view for the iPhone and Kindle.  Visual Studio for the Windows Phone.  Also Ionic build for the Kindle.
5.  I've tried several different ways.
cordova plugin add cordova-plugin-inappbrowser installs version 1.0.0
cordova plugin add https://github.com/apache/cordova-plugin-inappbrowser installs 1.0.1-dev
both behave the same
6. There are no errors.  It appears as if it is simply waiting for the Google server . . . . 

Thank you!

**Comment by MWaser** [comment]
By the way, it would be awesome if there were a complete sample project that could be downloaded that was known to work . . . . then either it doesn't work on my set-up or I could alter things line-by-line to resemble my code until it broke (and thereby told me what my problem was . . . .

**Comment by nraboy** [comment]
Here are two working projects I have on GitHub:

https://github.com/nraboy/ng-cordova-facebook-example
https://github.com/nraboy/ionic-imgur-app

In regards to the things you've told me.  Do not use Ionic View.  It has limited to no compatibility with this library due to strange behavior with the InAppBrowser plugin.  Can you try building your project and then installing it to your device?

Thanks,

**Comment by MWaser** [comment]
Oomph.  I'd have to buy a Mac then to build for iPhone, wouldn't I?  I could do that if necessary but . . . . do you know of any other way?

**Comment by nraboy** [comment]
I wouldn't recommend going against the grain.  Build systems like Phonegap Build or Ionic View have too many limitations when it comes to plugins.  They work great for apps with no plugins, but not with.

I don't have any good suggestions beyond, buy a Macbook Air or Mac Mini.

Sorry,

**Comment by MWaser** [comment]
So . . . . any clue on the Windows Phone 8?

**Comment by nraboy** [comment]
I don't have access to any Windows Phone development tools (I'm an Android owner on a Mac).

If I had you try a few things, would you be able to for me?  Ionic doesn't support Windows Phone, but this doesn't seem like an Ionic issue.

Let me know your willingness level and we'll see what happens.  Success may be out of our control in the long run, but it doesn't hurt to try.

Thanks,

**Comment by MWaser** [comment]
I'm getting into this for the long haul, so . . . . yes, I'm willing to try a lot of things.

**Comment by nraboy** [comment]
I'm getting quite a few reports of InAppBrowser shenanigans today.  I fear they changed something again.

Let me play around with some stuff tonight when I'm at my personal computer and I'll report back.

See https://github.com/nraboy/ng-cordova-oauth/issues/75 for reference.

**Comment by nraboy** [comment]
Please see the following:

https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101083345

I've concluded that there are no issues with the current InAppBrowser plugin for Android and iOS.  Not sure on Windows Phone yet.

Will keep you posted.

**Comment by MWaser** [comment]
So . . . . I've got the Macbook set up (finally!) . . . . 

The good news is . . . . the iOS Google OAuth is working just fine (regardless of whether I'm using the newest ngOauth or an older ngCordova with the all instances of org.apache.cordova.inappbrowser changed to cordova-plugin-inappbrowser).

The bad news is . . . . exactly the same code is not working for Windows Phone (necessarily compiled in Visual Studio on my PC)

Any ideas?

**Comment by nraboy** [comment]
Makes me wonder if InAppBrowser has some faults for Windows Phone.  Or instead of faults, maybe differences that need to be accommodated.

Hopefully with your new Mac, you're still experiencing a major positive from everything.

I'm moving this weekend, but as soon as things settle down, I'll spend a little time researching Windows Phone.  I of course won't be able to test anything myself, but maybe I'll get an idea to the problem.

Thanks,

**Comment by MWaser** [comment]
As a Windows guy, I'm required to kvetch about having to use a Mac -- but there's nothing that's been intolerable :-)

The way Visual Studio (2013 since 2015 is still in beta) handles plug-ins is pretty FUBAR (i.e. it either loads really old versions -- 0.52 for InAppBrowser -- if you select the "Core" version or the bleeding-edge dev versions if you use the "Custom" version which wants a Git address).

Worse, I see things like a similar report with Facebook login not working http://stackoverflow.com/questions/19026511/inappbrowser-not-working-in-windows-phone-8-using-phonegap

It is interesting though that Ionic View died in exactly the same place on a iPhone yet Android worked with both Ionic View and the version compiled with Visual Studio . . . .

**Comment by nraboy** [comment]
I'm going to close this ticket for now since it appears to be Windows Phone related.
