### ISSUE TITLE
ability to specify compact page for reddit oauth

### ISSUE THREAD

**Issue by seiyria** [nraboy/ng-cordova-oauth#77]
from [their oauth guide](https://github.com/reddit/reddit/wiki/OAuth2): 

`Note: Use /api/v1/authorize.compact? for a page that's friendlier to small screens.`

Currently you get something that looks like [this](http://puu.sh/hPJvk/e9c6cac7b4.png) if you aren't using the compact auth. I can submit a PR if necessary.

**Comment by nraboy** [comment]
My time is very tight right now.  I'd love it if you submitted a PR!  Please make sure you submit to the development branch.

Thanks!
