### ISSUE TITLE
Support for Envato API

### ISSUE THREAD

**Issue by KrzysiekF** [nraboy/ng-cordova-oauth#79]
Hello,
Can you please add support for new Envato API (https://build.envato.com/)?

Thank you for this great plugin! :)

Regards,
Krzysiek

**Comment by nraboy** [comment]
Added to the development branch https://github.com/nraboy/ng-cordova-oauth/commit/f5ead601494f3ea1f0c1b184ac1bb493121d4305

Can you please download from the development branch and let me know if it works?

Thanks,

**Comment by KrzysiekF** [comment]
Hello,
Thank you very much! I'll try check this as soon as possible.

**Comment by nraboy** [comment]
So is it good?

**Comment by KrzysiekF** [comment]
Hello,
I'm sorry, I have been really busy for last two weeks. I try use new method 'envato', but I have error:
<code>
$cordovaOauth.envato is not a function
</code>
I try change 'envato' to 'facebook', and script working.

**Comment by KrzysiekF** [comment]
OK it works, my mistake :) thank you very much! :)
