### ISSUE TITLE
Feature request: Magento support

### ISSUE THREAD

**Issue by nonec** [nraboy/ng-cordova-oauth#8]
OAuth support for magento API would be great
(http://www.magentocommerce.com/api/rest/authentication/oauth_authentication.html)

**Comment by nraboy** [comment]
This has been pushed to the development branch:

https://github.com/nraboy/ng-cordova-oauth/blob/development/ng-cordova-oauth.js#L797

It will be merged with the master after testing.

**Comment by nonec** [comment]
Thanks very much! :)

**Comment by nraboy** [comment]
This is now in the master branch.
