### ISSUE TITLE
LinkedIn returning 404

### ISSUE THREAD

**Issue by RylanGotto** [nraboy/ng-cordova-oauth#80]
Hi, thank you so much for all the great tutorials and contributions!

I am having some trouble retrieving the request token from LinkedIn mentioned in step 3 here https://developer.linkedin.com/docs/oauth2 . All key values are set properly and I can confirm that the correct data is making it to the server. As well, an extra key value pair named 'state' that is not required in the documentation is making it to the server.  I modified the source code in order to make sure that the 'state' key value pair was not making its way to the server. However, I was still met with a 404 error. I am not sure what to make of this, perhaps Linkedin has changed their API? I will continue to diagnosis and if I find anything I will post here. Any input or suggestions would be a great help.

Thanks again for all you do!
Cheers, Rylan

**Comment by RylanGotto** [comment]
curl -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "grant_type=authorization_code&code=AQTwp-Ue_gORgUJp8B9wVX07ponpAicFVteGzsZ9z2xybtXZe1ysD7O2hnhlqn430ZuAM8CvAY1KUTaWEVJ49v_qK_A20QVQhX3bP_ecoOLD2RU66dA&redirect_uri=http://localhost/callback&client_id=*********&client_secret=**********" https://www.linkedin.com/uas/oauth2/accessToken

I am able to retrieve the toke with the curl request.

**Comment by RylanGotto** [comment]
$http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
        $http.defaults.headers.common['Access-Control-Allow-Origin'] = 'http://localhost:8100';
        
        $http.post("https://www.linkedin.com/uas/oauth2/accessToken", retrivalData)
        .success(function(data) {
            //deferred.resolve(data);
        })
        .error(function(data, status) {
            //deferred.reject("Problem authenticating");
        });

With this request, I get a 200 status but a CORS error.

**Comment by RylanGotto** [comment]
and for whatever reason I get a 404 Page not found when using the LinkedIn ngcordova oauth library.

                           $http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';
                            $http.post("https://www.linkedin.com/uas/oauth2/accessToken", retrivalData)
                            .success(function(data) {
                                deferred.resolve(data);
                            })
                            .error(function(data, status) {
                                deferred.reject("Problem authenticating");
                            })
                            .finally(function() {
                                setTimeout(function() {
                                    browserRef.close();
                                }, 10);
                            });
                        }
                    });

**Comment by nraboy** [comment]
Try to install the new whitelist plugin.  The latest Apache Cordova blocks all outbound requests by default.  I am publishing a blog post on the topic next week.

**Comment by kirankc** [comment]
Nic, I am getting 404 trying to authenticate with Twitter.  Are you aware of any issues? Would installing the new whitelist plugin resolve the issue with Twitter too?

**Comment by nraboy** [comment]
I'm glad you got it working.  I have a post on the topic publishing on Monday.

Regards,

**Comment by RylanGotto** [comment]
Thanks so much, got it working, I will be looking out for that blog post.
Thanks a lot again for all your great info.
