### ISSUE TITLE
Digital Ocean Api v2 ?

### ISSUE THREAD

**Issue by thco** [nraboy/ng-cordova-oauth#84]
Hi there.

I just wonder if you plan to update Digital Ocean to v2 ?

Thanks :)

**Comment by nraboy** [comment]
Please link me to the documentation regarding version 2 of the oauth endpoints.

Thanks,

**Comment by thco** [comment]
Hi !

I'm sorry, I did not check the doc before posting that :/ OAuth still use a v1 endpoint, even on v2.

I close, my bad.
