### ISSUE TITLE
Magento returns empty error during the authentication

### ISSUE THREAD

**Issue by flagthrow** [nraboy/ng-cordova-oauth#90]
Hello,
I'm experiencing strange behaviors with Magento Authentication. 
I'm using ngCordovaOauth and I've tried ngCordova as well but every time I try to authenticate I receive an empty alert. (the $http response is ok)

Did u experience similar problems with magento?  

Thank you for your reply
Giuseppe

**Comment by nraboy** [comment]
What do the logs say? It should return an object even if there is an error.

Paste the full ADB logs please.

**Comment by flagthrow** [comment]
Hello, 
thank you for your help.

I've created this repository containing my code https://github.com/flagthrow/magento-oauth-login
Inside the img_dbg directory you can find 3 images about the console logs, the magento backend configuration and the mobile application output.

These are the steps I followed to create the application: 
ionic start IonicProject blank
cd IonicProject
ionic platform add android
cordova plugin add org.apache.cordova.inappbrowser
cordova plugin add cordova-plugin-whitelist
bower install jsSHa
bower install ng-cordova-oauth -S

I've always tested my code directly on the device, as you write, and I added meta tag information inside index.html in order to avoid the following warnings: 
No Content-Security-Policy meta tag found. Please add one when using the Cordova-plugin-whitelist plugin

I tried to debug my code with chrome//inspect and I'm sure that I have not a 404. 
Actually I think that I isolated the error, indeed inside the adb log I have:

D/SystemWebChromeClient(22511): http://192.168.1.40:8100/: Line 0 : XMLHttpRequest cannot load https://shop.cheersmonkey.com/oauth/initiate. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.40:8100' is therefore not allowed access.
I/chromium(22511): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://shop.cheersmonkey.com/oauth/initiate. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.40:8100' is therefore not allowed access.", source: http://192.168.1.40:8100/ (0)
V/WindowManager(  549): not Base app: Adding window Window{a875531 u0 com.ionicframework.magentooauth777080/com.ionicframework.magentooauth777080.MainActivity} at 7 of 13
W/InputMethodManagerService(  549): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@199f8197 attribute=null, token = android.os.BinderProxy@33f9b0ea


Thank you very much
Giuseppe

**Comment by nraboy** [comment]
Please try ADB instead of Chrome inspect.  CORS errors are usually related to improper installation or testing.

Regards,

**Comment by nraboy** [comment]
Insufficient information.  Closing the ticket.
