### ISSUE TITLE
Add Native app detection and login in  ngCordova-oauth

### ISSUE THREAD

**Issue by Ajeetlakhani** [nraboy/ng-cordova-oauth#91]
ngCordova-oauth is a great plugin allows 20+ different oauths but it does not use their native apps to login. It always open a web view to login.

For example- If i have already login in my gmail account or google play services then ngCordova-oauth should detect and give an option to login in my app rather then opening gmail in  webview everytime and asking to submit username and password.

many are doing that 
https://github.com/EddyVerbruggen/cordova-plugin-googleplus

If it can be done in ng-cordova-oauth then it will a great help to login for diffrent oauth from both  native app and webview using single plugin.

**Comment by nraboy** [comment]
ng-cordova-oauth was designed to be generic and work without anyone else's native plugin.

If you want to add a native social networking plugin, I encourage you to fork this project and add it into your local fork.

Regards,
