### ISSUE TITLE
Update README to correct js script path

### ISSUE THREAD

**Issue by setheen** [nraboy/ng-cordova-oauth#92]
README currently references :

ng-cordova-oauth/ng-cordova-oauth.min.js

The script actually lives at ng-cordova-oauth/dist/ng-cordova-oauth.min.js

**Comment by nraboy** [comment]
You're right.  Thanks for opening the issue ticket :-)

**Comment by nraboy** [comment]
This is corrected in https://github.com/nraboy/ng-cordova-oauth/commit/e9e909b57a64be90c1090a232f5dda55a2d51c48

Thanks for reporting!
