### ISSUE TITLE
Chosen SHA variant is not supported

### ISSUE THREAD

**Issue by Guiguillermo** [nraboy/ng-cordova-oauth#93]
Hello,

I'm using $cordovaAuth to connect with Twitter and when I do : 
$cordovaOauth.twitter(clientId, clientSecret);
I got the following error : 

error    Error: Chosen SHA variant is not supported
    at Error (native)
    at new t (http://192.168.1.19:8100/lib/sha-js/sha1.js:12:276)
    at Object.createSignature (http://192.168.1.19:8100/lib/ngCordova/dist/ng-cordova.js:6120:38)
    at Object.twitter (http://192.168.1.19:8100/lib/ngCordova/dist/ng-cordova.js:5623:55)
    at Object.initialize (http://192.168.1.19:8100/js/services/twitter.js:18:18)

Thanks.

**Comment by dhaspden** [comment]
Hey there,

I just went through this yesterday.  It seems that the new version of jsSHA is not supported.  Use version 1.6.0 of jsSHA instead, that seemed to fix it for me.

Regards,

**Comment by Guiguillermo** [comment]
That works for me now ! Thank you !

**Comment by nraboy** [comment]
I'm wondering why breaking changes were introduced in jsSHA 2.0.

I guess use 1.6.0 for now until I can figure out a solution.  Shouldn't cause any negative impact using an older version of the library.

**Comment by saimon24** [comment]
Got this error as well, maybe we need to point it out in the readme as new users are very likely to get stopped with this error.

**Comment by nraboy** [comment]
This has been added to the README.  When time permits I was going to figure out how to get the latest version working, but for now 1.6.0 will have to do.

**Comment by FrancescoMussi** [comment]
Still getting the issue..
Any solution with jssha 2.0.0?
