### ISSUE TITLE
In App Browser opening to ( and sticking on ) blank screen

### ISSUE THREAD

**Issue by iamaro** [nraboy/ng-cordova-oauth#96]
When trying to use oauth for twitter, the in app browser is opening to a blank screen and nothing is happening.

I'm not seeing any errors and am not running in livereload mode

Please help!

Thanks,
Clay
![screen shot 2015-06-24 at 3 36 02 am](https://cloud.githubusercontent.com/assets/260895/8328057/52aa1138-1a22-11e5-8ef7-440480f48b8e.png)

**Comment by nraboy** [comment]
You cannot use live-reload with this library.  It has a history of having strange results where it will work sometimes, but not all the time.

You need to do a complete build and and install for it to work correctly.

Regards,

**Comment by iamaro** [comment]
Thanks for the quick response!

Can you clarify a bit -- what do you mean by doing a 'complete build and install' -- Do i just need to do Ionic build ios again (as I've tried that) or do I have to delete my platforms folder, install the plugin agian, and never run livereload in the future?

Thanks again,
Clay

**Comment by iamaro** [comment]
To clarify, I am NOT using livereload -- are you saying that using livereload at any time in the past will break the project somehow? I dont understand what you're saying I should do to fix

**Comment by nraboy** [comment]
Live-reload, ionic view, and ionic serve cause me all kinds of headaches.  Because they are all still alpha, I recommend not using them.

Regards,

**Comment by okmttdhr** [comment]
@nraboy Hi, in that case, how to debug the application using ng-cordova-oauth?

**Comment by okmttdhr** [comment]
@nraboy Any effective way to debug and develop?

**Comment by nraboy** [comment]
ADB for Android:

https://blog.nraboy.com/2014/12/debugging-android-source-code-adb/
https://blog.nraboy.com/2015/02/properly-testing-ionic-framework-mobile-application/

Regards,
